== Estatística Descritiva

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* Conhecer os conceitos básicos da estatística e, principalmente, a diferença entre população e amostra
* Construir uma tabela estatística
* Conhecer os tipos de variáveis estatísticas
* Construir um histograma
* Identificar e entender o significado dos gráficos estatísticos
* Conhecer e saber calcular as principais medidas de posição
* Conhecer e saber calcular as principais medidas de dispersão
____


=== Conceitos Básicos

// O que é estatística?

A Estatística é a ciência voltada para a construção de técnicas e métodos que permitem tomar 
decisões nos mais deferentes setores do conhecimento. O que hoje se conhece por _Estatística_,
é justamente esse conjunto de ferramentas de pesquisa que envolve, entre outros, o planejamento 
do experimento a ser realizado, a coleta qualificada dos dados, os processos de inferência estatística, 
bem como a análise e o processamento das informações coletadas.

==== Definições importantes

(((População)))
(((Amostra)))
(((Variável)))
(((Censo)))

Na estatística temos algumas definições importantes:

* *População*: Qualquer conjunto de informação que tenha entre si uma característica comum que delimite os elementos pertencentes a ela.
* *Amostra*: É um subconjunto de elementos pertencentes a uma população.
* *Variável*: Dados referêntes a uma característica de interesse, coletados a partir de uma amostra.
* *Censo*: Exame de todos os elementos da população.

.População e Amostra
image::images/descritiva/pop-amostra.eps[scaledwidth="60%"] 

.Exemplo de variável
image::images/descritiva/variavel.eps[scaledwidth="60%"] 



Temos dois tipos de variáveis:

[latexmath]
++++
\[
Qualitativa  \begin{cases}
          Nominal:& \text{sexo, cor dos olhos.} \\[15pt]
          Ordinal:& \text{classe social, grau de instrução.}
      \end{cases}
\]
\bigskip
\[
Quantitativa  \begin{cases}
          Discreta:& \text{número de filhos.} \\[15pt]
          Contínua:& \text{altura, peso, salário.}
      \end{cases}
\]
++++

(((Variável, Qualitativa, Nominal)))
(((Variável, Qualitativa, Ordinal)))
(((Variável, Quantitativa, Discreta)))
(((Variável, Quantitativa, Contínua)))

=== Tabelas Estatísticas

(((Tabelas)))

Na estatística é fundamental aprendermos a representar os dados que serão analisados  por meio de tabelas. 

Uma tabela deve apresentar a seguinte estrutura:

*	Cabeçalho;
*	Corpo;
*	Rodapé.

O cabeçalho deve conter o suficiente para que sejam respondidas as questões:

*	O que está representado?
*	Onde ocorreu?
*	Quando ocorreu?

Além disso, a tabela é um quadro  que resume um conjunto de dados dispostos segundo linhas e colunas de maneira sistemática.

==== Série Cronológica ou Temporal
(((Série, Cronológica)))
(((Série, Temporal)))


Um exemplo muito comum e muito útil de tabela é dado pelas séries temporais. 
Uma série temporal consiste em uma sequência numérica cujos valores variam com o tempo. 

Abaixo vemos como inserir os dados de uma série temporal em uma tabela:

x:[\centerline{\textbf{Vendas da Companhia Alfa - 2007-2009}}]
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Anos & Vendas em R\$ 1.000,00 \\
\hline
2007 &11.425 \\
2008& 18.258\\
2009& 15.798\\
\hline
\end{tabular}
\]
++++
x:[\centerline{\textit{Fonte: Departamento de Marketing.}}]

==== Série Geográfica
(((Série, Geográfica)))

Muitas vezes o dado de interesse pode depender a posição geográfica de onde foram coletados.
Assim, uma série geográfica consiste em uma sequência numérica obtidas em diferentes regiões
em um determinado instante do tempo.


x:[\centerline{\textbf{Empresas Fiscalizadas em 2008}}]
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Regiões & Número de Empresas \\
\hline
Norte &11.425 \\
Nordeste& 18.258\\
Sudeste&28.157\\
Sul& 15.798\\
Centro-Oeste &9.236 \\
\hline
\end{tabular}
\]
++++
x:[\centerline{\textit{Fonte: Mensário Estatístico.}}]

==== Série Específica
(((Série, Específica)))

Uma série importante é formada por dados agrupados por alguma espécie ou característica comum. 
Assim, uma série específica é uma série numérica agrupada por tipo. Temos o exemplo abaixo:

x:[\centerline{\textbf{Matrículas na Pós-graduação da UFPB - 2008}}]
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Áreas de Ensino & Matrículas \\
\hline
Ciências Biológicas &125 \\
Ciências Exatas e Tecnologia& 158\\
Ciências Humanas& 128\\
\hline
\end{tabular}
\]
++++
x:[\centerline{\textit{Fonte: Serviço de Educação e Cultura.}}]

=== Distribuição de Frequência

(((Distribuição de Frequência)))

Uma distribuição de frequência é uma tabela que contém um resumo dos dados obtido em uma amostra.

A distribuição é organizada em formato de tabela, e cada entrada da tabela contém a frequência dos dados
em um determinado intervalo, ou em um grupo.

Abaixo vemos um exemplo simplificado de tabela de distribuição de frequência:

x:[\centerline{\textbf{Altura dos Alunos da UFPB - 2008}}]
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Alturas em metros & Número dos Alunos \\
\hline
1,50 $|\!-$ 1,60 &5 \\
1,60 $|\!-$ 1,70 & 15\\
1,70 $|\!-$ 1,80& 17\\
1,80 $|\!-$ 1,90&3\\
\hline
\end{tabular}
\]
++++
x:[\centerline{\textit{Fonte: Serviço de Saúde.}}]

Na próxima subseção aprenderemos a construir uma distribuição de frequência completa.

==== Construção de uma distribuição de frequência

Para ilustrar como se constrói uma distribuição de frequência, nós vamos considerar um exemplo específico.

Assim, suponha que uma pesquisa foi feita, e o seguinte conjunto de dados foi obtido:

* *Dados Brutos*:

24-23-22-28-35-21-23-33-34-24-21-25-36-26-22-30-32-25-26-33-34-21-31-25-31-26-25-35-33-31.

(((Rol de dados)))

A primeira coisa que fazemos é ordenar os dados do menor para o maior, formando o _rol de dados_:

* *Rol de dados*:

21-21-21-22-22-23-23-24-25-25-25-25-26-26-26-28-30-31-31-31-32-33-33-33-34-34-34-35-35-36.

(((Amplitude Total)))

Em seguida, calculamos a _amplitude total_, ou seja, o maior valor obtido na amostra subtraído do menor
valor obtido na amostra:

* *Amplitude Total* x:[R]:

[latexmath]
++++
\[ R=36-21=15.\]
++++

Vamos agora definir as variáveis de interesse, ou seja, para cada valor distinto obtido na amostra,
atribuiremos uma variável diferente:

* *Variável* x:[X_i]:

[latexmath]
++++
\[X_1=21, \quad X_2=22, \quad X_3=23, \quad X_4=24, \quad \hbox{etc}.\]
++++

O próximo passo é calcular a frequência absoluta das variáveis, ou seja, vamos calcular
quantas vezes cada valor aparece na sequência. Por exemplo, o valor 21 aparece 3 vezes, 
o valor 22 aparece 2 vezes, etc.. Assim, obtemos:

(((Frequência Absoluta)))

* *Frequência Absoluta* x:[F_i]

[latexmath]
++++
F_1=3, \quad F_2=2, \quad F_3=2, \quad F_4=1, \quad \hbox{etc}.
++++

Vamos calcular, agora, o tamanho amostral, ou seja, o número de observações obtidas na amostra.

Desta forma, temos:

(((Tamanho Amostral)))

* *Tamanho Amostral* x:[n]:

[latexmath]
++++
\[n = 30.\]
++++

Queremos, agora, dividir a amostra em uma quantidade de grupos que formarão os intervalos. Cada grupo é chamado de classe,
assim, queremos definir o número de classes a ser considerado na tabela de distribuição de frequência:

* *Número de Classes* x:[K]:

** x:[K=5] para x:[n\leq 25] e x:[K\approx \sqrt{n}], para x:[n>25]. 

** Fórmula de Sturges x:[K\approx 1+3,22\log n.] 

Logo, pela primeira regra temos x:[K=\sqrt{30}\approx 5,48 \approx 6], e pela segunda regra 
x:[K\approx 1+3,22\log 30\approx 5,75 \approx 6.] Desta forma, em ambos os casos temos x:[K=6], que será o valor considerado.

O próximo passo é saber o comprimento de cada intervalo a ser considerado, ou seja, calcular a amplitude de cada
classe. Queremos que todas as classes tenham a mesma amplitude e portanto, temos:

* *Amplitude das Classes* x:[h]:
[latexmath]
++++
\[
h=\frac{R}{K}.
\]
++++

Daí, para o nosso caso, x:[h= \frac{15}{6}=2,5\approx 3]. 

Vamos agora definir os limites das classes. Ou seja, definir os intervalos propriamente ditos. Para tanto, começamos
com o menor valor obtido da amostra, ou equivalentemente, o primeiro valor do _rol de dados_, e vamos
somando a amplitude para definir cada limite de intervalo:

* *Limites das Classes*:
[latexmath]
++++
\[
\begin{array}{l}
21|\!-24\\
24|\!-27\\
27|\!-30\\
30|\!-33\\
33|\!-36\\
36|\!-39
\end{array}
\]
++++

Em seguida, calculamos os pontos médios das classes, que nada mais é que a média aritmética entre os limites 
das classes:

* *Pontos Médios das Classes* x:[pm_i]:

[latexmath]
++++
\[
pm_1=\frac{21+24}{2}=22,5, \quad pm_2=\frac{24+27}{2}=25,5, \quad, etc.
\]
++++
(((Frequência, Absoluta, Acumulada)))

Agora, calculamos as frequências dos dados em cada intervalo e, chamada de _frequência absoluta_, e também a frequência acumulada,
chamada de _frequência absoluta acumulada_, que
considera a soma das frequências dos intervalos anteriores até o intervalo considerado:

* *Frequência Absoluta Acumulada* x:[F_{ac}]:
[latexmath]
++++
\[
\begin{tabular}{c|c|c|c}
\hline
Classes &$pm_i$& $F_i$ &$F_{ac}$ \\
\hline
$21|\!-24$&22,5&7&7\\
$24|\!-27$&25,5&8&15\\
$27|\!-30$&28,5&2&17\\
$30|\!-33$&31,5&4&21\\
$33|\!-36$&34,5&8&29\\
$36|\!-39$&37,5&1&30\\
\hline
Total&-&30&-\\
\hline
\end{tabular}
\]
++++

(((Frequência, Relativa)))

Em seguida, inclui-se as frequências relativas dos dados, ou seja, para cada intervalo calcula-se x:[f_i = F_i/n]. A frequência
relativa, nos informa a proporção dos dados que pertencem a um determinado intervalo.

* *Frequência Relativa* x:[f_i]:

[latexmath]
++++
\[
\begin{tabular}{c|c|c|c|c}
\hline
Classes &$pm_i$ & $F_i$ &$F_{ac}$&$f_i$ \\
\hline
$21|\!-24$&22,5&7&7&0,23\\
$24|\!-27$&25,5&8&15&0,27\\
$27|\!-30$&28,5&2&17&0,07\\
$30|\!-33$&31,5&4&21&0,13\\
$33|\!-36$&34,5&8&29&0,27\\
$36|\!-39$&37,5&1&30&0,03\\
\hline
Total&-&30&-&1,00\\
\hline
\end{tabular}
\]
++++

(((Frequência, Relativa, Acumulada)))

Para finalizar, calculamos a frequência acumulada relativa, ou seja, calculamos para cada intervalo x:[f_{ac} = F_{ac}/n]:

* *Frequência Relativa Acumulada* x:[f_{ac}]:
[latexmath]
++++
\[
\begin{tabular}{c|c|c|c|c|c}
\hline
Classes &$pm_i$& $F_i$ &$F_{ac}$&$f_i$&$f_{ac}$ \\
\hline
$21|\!-24$&22,5&7&7&0,23&0,23\\
$24|\!-27$&25,5&8&15&0,27&0,50\\
$27|\!-30$&28,5&2&17&0,07&0,57\\
$30|\!-33$&31,5&4&21&0,13&0,70\\
$33|\!-36$&34,5&8&29&0,27&0,97\\
$36|\!-39$&37,5&1&30&0,03&1,00\\
\hline
Total&-&30&-&1,00&-\\
\hline
\end{tabular}
\]
++++

=== Gráficos Estatísticos

(((Histograma)))

==== Histograma

O histograma é uma representação gráfica da distribuição de frequência. O histograma é formado 
por uma justaposição de retângulos de bases com mesmo comprimento. O comprimento da base é justamente
a amplitude do intervalo e a altura do retângulo é dada pela frequência absoluta do intervalo.

Assim, uma vez feita a distribuição de frequência, a construção do histograma é uma tarefa muito simples.

Abaixo vemos um exemplo de histograma:

.Histograma
image::images/descritiva/histograma.eps[scaledwidth="60%"] 

==== Polígono de Frequência

(((Polígono de Frequência)))

O polígono de frequência é uma representação gráfica obtida após ligar os pontos médios de cada classe entre si. Se
já tivermos um histograma, basta ligar os pontos médios das bases superiores dos retângulos. 

Abaixo vemos um exemplo de polígono de frequência obtido a partir de um histograma:

.Polígono de Frequência Obtido a Partir de um Histograma
image::images/descritiva/poligono-hist.eps[scaledwidth="60%"] 

Abaixo vemos um exemplo contendo apenas o polígono de frequência:

.Polígono de Frequência Obtido a Partir de um Histograma
image::images/descritiva/poligono.eps[scaledwidth="60%"] 

==== Gráfico de Linhas

(((Gráfico, de Linhas)))

Suponha que temos duas variáveis, por exemplo, podemos ter os dados de uma série temporal, donde uma variável seria
o valor obtido, e a outra variável seria a data em que o valor foi obtido. Outra possibilidade seria colocar
dados de uma série geográfica, onde uma variável seria formada pelos dados e a outra seria a localização geográfica.

O gráfico de linhas então é formado construindo pontos no plano (a partir das duas variáveis) e, em seguida, 
estes pontos são ligados por segmentos de retas.

Abaixo vemos um exemplo de gráfico de linhas de uma série temporal

.Gráfico de linhas
image::images/descritiva/linha.eps[scaledwidth="60%"] 

==== Gráfico de Colunas

(((Gráfico, de Colunas)))

Um gráfico de colunas é formado por uma coleção de colunas, com bases de mesmo comprimento, e igualmente espaçados.
O eixo horizontal do gráfico consiste das diferentes categorias consideradas, e o eixo vertical é proporcional ao valor
do dado.

Abaixo vemos um exemplo de gráfico de colunas:

.Gráfico de colunas
image::images/descritiva/colunas.eps[scaledwidth="60%"] 

==== Gráfico em Barras

(((Gráfico, em Barras)))

O gráfico em barras pode ser entendido como uma variação do gráfico de colunas. De fato, o gráfico em barras
é formado por uma coleção de barras, de mesma altura e igualmente espaçadas. Entretanto, neste caso o eixo
vertical representa as diferentes categorias consideradas e o eixo horizontal é proporcional ao valor dado.

Abaixo vemos um exemplo de gráfico em barras:

.Gráfico em barras
image::images/descritiva/barras.eps[scaledwidth="60%"] 

==== Gráfico de Setores

(((Gráfico, de Setores)))

(((Gráfico, Pizza)))

O gráfico de setores, que também é popularmente conhecido como gráfico pizza, é um gráfico em que um círculo é dividido
em setores (que podem ser pensados como as fatias da pizza), onde cada setor representa uma categoria considerada pelo
conjunto de dados, e os ângulos dos setores são proporcionais aos valores dos dados em cada categoria. Assim,
quanto maior o valor obtido, maior será o ângulo do setor (e assim, maior será a fatia da pizza).

Abaixo vemos um exemplo de gráfico de setores:

.Gráfico de setores
image::images/descritiva/pizza.eps[scaledwidth="60%"] 

=== Medidas de Posição

(((Medidas, de Tendência  Central)))
(((Média)))
(((Moda)))
(((Mediana)))

As medidas de posição são valores que representam a tendência de concentração dos dados observados.

As mais importantes são as _medidas de tendência central_. As três medidas de tendência central 
mais utilizadas são: _média aritmética_, _moda_ e _mediana_.

==== Média Aritmética
É um valor que representa uma característica do conjunto de dados. Essa característica é tal que
a soma dos dados é preservada. A média é obtida a partir de todos os elementos da 
distribuição e do tamanho da amostra x:[n].

(((Média Aritmética)))

Notação: representamos a média de um conjunto de dados por x:[\overline{X}]  (lê-se x:[x] barra).

.Cálculo da Média Aritmética
+
--
* *Dados não agrupados* (brutos) - média aritmética simples.

No caso de uma lista de dados não-agrupados, calculamos a média aritmética pela fórmula:
[latexmath]
++++
\[
\overline{X}=\sum_{i=1}^{n}\frac{X_i}{n}.
\]
++++

.Exemplo de cálculo de média aritmética com dados brutos:
====
Considere os dados x:[2, 3, 7] e x:[8]. Então,
[latexmath]
++++
\[
\overline{X} =\frac{2+3+7+8}{4}=\frac{20}{4}=5.
\]
++++
====

* *Dados agrupados* - média aritmética ponderada.

(((Média Aritmética, Ponderada)))

No caso em que temos os dados agrupados, ou seja, sabemos a frequência de cada observação, 
o cálculo da média aritmética pode ser simplificado. Assim, a média aritmética pode
ser cálculada pela fórmula:
[latexmath]
++++
\[
\overline{X}=\sum_{i=1}^{n}\frac{X_i\cdot F_i}{n}.
\]
++++

.Exemplo de cálculo de média aritmética ponderada
====
Considere a seguinte tabela:
[latexmath]
++++
\[
\begin{tabular}{c|c|c}
\hline
Tempo de Serviço $(X_i)$& $F_i$ & $X_i\cdot F_i$ \\
\hline
4 &3 &12\\
6& 5&30\\
8& 10&80\\
\hline
Total&18 &122\\
\hline
\end{tabular}
\]
++++

Assim, x:[\overline{X}=\frac{122}{18} = 6,78.]
====

* *Dados agrupados em intervalos* - média aritmética ponderada

No caso em que temos os dados agrupados em intervalos, utilizamos a média aritmética ponderada, onde
os pesos são dados pelo ponto médio do intervalo. Assim, a média aritmética é calculada pela fórmula:
[latexmath]
++++
\[
\overline{X}=\sum_{i=1}^{n}\frac{X_i\cdot pm_i}{n},
\]
++++

.Exemplo de cálculo de médias com dados agrupados em intervalos
====
Considere a seguinte tabela:
[latexmath]
++++
\[
\begin{tabular}{c|c|c|c}
\hline
Anos $(X_i)$& $F_i$ &$pm_i$ &$X_i\cdot pm_i$ \\
\hline
$0\vdash 4$ &4 &2&8\\
$4\vdash 8$& 10&6&60\\
$8\vdash 12$& 7&10&70\\
\hline
Total&21 &-&138\\
\hline
\end{tabular}
\]
++++
Assim, x:[\overline{X}=\frac{138}{21} = 6,57.]
====
--

==== Moda

Definimos a moda de um conjunto de dados como o valor mais frequente deste conjunto. 

(((Moda)))

Notação: representamos a moda de um conjunto de dados por x:[Mo].

.Exemplo de modas
====
* 1, 2, 4, 5 e 8 - não existe valor mais frequente - não existe moda (Amodal).
* 2, 2, 3, 7 e 8 - Mo = 2 (Unimodal).
* 1, 1, 10, 5, 5, 8, 7, 2 - Mo = 1 e 5 (Bimodal). 
====

* *Dados agrupados* - Neste caso, a moda é definida como ``classe modal'', isto é, a classe com a maior frequencia.

.Exemplo de cálculo de classe modal
====
Considere a seguinte tabela:
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Tempo de Serviço $(X_i)$& $F_i$ \\
\hline
4 &3 \\
6& 5\\
8& 10\\
\hline
Total&18\\
\hline
\end{tabular}
\]
++++
Assim, Mo = 8 (x:[F_3]).
====

(((Fórmula de Czuber)))

* *Dados agrupados em intervalos*: Neste caso, utiliza-se a fórmula de Czuber:

[latexmath]
++++
\[
{\rm Mo}=l_{\rm Mo} + \left[\frac{h(F_{\rm Mo} - F_{\rm ant})}{2 F_{\rm Mo}-(F_{\rm ant}+F_{\rm Pos})} \right],
\]
++++
onde:

* x:[h] é a amplitude intervalar,

* x:[F_{\rm Mo}] é a frequência da classe modal,

* x:[l_{\rm Mo}] é o limite inferior da classe modal,

* x:[F_{\rm ant}] é a frequência da classe anterior à classe modal,

* x:[F_{\rm Pos}] é a frequência da classe posterior à classe modal.

.Exemplo de cálculo de moda pela fórmula de Czuber
====
Considere a seguinte tabela:
[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
Anos $(X_i)$& $F_i$ \\
\hline
$0\vdash 4$ &4 \\
$4\vdash 8$& 10\\
$8\vdash 12$& 7\\
\hline
Total&21\\
\hline
\end{tabular}
\]
++++

Assim, x:[h = 4, F_{\rm Mo} = 10, l_{\rm Mo} = 4, F_{\rm ant} = 4] e x:[F_{\rm pos} = 7]. Daí
[latexmath]
++++
\[
{\rm Mo} = 4 + \left[ \frac{4\cdot (10-4)}{2\cdot 10 - (4+7)}\right]=6,67.
\]
++++
====

==== Mediana

Definimos a mediana de um conjunto de dados como o valor que divide um conjunto de dados 
(ordenados) em duas partes com a mesma quantidade de dados.

(((Mediana)))

Notação: representamos a mediana de um conjunto de dados por x:[Md].


(((Elemento Mediano)))

O *elemento mediano* (x:[E_{\rm Md}]) aponta o local (nos dados) onde a mediana está localizada. 
A mediana será o valor assumido na posição x:[E_{\rm Md}]. 

* *Dados não agrupados* (brutos) 

** No caso de dados brutos, se o tamanho amostral (x:[n]) é ímpar, temos que x:[E_{\rm Md} = (n+1)/2]. 

** Note que no caso tamanho amostral é par, teremos dois valores possíveis para o elemento mediano: 
x:[n/2] e x:[n/2 +1]. Neste caso a mediana será a média dos valores assumidos nestas posições.

.Exemplo de cálculo de mediana para dados brutos
====
* 1, 2, 4, 5 e 8. Como x:[n] é ímpar, temos x:[E_{\rm Md} = 3], e x:[Md = 4].

* 2, 2, 3, 7, 8 e 10. Aqui x:[n] é par, assim x:[E_{\rm Md,1} = 6/2 = 3] e 
x:[E_{\rm Md,2} = 6/2+1 = 4]. Daí x:[{\rm Md} = (3+7)/2 = 5]. 
====

* *Dados agrupados*

Neste caso, olhar a frequência acumulada ajuda a encontrar a médiana.

** _Caso 1_: x:[n] ímpar. 

.Exemplo de cálculo de mediana com dados agrupados para x:[n] ímpar
====
Considere a seguinte tabela:\vfill

[latexmath]
++++
\[
\begin{tabular}{c|c|c}
\hline
Faltas $(X_i)$& $F_i$& $F_{\rm ac}$ \\
\hline
2 &1& 1 \\
3& 7 & 8\\
4& 3& 11\\
\hline
Total&11 & - \\
\hline
\end{tabular}
\]
++++

Como x:[n=11], temos que x:[E_{\rm Md} = (11 + 1)/2 = 6]. Daí x:[{\rm Md} = 3]. 
Note que a frequência acumulada indica que nas posições de x:[2] até x:[8] temos o valor x:[3].
====

** _Caso 2_: x:[n] par.

.Exemplo de cálculo de mediana com dados agrupados para x:[n] par
====
Considere a seguinte tabela:

[latexmath]
++++
\[
\begin{tabular}{c|c|c}
\hline
Tempo de Serviço $(X_i)$& $F_i$ & $F_{\rm ac}$ \\
\hline
4 &3 & 3\\
6& 5 & 8\\
8& 10& 18\\
\hline
Total&18\\
\hline
\end{tabular}
\]
++++

Neste caso x:[n=18], daí temos x:[E_{\rm Md,1} = 18/2 = 9] e x:[E_{\rm Md,2} = 18/2 +1 = 10]. 
Portanto x:[{\rm Md} = (8+8)/2 = 8.] Note, novamente, que a frequência acumulada indica que nas posições de
x:[9] até x:[18] temos o valor x:[8].
====


(((Fórmula da Mediana)))

* *Dados agrupados em intervalos*

Neste caso, utilizamos x:[E_{\rm Md} = n/2] independentemente de x:[n] ser par ou ímpar.

A classe mediana é a primeira classe tal que x:[F_{\rm ac} \geq E_{\rm Md}].

Portanto, definimos a mediana pela fórmula
[latexmath]
++++
\[
{\rm Md} = l_{\rm Md} + h\cdot\left[ \frac{E_{\rm Md} - F_{\rm ac,ant}}{F_{\rm Md}}\right],
\]
++++

onde,

* x:[l_{\rm Md}] é o limite inferior da classe mediana,

* x:[h] é a amplitude do intervalo,

* x:[F_{\rm ac,ant}] é a frequência acumulada da classe anterior à classe mediana,

* x:[F_{\rm Md}] é a frequência da classe mediana.

.Exemplo do cálculo da mediana para dados agrupados em intervalos
====
Considere a seguinte tabela:

[latexmath]
++++
\[
\begin{tabular}{c|c|c}
\hline
Anos $(X_i)$& $F_i$ & $F_{\rm ac}$\\
\hline
$0\vdash 4$ &4 & 4 \\
$4\vdash 8$& 10 & 14\\
$8\vdash 12$& 7& 21\\
\hline
Total&21\\
\hline
\end{tabular}
\]
++++

Assim, x:[E_{\rm Md} = 21/2 = 10,5], e desta forma temos que a segunda classe é a classe mediana. 
Daí x:[l_{\rm Md} = 4, h = 4, F_{\rm ac,ant} = 4] e x:[F_{\rm Md} = 10]. Portanto,
[latexmath]
++++
\[
{\rm Md} = 4 + 4\cdot\left[\frac{10,5-4}{10}\right] = 6,6.
\]
++++
====

=== Medidas de Dispersão

(((Medidas, de Dispersão)))

* As medidas de dispersão medem o grau de variabilidade dos elementos de uma distribuição;

* O valor zero indica ausência de dispersão;

* A dispersão aumenta à medida que aumenta o valor da medida de dispersão.

.Exemplo de motivação para as medidas de dispersão
====
x:[\centerline{\textbf{Notas de alunos em cinco avaliações, UFPB, 2009.}}]

[latexmath]
++++
\[
\begin{tabular}{c|ccccc|c}
\hline
Alunos& & & Notas& & & Média \\
\hline
Antônio &5&5&5&5&5&5\\
João &6&4&5&4&6&5\\
José &10&5&5&5&0&5\\
Pedro &10&10&5&0&0&5\\
\hline
\end{tabular}
\]
++++

Observa-se que:
* As notas de Antônio não variaram;

* As notas de João variaram menos do que as notas de José;

* As notas de Pedro variaram mais do que as notas de todos os outros alunos.

====

Principais Medidas de Dispersão:

* Amplitude,

* Desvio Médio,

* Variância,

* Desvio Padrão,

* Coeficiente de Variação.

==== Amplitude

(((Amplitude)))

A amplitude nos fornece uma idéia do campo de variação dos elementos. Mais precisamente, ela fornece a maior variação possível dos dados.

A amplitude é dada pela fórmula
[latexmath]
++++
\[
A = X_{\max} -  X_{\min}.
\]
++++

.Exemplo de cálculo de amplitude
====
No exemplo anterior:   
[latexmath]
++++
\[
A_{\hbox{Antônio}}=0;\quad A_{\hbox{João}}=2;\quad A_{\hbox{José}}=10;\quad A_{\hbox{Pedro}}=10.
\]
++++
====

NOTE: A amplitude não mede bem a dispersão dos dados porque, usam-se apenas os valores extremos, 
ao invés de utilizar todos os elementos da distribuição. 


==== Desvio Médio

(((Desvio, Médio)))

Desejando-se medir a dispersão dos dados em relação a média, parece interessante a análise dos desvios
em torno da média. Isto é, análise dos desvios:

[latexmath]
++++
\[
d_i=(X_i-\overline{X}).
\]
++++

Mas a soma de todos os desvios é igual a zero. Isto é:

[latexmath]
++++
\[
\sum_{i=1}^{n} d_i= \sum_{i=1}^{n} (X_i-\overline{X})=0.
\]
++++

Logo, será preciso encontrar uma maneira de se trabalhar com os desvios sem que a soma dê zero.
Dessa forma, define-se o _desvio médio_.

* *Dados não agrupados* (brutos):

Neste caso, calculamos o desvio médio como:

[latexmath]
++++
\[
DM=\sum_{i=1}^{n} \frac{|d_i|}{n}= \sum_{i=1}^{n} \frac{|X_i-\overline{X}|}{n}.
\]
++++

NOTE: Veja que os desvios foram considerados em módulo, evitando-se assim que a soma fosse nula. 

* *Dados agrupados*:

[latexmath]
++++
\[
DM=\sum_{i=1}^{n} \frac{|d_i|\cdot F_i}{n}= \sum_{i=1}^{n} \frac{|X_i-\overline{X}|\cdot F_i}{n}.
\]
++++

NOTE: x:[X_i] representa um valor individual, no caso de uma distribuição de frequência simples, ou o 
ponto médio  da classe (x:[pm_i]), no caso de uma distribuição de frequência em classes.


[IMPORTANT]
====
* O desvio médio é mais vantajoso que a amplitude, visto que leva em consideração todos os valores da distribuição.

* No entanto, não é tão frequentemente empregado, pois não apresenta propriedades matemáticas interessantes.
====


==== Variância

(((Variância, Populacional)))

A variância é a medida de dispersão mais utilizada. É o quociente entre a soma dos quadrados dos desvios e o número de elementos. 
Assim, temos a seguinte definição de _variância populacional_:

* *Dados não agrupados* - (brutos):

Neste caso, a variância é dada pela fórmula:

[latexmath]
++++
\[
\sigma^2=\sum_{i=1}^{N} \frac{d_i^2}{N}= \sum_{i=1}^{N} \frac{(X_i-\overline{X})^2}{N}.
\]
++++

* *Dados agrupados*:

Aqui, podemos utilizar a frequência para simplificar a fórmula:

[latexmath]
++++
\[
\sigma^2=\sum_{i=1}^{N} \frac{d_i^2\cdot F_i}{N}= \sum_{i=1}^{N} \frac{(X_i-\overline{X})^2\cdot F_i}{N}.
\]
++++


NOTE: x:[\sigma^2] indica a variância populacional e lê-se sigma ao quadrado ou sigma dois. Neste caso, 
x:[\overline{X}] e x:[N] da formúla representam a média populacional e o tamanho populacional, respectivamente.

(((Variância, Amostral)))

Temos ainda a seguinte definição de _variância amostral_:
 
* *Dados não agrupados* - (brutos):

Neste caso, a fórmula é dada por
[latexmath]
++++
\[
S^2=\sum_{i=1}^{n} \frac{d_i^2}{n-1}= \sum_{i=1}^{n} \frac{(X_i-\overline{X})^2}{n-1}
\]
++++

* *Dados agrupados*:

Podemos, novamente, utilizar as frequências para simplificar a fórmula:

[latexmath]
++++
\[
S^2=\sum_{i=1}^{n} \frac{d_i^2\cdot F_i}{n-1}= \sum_{i=1}^{n} \frac{(X_i-\overline{X})^2\cdot F_i}{n-1}.
\]
++++

NOTE: x:[X_i] representa um valor individual, no caso de uma distribuição de frequência simples, 
ou o ponto médio  da classe (x:[pm_i]), no caso de uma distribuição de frequência em classes.

[IMPORTANT]
====
Fórmulas práticas para os cálculos das variâncias são dadas a seguir:
[latexmath]
++++
\[
\sigma^2=\frac{1}{N}\Big[\sum_{i=1}^{N}X_i^2\cdot F_i-\frac{(\sum_{i=1}^{N}X_i\cdot F_i)^2}{N}\Big]
\]
++++

ou

[latexmath]
++++
\[
S^2=\frac{1}{n-1}\Big[\sum_{i=1}^{n}X_i^2\cdot F_i-\frac{(\sum_{i=1}^{n}X_i\cdot F_i)^2}{n}\Big]
\]
++++

que foram obtidas por transformações nas respecitivas fórmulas originais.
====

==== Desvio Padrão

(((Desvio, Padrão)))

Temos também outra medida de dispersão, que é a raiz
quadrada da variância, chamada de _desvio padrão_. Assim,

[latexmath]
++++
\[
\sigma = \sqrt{\sigma^2} \quad \hbox{é o desvio desvio padrão populacional}
\]
++++

e

[latexmath]
++++
\[
S = \sqrt{S^2} \quad \hbox{é o desvio desvio padrão amostral.}
\]
++++

NOTE: Para o cálculo do desvio padrão deve-se primeiramente determinar o valor da variância e, em seguida, 
extrair a raiz quadrada desse resultado.


.Exemplo de cálculo das medidas de dispersão
====
Calcular a amplitude, o desvio médio, a variância e o desvio padrão da seguinte distribuição amostral:

[latexmath]
++++
\[
\begin{tabular}{c|c}
\hline
$X_i$& $F_i$ \\
\hline
5&2\\
7& 3\\
8&5 \\
9& 4\\
11& 2\\
\hline
Total&16\\
\hline
\end{tabular}
\]
++++

* *Cálculo da amplitude*:

[latexmath]
++++
\[
A= X_{\max} -  X_{\min}=11-5=6.
\]
++++

* *Cálculo do desvio médio:* 

Primeiramente é preciso do valor da média. Assim,

[latexmath]
++++
\[
\begin{tabular}{c|c|c}
\hline
$X_i$& $F_i$ & $X_i\cdot F_i$ \\
\hline
5&2&10 \\
7& 3&21 \\
8&5 &40 \\
9& 4&36 \\
11& 2&22 \\
\hline
Total&16& 129\\
\hline
\end{tabular}
\]
++++

[latexmath]
++++
\[
\overline{X}=\sum_{i=1}^{n} \frac{X_i\cdot F_i}{n}= \frac{129}{16}=8,06.
\]
++++

Para o cálculo do x:[DM] são abertas novas colunas:

[latexmath]
++++
\[
\begin{tabular}{c|c|c|c|c}
\hline
$X_i$& $F_i$ & $X_i\cdot F_i$&$|X_i-\overline{X}|=|d_i|$&$|d_i|\cdot F_i$ \\
\hline
5&2&10  &$|5-8,06|=3,06$&6,12\\
7& 3&21 &$|7-8,06|=1,06$&3,18\\
8&5 &40 &$|8-8,06|=0,06$&0,30\\
9& 4&36 &$|9-8,06|=0,94$&3,76\\
11& 2&22 &$|11-8,06|=2,94$&5,88\\
\hline
Total&16& 129&-&19,24\\
\hline
\end{tabular}
\]
++++

Portanto,

[latexmath]
++++
\[
DM=\sum_{i=1}^{n} \frac{|d_i|}{n}= \frac{19,24}{16}=1,20.
\]
++++

* *Cálculo do variância amostral*: 

Observe que o cálculo será facilitado, pois sabe-se que: x:[n=16]; 
x:[\sum X_i\cdot F_i= 129]. Resta encontrar x:[\sum X_i^2\cdot F_i]. 
Para tanto, uma nova coluna é considerada na tabela.

[latexmath]
++++
\[
\begin{tabular}{c|c|c|c}
\hline
$X_i$& $F_i$ & $X_i\cdot F_i$ & $X_i^2\cdot F_i$\\
\hline
5&2&10& 50\\
7& 3&21 &147\\
8&5 &40 &320\\
9& 4&36 &324\\
11& 2&22 &242\\
\hline
Total&16& 129&1083\\
\hline
\end{tabular}
\]
++++

Portanto,
[latexmath]
++++
\[
\begin{array}{lll}
S^2&=&\displaystyle\frac{1}{n-1}\Big[\sum_{i=1}^{n}X_i^2\cdot F_i-\frac{(\sum_{i=1}^{n}X_i\cdot F_i)^2}{n}\Big]\\
&=&\displaystyle\frac{1}{16-1}\Big[1083-\frac{(129)^2}{16}\Big]=\frac{1}{15}\Big[1083-\frac{16641}{16}\Big]\\
&=&\displaystyle\frac{1}{15}\Big[\frac{17328-16641}{16}\Big] = \frac{687}{15\cdot 16}=2,86.
\end{array}
\]
++++


Logo, a variância amostral x:[S^2 = 2,86].

* *Cálculo do desvio padrão amostral*:


Como x:[S=\sqrt{S^2}], logo x:[S=\sqrt{2,86}=1,69].

Dessa forma, podemos observar que a distribuição possui média x:[8,06]. Isto é, seus valores estão em torno de 
x:[8,06] e seu grau de concentração é de x:[1,2], medido pelo desvio médio e de x:[1,69], medido pelo desvio padrão.

====


==== Coeficiente de Variação
(((Coeficiente de Variação)))

Trata-se de uma medida relativa de dispersão útil para a comparação em termos relativos do grau de concentração 
em torno da média de séries distintas. É dado por

[latexmath]
++++
\[
CV=\frac{S}{\overline{X}}\times 100.
\]
++++

onde, x:[S] é o desvio padrão amostral e x:[\overline{X}] é a média amostral.

O coeficiente de variação é expresso em porcentagens.

.Exemplo de cálculo do coeficiente de variação
====
Numa empresa, o salário médio dos homens é de R$ 4.000,00, com desvio padrão de R$ 1.500,00, e o das 
mulheres é em média de R$ 3.000,00, com um desvio padrão de R$ 1.200,00. Então:


* Para os homens: 
[latexmath]
++++
\[
CV= \frac{1.500}{4.000}\times 100= 37,5\%.
\]
++++

* Para as mulheres: 
[latexmath]
++++
\[
CV= \frac{1.200}{3.000}\times 100= 40\%.
\]
++++


Logo, podemos concluir que os salários da mulheres apresenta maior dispersão relativa do que o dos homens.
====

Diz-se que a distribuição possui pequena variabilidade, ou dispersão, quando o coeficiente 
der até 10%; média dispersão quando estiver acima de 10% até 20%; e grande dispersão quando superar 20%. 
Alguns analistas consideram:


* Baixa dispersão: x:[CV \leq 15\%];


* Média dispersão: x:[15\% < CV < 30\%];

////
Sempre termine os arquivos com uma linha em branco.
////





