=== Atividades

*1.* Verdadeiro ou Falso?
--
a. {resposta} x:[\{a,a,b,c\} = \{a,b,c\}];

b. {resposta} x:[\{a,\{a\}\} = \{a\}];

c. {resposta} x:[\{a\} \in \{a,\{a\}\}];

d. {resposta} x:[\{a\}\subset \{a,\{a\}\}];

e. {resposta} x:[\{\{a\}\} \subset \{a,\{a\}\}];

f. {resposta} x:[\{a,b\} \subset \{a,\{a,b\}\}];

g. {resposta} x:[\{a,b\}\in \{a,\{a,b\}\}];

h. {resposta} x:[b\in \{a,\{a,b\}\}];

i. {resposta} x:[\emptyset\in \{\emptyset\}];

j. {resposta} x:[\emptyset=\{\emptyset\}];

l. {resposta} x:[\emptyset\subset\{\emptyset\}];

m. {resposta} x:[\{\emptyset\}\subset\{\{\emptyset\}\}];

n. {resposta} x:[ \{\emptyset\}\in\{\{\emptyset\}\}];

o. {resposta} x:[\{\emptyset\}=\{\{\emptyset\}\}].
--

*2.* Sejam x:[A = \{1,2,3,4,\{5\},\{6,7\}\}], x:[B= \{4,\{5\},6,7\}] e x:[C = \{5,6,7\}]. 
Determine os seguintes conjuntos:
--
a. {resposta} x:[A\setminus\emptyset];

b. {resposta} x:[A\setminus A];

c. {resposta} x:[A\setminus C];

d. {resposta} x:[C\setminus A];

e. {resposta} x:[A\setminus B];

f. {resposta} x:[B\setminus A];

g. {resposta} x:[B\setminus C].
--

*3.* Seja x:[M=\{1,2,3,4,\{1\},\{2\},\{3\},\{4\}\}]. Sejam x:[A = \{1,\{2\},3,\{4\}\}] e 
x:[B = \{\{1\},2,\{3\},4\}].
--
a. Mostre que x:[A] e x:[B] são subconjuntos de x:[M], e conclua que podemos falar sobre o complementar
de x:[A] e sobre o complementar de x:[B] (ambos com relação a x:[M]);

b. {resposta} Determine os conjuntos: x:[A^c], x:[B^c], x:[A\cup B^c], x:[A^c\cup B], x:[A^c\cup B^c], x:[A\cup B],
x:[A\cup A^c] e x:[B\cup B^c].

c. {resposta} Determine os conjuntos: x:[A\cap B], x:[A^c\cap B], x:[A^c\cap B^c], x:[A\cap B^c], x:[A\cap A^c] e x:[B\cap B^c].
--


*4.* {resposta}  Quantas palavras contendo 3 letras diferentes podem ser formadas com um alfabeto de 26 letras?


*5.* {resposta} Para fazer uma viagem João Pessoa-Salvador-João Pessoa, posso ir de carro, ônibus ou avião. 
De quantos modos posso escolher os transportes se não desejo usar na volta o mesmo meio
de transporte da ída?


*6.* {resposta} Quantos são os gabaritos possíveis de um teste de 10 questões de múltipla escolha, com cinco alternativas 
por questão?



*7.* {resposta} De quantos modos 3 pessoas podem sentar-se em 5 cadeiras em fila?



*8.* {resposta}  O departamento de computação científica de uma universidade possui 20 professores.
De quantos modos podem ser escolhidos um chefe de departamento, um coordenador da gradução
e um coordenador de pós-graduação?



*9.* {resposta} Quantos são os anagramas da palavra CAPÍTULO?



*10.* {resposta} Quantos são os anagramas da palavra CAPÍTULO que têm a letra C no primeiro lugar E a letra
A no segundo lugar E a letra P no terceiro lugar?



*11.* {resposta} João tem 10 frutas diferentes e deseja fazer vários tipos de saladas de frutas, onde cada salada
contém exatamente 4 frutas. Quantos tipos de saladas de frutas ele pode fazer?



*12.* {resposta} Em uma prova, o estudante deve escolher exatamente 7 questões entre 10 disponíveis. 
Quantas escolhas ele tem?




*13.* {resposta} De quantos modos podemos escolher 6 pessoas, incluindo pelo menos duas mulheres, em um grupo de 7
homens e 4 mulheres?



























