=== Atividades

1. Sejam x:[A,B] e x:[C] três eventos em um espaço de probabilidade. Expresse os seguintes eventos em termos
de x:[A,B] e x:[C]:
+
--
a) Apenas x:[A] ocorre;



b) x:[A] e x:[B] ocorrem, mas x:[C] não ocorre;



c) Os três eventos ocorrem;



d) Pelo menos um dos três ocorrem;



e) Nenhum dos três ocorrem;



f) Exatamente um dos três ocorre;



--

2. Extraem-se 4 cartas de um baralho com 52 cartas. Qual é a probabilidade de que 2 sejam vermelhas e 2 sejam pretas?



3. Qual a probabilidade de que os aniversários de 12 pessoas sejam em meses diferentes?



4. Quatro números são sorteados ao acaso, sem reposição, do conjunto x:[\{0,1,2,\ldots,9\}]. Calcule a probabilidade de que:
+
--
a) Os quatro números sorteados podem ser ordenados de forma consecutiva, por exemplo, x:[\{1,2,3,4\}]. 



b) Todos sejam maiores do que 5.



c) O número 0 seja escolhido.



d) Pelo menos um seja maior do que 7.



e) Todos sejam ímpares.


--

5. Sejam x:[A] e x:[B] dois eventos em um espaço de probabilidade tais que x:[P(A)=1/2],
x:[P(B)=1/4] e x:[P(A\cap B)=1/5]. Calcule as probabilidades dos seguintes eventos:
+
--
a) x:[A] não ocorre;



b) x:[B] não ocorre;



c) Pelo menos um entre x:[A] e x:[B] ocorrem;



d) x:[A] não ocorre e x:[B] sim;



e) x:[B] não ocorre e x:[A] sim;



f) Ocorre exatamente um de x:[A] e x:[B];



g) Não ocorre nenhum de x:[A] e x:[B];



h) Pelo menos um de x:[A] e x:[B] não ocorre.



--

==== Probabilidade Condicional e Independência

6. Escolhe-se ao acaso um número entre 1 e 50. Sabendo que o número é primo, qual é a probabilidade de que seja
ímpar?



7. Em um programa de auditório o participante lança um dado honesto 6 vezes. Ele ganha um prêmio de participação
se obtiver o mesmo número pelo menos duas vezes, e ganha um prêmio milionário se a face 6 aparecer pelo menos
quatro vezes. Qual a probabilidade de que o participante:
+
--
a) Ganhe o prêmio de participação?



b) Ganhe o prêmio milionário?



c) Tenha ganho o prêmio milionário dado que ganhou o prêmio de participação?



--

8. Em um curso preparatório para o vestibular, 1/3 dos estudantes são do sexo masculino e 2/3 são do sexo feminino.
A proporção dos rapazes que estudam matemática é 20% e apenas 10% das moças estudam matemática. Obtenha as probabilidades
de que:
+
--
a) Um estudante escolhido ao acaso estude matemática.



b) Um estudante de matemática escolhido ao acaso seja do sexo feminino.



--


9. Lança-se um dado duas vezes. Considere os eventos: 
[latexmath]
++++
\[
A = \{\hbox{Foi obtido 2 ou 5 no primeiro lançamento}\}
\]
++++
e
[latexmath]
++++
\[
B = \{\hbox{A soma das faces obtidas nos dois primeiros lançamentos é pelo menos 7}\}.
\]
++++
x:[A] e x:[B] são independentes?




10. Dois estudantes, Pedro e Paulo, estão matriculados na turma de Probabilidade e Estatística. Pedro comparece
a 80% das aulas e Paulo comparece a 60%. Suas presenças nas aulas são independentes. Calcule a probabilidade de
que, em determinado dia:
+
--
a) pelo menos um dos estudantes compareça a aula.



b) apenas um deles esteja presente.



--














