== Definições Básicas

(((Modelos Matemáticos)))

Modelos Matemáticos::
+

* *Modelo Determinístico:* Um modelo no qual as condições impostas ao modelo _determinam_ o resultado do experimento. +

* *Modelo Probabilístico:* Modelos nos quais, mesmo mantendo as mesmas condições, o resultado do 
experimento pode variar. Isso se deve a um fator _aleatório_ o qual não podemos controlar.

(((Experimento Aleatório)))

Experimento aleatório:: 
+
--
Consiste em um experimento em que, mesmo mantendo as mesmas condições, o resultado do experimento pode variar.
--

.Exemplos de experimentos aleatórios
====
. Lançar um dado e observar o resultado.

. Jogar três moedas e contar o número de vezes que o resultado foi cara.

. Medir o número de nascimentos na cidade de João Pessoa na última hora.
====

=== Fundamentos de Probabilidade

(((Espaço, amostral)))

Definição: Espaço amostral:: 
+
--
Espaço amostral é o conjunto de todos os resultados possíveis 
de um experimento. Denotamos o conjunto de todos os 
resultados por latexmath:[$\Omega$].
--

.Espaços amostrais associados aos exemplos anteriores
====
. latexmath:[$\Omega = \{1,2,3,4,5,6\}$];

. latexmath:[$\Omega = \{0,1,2,3\}$];

. latexmath:[$\Omega = \{0,1,2,3,\ldots\}, \Omega = \{0,1,2,...,7000000000\}, \ldots $].
====

[NOTE]
====
Observe que no último exemplo tivemos mais de uma opção de espaço amostral. 
Isto não contradiz a definição de espaço amostral. De fato, podemos ter mais 
de uma opção de espaços amostrais, o importante é que cada uma dessas 
opções contenha todos os resultados possíveis.
====

(((Evento)))

Definição: Evento:: 
+
--
Seja latexmath:[$\Omega$] o espaço amostral de um experimento. 
Todo conjunto latexmath:[$A\subset\Omega$] tal que podemos calcular 
a probabilidade de latexmath:[$A$] é chamado de _evento_. 
--

(((Evento, Certo)))
(((Evento, Impossível)))

Destacamos dois eventos importantes: 

. latexmath:[$\Omega$] é chamado de _evento certo_;
. latexmath:[$\emptyset$] é chamado de _evento impossível_. 

[NOTE]
====
O conjunto de todos os eventos possui uma estrutura chamada de latexmath:[$\sigma$]-álgebra.
Apesar da definição de latexmath:[$\sigma$]-álgebra ser muito simples, não há necessidade de 
estudarmos latexmath:[$\sigma$]-álgebras, pois todos os conjuntos que 
utilizaremos ao longo do livro serão eventos. Além disso, as aplicações onde é _realmente_
necessário o uso de latexmath:[$\sigma$]-álgebras fogem do escopo deste livro.
====


Como cada evento é um conjunto, vale a pena descrever os eventos 
obtidos após realizarmos as operações clássicas de conjuntos entre eventos.

(((Eventos, Mutuamente excludentes)))


.Eventos
====
* latexmath:[$A\cup B$]: é o evento ``latexmath:[$A$] ou latexmath:[$B$]'';
* latexmath:[$A\cap B$]: é o evento ``latexmath:[$A$] e latexmath:[$B$]'';
* latexmath:[$A^c$]: é o evento ``não ocorrência de latexmath:[$A$]'';
* latexmath:[$A\subset B$]: significa que se o evento latexmath:[$A$] ocorre, então o evento latexmath:[$B$] ocorre.
* latexmath:[$A\cap B = \emptyset$]: significa que latexmath:[$A$] e latexmath:[$B$] são 
eventos mutuamente excludentes, ou seja, a ocorrência de latexmath:[$A$] implica 
que latexmath:[$B$] não ocorre, e a ocorrência de latexmath:[$B$] implica que latexmath:[$A$] não ocorre.
====

(((Espaço Amostral, Partição)))

Definição: Partição::
+
--
Dado um espaço amostral latexmath:[$\Omega$], uma _partição_ latexmath:[$\mathcal{P} = \{A_{\alpha}, \alpha\in I\}$] 
de latexmath:[$\Omega$] é uma coleção de eventos, latexmath:[$A_{\alpha}$], indexados por latexmath:[$\alpha$], tais que:

* Para todo latexmath:[$\alpha\neq\beta$], latexmath:[$A_{\alpha}\cap A_{\beta} = \emptyset$];
* latexmath:[$\bigcup_{\alpha\in I} A_{\alpha} = \Omega.$]

--

Portanto, temos que os eventos de uma partição são dois-a-dois _mutuamente excludentes_ 
e sua união é todo o espaço amostral. 

.Exemplo de partição
====
Se latexmath:[$\Omega = \{1,2,3,4\}$], então latexmath:[$\{A_1,A_2\}$], onde 
latexmath:[$A_1 = \{1,2,3\}$] e latexmath:[$A_2 = \{4\}$], é uma partição de latexmath:[$\Omega$].
====

=== Noções de Probabilidade
(((Medida, Probabilidade)))

(((Aditividade, Finita)))
(((Aditividade, Contável)))

Definição: Medida de Probabilidade::
+
--
Seja latexmath:[$E$] um experimento. Seja latexmath:[$\Omega$] um espaço amostral,
e seja latexmath:[$E$] um evento de latexmath:[$\Omega$]. Dizemos que latexmath:[$P$] é uma 
medida probabilidade em latexmath:[$\Omega$] se para todo evento latexmath:[$A$], 
temos que latexmath:[$P(A)$] é um número não-negativo, chamado de probabilidade de latexmath:[$A$], 
tal que

* latexmath:[$ 0\leq P(A)\leq 1$];
* latexmath:[$P(\Omega) = 1$];
* _(Aditividade finita)_ Se _A_ e _B_ forem eventos mutuamente excludentes, temos que latexmath:[$P(A\cup B) = P(A) + P(B)$];
* _(Aditividade contável)_ Se latexmath:[$A_i, i=1,2,3,\ldots$] forem eventos dois-a-dois mutuamente excludentes, então, 
[latexmath]
++++
\[P\Big(\bigcup_{i=1}^{\infty} A_i\Big) = \sum_{i=1}^{\infty} P(A_i).\]
++++

--

Provaremos agora algumas consequências desta definição.

Teorema:: 
+
--
Seja latexmath:[$\emptyset$] o conjunto vazio, então latexmath:[$P(\emptyset) = 0$].
--

_Demonstração_::
+
--
Para qualquer evento latexmath:[$A$], podemos escrever latexmath:[$A = A\cup \emptyset$]. 
Como latexmath:[$A$] e latexmath:[$\emptyset$] são mutuamente excludentes, 
decorre da aditividade finita que
latexmath:[$P(A) = P(A\cup \emptyset) = P(A) + P(\emptyset)$]. Desta forma, latexmath:[$P(\emptyset) = 0$].
--

(((Evento, Complementar)))

Teorema::
+
--
Seja latexmath:[$A^c$] o evento complementar de latexmath:[$A$]. Então latexmath:[$P(A^c) = 1- P(A)$].
--

_Demonstração_::
+
--
Podemos escrever latexmath:[$\Omega = A \cup A^c$]. Além disso, 
latexmath:[$A$] e latexmath:[$A^c$] são mutuamente excludentes. Portanto, 
pela aditividade finita, temos que latexmath:[$1 = P(\Omega) = P(A\cup A^c) = P(A)+P(A^c)$]. 
Desta forma, segue que latexmath:[$P(A^c) = 1- P(A)$]. 
--

Teorema:: 
+
--
Sejam latexmath:[$A$] e latexmath:[$B$] dois eventos quaisquer. 
Então latexmath:[$P(A\cup B) = P(A)+P(B) - P(A\cap B)$]. 
--

_Demonstração_::
+
--
Temos que latexmath:[$A\cup B = A\cup (B\cap A^c)$] (faça um desenho) 
e latexmath:[$B = (A\cap B)\cup (B\cap A^c)$]. 
Desta forma, temos que como latexmath:[$A$] e latexmath:[$B\cap A^c$] 
são mutuamente excludentes, vale latexmath:[$P(A\cup B) = P(A) + P(B\cap A^c)$].

Por outro lado, temos que latexmath:[$A\cap B$] e latexmath:[$B\cap A^c$] também são 
mutuamente excludentes. Portanto, segue que
latexmath:[$P(B) = P(A\cap B) + P(B\cap A^c) \Rightarrow P(B\cap A^c) = P(B) - P(A\cap B)$]. 

Juntando as duas equações, obtemos que 
[latexmath]
++++
\[P(A\cup B) = P(A) + P(B) - P(A\cap B).\]
++++
--
(((Princípio, Inclusão e Exclusão)))
Mais geralmente temos o

Teorema _(Princípio da inclusão e exclusão)_::
+
--
Sejam latexmath:[$A_1,A_2,\ldots,A_n$] latexmath:[$n$] eventos quaisquer. Então,

[latexmath]
++++
\[
\begin{array}{lll}
P(A_1\cup A_2\cup \cdots \cup A_n) &=& \displaystyle\sum_{i=1}^n P(A_i) - \displaystyle\sum_{i<j} P(A_i\cap A_j) \\
&+& \displaystyle\sum_{i<j<k} P(A_i\cap A_j\cap A_k) + \cdots+(-1)^{n-1}P(A_1\cap\cdots\cap A_n).
\end{array}
\]
++++
--

Teorema:: 
+
--
Sejam latexmath:[$A$] e latexmath:[$B$] dois eventos. Suponha que latexmath:[$A\subset B$], então latexmath:[$P(A)\leq P(B)$]. 
--

_Demonstração_::
+
--
Temos que latexmath:[$B = A\cup (B\cap A^c)$], com latexmath:[$A$] e latexmath:[$B\cap A^c$] sendo mutuamente excludentes. 

Desta forma,latexmath:[$P(B) = P(A) + P(B\cap A^c)$]. Por outro lado, latexmath:[$P(B\cap A^c) \geq 0$]. 

Portanto, temos que latexmath:[$P(B) \geq P(A)$].
--

Exercício:: 
+
--
Mostre que a coleção de intervalos latexmath:[$\{ (n,n+1\]: n\in \mathbb{R}\}$] é uma 
partição do conjunto dos números reais latexmath:[$\mathbb{R}$].
--

_Solução_::
+
--
Denote por latexmath:[$[x\]$] a parte inteira do número real latexmath:[$x$]. 
Temos que para todo latexmath:[$x$] real, vale 
[latexmath]
++++
\[x\in ([x]-1,[x]]\cup ([x],[x]+1].\]
++++

Portanto, vale latexmath:[$x \in \displaystyle\bigcup_{n\in \mathbb{Z}} (n,n+1\]$], ou seja, 
latexmath:[$\mathbb{R}\subset \displaystyle\bigcup_{n\in \mathbb{Z}} (n,n+1\]$]. 

Por outro lado, latexmath:[$\forall n\in \mathbb{Z}, (n,n+1\]\subset \mathbb{R}$]. 
Daí latexmath:[$\displaystyle\bigcup_{n\in \mathbb{Z}} (n,n+1\] \subset \mathbb{R}$]. 
Portanto, concluímos que 
[latexmath]
++++
\[\mathbb{R} = \displaystyle\bigcup_{n\in \mathbb{Z}} (n,n+1].\]
++++

--


=== Espaços Amostrais Finitos

Seja latexmath:[$\Omega$] um espaço amostral associado a um experimento aleatório 
latexmath:[$E$] com um número finito de resultados possíveis. 
Então latexmath:[$\Omega$] pode ser escrito da seguinte forma: 
latexmath:[$\Omega = \{\omega_1,\ldots,\omega_n\}$], 
para algum número natural latexmath:[$n$]. 

A cada evento simples latexmath:[$\{\omega_i\}$], latexmath:[$i=1,\ldots,n$], 
associamos um número latexmath:[$p_i,i=1,\ldots,n$] de tal forma que duas condições sejam satisfeitas:

. latexmath:[$p_i\geq 0$] para todo latexmath:[$i=1,\ldots,n$];
. latexmath:[$p_1+\cdots+p_n = 1$].

Assim, definimos a probabilidade da ocorrência do resultado latexmath:[$\omega_i,i=1,\ldots,n$] 
como sendo latexmath:[$P(\{\omega_i\}) = p_i$]. 

Suponha que tenhamos um evento latexmath:[$A$] consistindo de latexmath:[$k$] resultados possíveis,
ou seja, latexmath:[$A = \{\omega_{j_1},\ldots,\omega_{j_k}\}$], onde latexmath:[$j_1,\ldots,j_k$] 
assumem valores entre 1 e latexmath:[$n$]. Pela propriedade da aditividade contável, 
a probabilidade do evento latexmath:[$A$] é dada por
[latexmath]
++++
\[P(A) = P(\{\omega_{j_1}\}) + \cdots + P(\{\omega_{j_k}\}) = p_{j_1}+\cdots+p_{j_k}.\]
++++

Exercício::
+
--
Suponha que somente três resultados sejam possíveis em um experimento, 
a saber, latexmath:[$a_1, a_2$] e latexmath:[$a_3$]. Além disso, 
suponha que latexmath:[$a_1$] seja duas vezes mais provável de ocorrer 
do que latexmath:[$a_2$], o qual, por sua vez, é duas vezes mais provável 
de ocorrer do que latexmath:[$a_3$]. Determine as probabilidades de 
ocorrência de latexmath:[$a_1,a_2$] e latexmath:[$a_3$].
--

_Solução_::
+
--
Sejam latexmath:[$p_1,p_2$] e latexmath:[$p_3$] as probabilidades de ocorrências 
de latexmath:[$a_1,a_2$] e latexmath:[$a_3$], respectivamente. Então, temos do enunciado que 
latexmath:[$p_1 = 2p_2$] e que latexmath:[$p_2 = 2p_3$]. 
Como sabemos que latexmath:[$p_1+p_2+p+3 = 1$], temos que latexmath:[$4p_3 + 2p_3 + p_3 = 1$], ou seja, latexmath:[$p_3 = 1/7$]. 

Isto fornece latexmath:[$p_1 = 4/7$], latexmath:[$p_2 = 2/7$] e latexmath:[$p_3 = 1/7$]. 

--

=== Resultados Equiprováveis

(((Resultados, Equiprováveis)))

Suponha que temos um experimento com latexmath:[$n$] resultados possíveis e 
que todos esses resultados sejam equiprováveis, isto é, todos os resultados 
possuem a mesma probabilidade de ocorrência. Neste caso, dizemos que o 
experimento possui resultados equiprováveis. Digamos que os resultados 
possíveis do experimento são latexmath:[$a_1,\ldots,a_n$]. 

Sejam latexmath:[$p_1,p_2,\ldots,p_n$] as probabilidades de ocorrências 
dos eventos latexmath:[$a_1,a_2,\ldots,a_n$], respectivamente. Então, como 
todos os resultados possuem a mesma probabilidade de ocorrência, 
temos que latexmath:[$p_1=p_2=\cdots=p_n = p$]. 

Além disso, sabemos que latexmath:[$p_1+\cdots+p_n = 1$], ou seja, 
latexmath:[$n p = 1$], o que por sua vez implica que latexmath:[$p = 1/n$]. 

Utilizando a propriedade de aditividade contável da probabilidade podemos 
concluir o seguinte resultado: Seja latexmath:[$A$] um evento que contém 
latexmath:[$k$] resultados possíveis, então latexmath:[$P(A) = k/n$]. 

Este método de avaliar a probabilidade do evento latexmath:[$A$] normalmente
é enunciado da seguinte maneira: 
[latexmath]
++++
\[P(A) = \frac{\textrm{número de resultados favoráveis a } A}{\textrm{número de resultados possíveis}}.\]
++++

Exercício::
+
--
Um dado é lançado e todos os resultados são igualmente prováveis. 
O evento latexmath:[$A$] ocorrerá se, e somente se, um número maior do que 4 aparecer, 
isto é, latexmath:[$A = \{5,6\}$]. Calcule latexmath:[$P(A)$].
--

_Solução_::
+
--
Como temos 6 resultados possíveis e 2 resultados favoráveis, temos que latexmath:[$P(A) = 2/6 =1/3$].
--

=== Probabilidade Condicional
(((Probabilidade, Condicional)))

Suponha que temos a seguinte situação: 
Um lote é formado por 100 monitores de computador. Foi verificado que neste lote, 
temos 80 monitores em perfeito estado e 20 monitores defeituosos. Suponha 
que dois monitores são retirados do lote ao acaso. Considere então os eventos:

[latexmath]
++++
\[A = hbox{O primeiro monitor é defeituoso e }~B = \hbox{O segundo monitor é defeituoso}.\]
++++

Suponha que a retirada dos monitores seja com reposição. Isto é, o primeiro monitor é retirado, verifica-se se é defeituoso ou não, e é colocado de volta ao lote. Neste cenário, temos 20 casos favoráveis ao evento _A_, entre 100 casos possíveis, e 20 casos favoráveis ao evento _B_, também entre 100 casos possíveis. Desta forma, no cenário *com reposição*, temos que latexmath:[$P(A) = P(B) = 1/5$].

Entretanto temos um segundo cenário possível: que a retirada dos monitores seja feita *sem reposição*, isto é, o primeiro monitor é retirado, verifica-se se este é defeituoso, e em seguida um segundo monitor é retirado (sem que o primeiro seja devolvido ao lote), donde após a retirada, verifica-se se o segundo monitor é defeituoso ou não.

Neste cenário, ainda temos 20 casos favoráveis ao evento _A_ e 100 casos possíveis. No entanto, para o evento _B_ o problema não se torna fácil, pois não sabemos se no momento da retirada do segundo monitor teremos 19 casos favoráveis ou 20 casos favoráveis. Isto dependerá se o evento _A_ ocorreu ou não. A única coisa certa é que temos 99 casos possíveis para o evento _B_. 

A fim de resolver este problema vamos introduzir um novo conceito, o de probabilidade condicional. Assim que tivermos desenvolvido a teoria o suficiente para resolver o problema acima, terminaremos a solução dele.

Sejam agora, _A_ e _B_ dois eventos associados a um experimento _E_. Suponha que latexmath:[$P(A) >0$], então denotamos por latexmath:[$P(B|A)$] a probabilidade do evento _B_ ocorrer condicionada à ocorrência do evento _A_. Esta probabilidade condicional é definida como
latexmath:[$P(B|A) = \frac{P(A\cap B)}{P(A)}$]. Vale a pena relembrar que estamos supondo que latexmath:[$P(A)>0$].

Observação importante:: Sempre que calculamos a probabilidade condicional latexmath:[$P(B|A)$], o que estamos fazendo na prática é reduzir o espaço amostral original latexmath:[$\Omega$] para um espaço amostral de eventos favoráveis à ocorrência do evento latexmath:[$A$]. Esse espaço amostral é chamado de espaço amostral reduzido.

Exercício:: Dois dados equilibrados (onde todos os resultados são equiprováveis) são lançados. Os resultados são registrados como o par ordenado latexmath:[$(x_1,x_2)$], onde latexmath:[$x_1$] representa o resultado obtido no lançamento do primeiro dado, e latexmath:[$x_2$] representa o resultado do lançamento do segundo dado. Consideremos os eventos:
latexmath:[$A = \{(x_1,x_2); x_1+x_2 = 10\}$] e latexmath:[$B = \{(x_1,x_2); x_1>x_2\}$].
Calcule latexmath:[$P(A|B)$] e latexmath:[$P(B|A)$].

_Solução_: Escrevendo os eventos latexmath:[$A, B$] e latexmath:[$A\cap B$] explicitamente, temos que

latexmath:[$A = \{(5,5), (4,6), (6,4)\}$], latexmath:[$B = \{(2,1),(3,1),(4,1),(5,1),(6,1),(3,2), (4,2), (5,2), (6,2), (4,3), (5,3), (6,3), (5,4), (6,4), (6,5)\}$] e latexmath:[$A\cap B = \{(6,4)\}$]. 

O número de casos totais é 36, pois temos 6 casos possíveis para o primeiro lançamento e 6 casos possíveis para o segundo lançamento. 

Assim, como os resultados são todos equiprováveis, temos que 

latexmath:[$P(A) = \frac{3}{36} = \frac{1}{12}, P(B) = \frac{15}{36} = \frac{5}{12}$] e latexmath:[$P(A\cap B) = \frac{1}{36}$]. 

Assim, segue que 

latexmath:[$P(A|B) = \frac{P(A\cap B)}{P(B)} = \frac{1/36}{5/12} = \frac{1}{15}$] e latexmath:[$P(B|A) = \frac{P(A\cap B)}{P(A)} = \frac{1/36}{1/12} = \frac{1}{3}$].

'''

==== Teorema da Multiplicação
A mais importante consequência da definição da probabilidade condicional é obtida ao escrevermos:

latexmath:[$P(A\cap B) = P(A|B) P(B)$] ou equivalentemente, latexmath:[$P(A\cap B) = P(B|A) P(A)$].

Estas igualdades são chamadas de _Teorema da multiplicação_ ou _Teorema do produto_.

Existe uma generalização para mais de dois eventos e ela é a seguinte: Dados eventos latexmath:[$A_1,A_2,\ldots,A_n$], temos que

latexmath:[$P(A_1\cap A_2\cap\cdots\cap A_n) = P(A_1)P(A_2|A_1)P(A_3|A_1\cap A_2)\cdots P(A_n|A_1\cap \cdots\cap A_{n-1}).$]

Exercício::

Uma caixa contém 4 lâmpadas boas e 2 queimadas. Retira-se ao acaso 3 lâmpadas sem reposição. Calcule a probabilidade dessas 3 lâmpadas serem boas.

_Solução_:

Sejam os eventos latexmath:[$A_i = $] {A _i_-ésima lâmpada é boa}, para _i_=1,2,3. Queremos calcular a probabilidade do evento latexmath:[$A_1\cap A_2\cap A_3$]. Sabemos, pelo teorema da multiplicação, que

latexmath:[$P(A_1\cap A_2\cap A_3) = P(A_1)P(A_2|A_1)P(A_3|A_1\cap A_2)$]. Vamos então calcular cada uma dessas probabilidades separadamente.

Inicialmente, temos 4 resultados favoráveis ao evento latexmath:[$A_1$], entre 6 resultados possíveis, logo latexmath:[$P(A_1) = \frac{4}{6} = \frac{2}{3}.$]

Agora, vamos considerar o espaço amostral reduzido para calcular latexmath:[$P(A_2|A_1)$]. Dado que latexmath:[$A_1$] ocorreu, e como estamos *sem reposição*, para a retirada da segunda lâmpada teremos 3 lâmpadas boas, e um total de 5 lâmpadas. Logo,

latexmath:[$P(A_2|A_1) = \frac{3}{5}.$]

Analogamente, para calcular latexmath:[$P(A_3|A_1\cap A_2)$], observe que se $A_1$ e $A_2$ ocorreram, então para a retirada da terceira lâmpada, teremos 2 lâmpadas boas e um total de 4 lâmpadas. Desta forma,

latexmath:[$P(A_3|A_1\cap A_2) = \frac{2}{4} = \frac{1}{2}.$]

Finalmente, juntando estas probabilidades obtemos que

latexmath:[$P(A_1\cap A_2\cap A_3) = \frac{2}{3} \frac{3}{5} \frac{1}{2} = \frac{1}{5}.$]

'''

==== Teorema da Probabilidade Total

Seja latexmath:[$\Omega$] o espaço amostral de um experimento latexmath:[$E$], e seja latexmath:[$B_1,B_2,\ldots,B_k$] uma partição de latexmath:[$\Omega$]. Assim, dado um evento latexmath:[$A$] qualquer, temos que 

latexmath:[$A = (A\cap B_1)\cup (A\cap B_2) \cup \cdots \cup (A\cap B_k).$]

Observe que como os eventos latexmath:[$A\cap B_1, A\cap B_2,\ldots, A\cap B_k$] são dois-a-dois mutuamente excludentes, podemos aplicar a aditividade contável da probabilidade, que é válida para eventos mutuamente excludentes, e escrever

latexmath:[$P(A) = P(A\cap B_1) + \cdots + P(A\cap B_k).$]

Essa forma acima é chamada a primeira forma do *Teorema da probabilidade total*. Vamos agora para a segunda forma. Escrevendo cada termo latexmath:[$P(A\cap B_i) = P(A|B_i)P(B_i)$] e, daí, obtemos a *segunda forma* do teorema da probabilidade total:

latexmath:[$P(A) = P(A|B_1)P(B_1) + \cdots + P(A|B_k)P(B_k).$]

Agora já temos teoria suficiente para resolver o problema dos monitores apresentado no início da seção:

Exercício::

Consideremos o exemplo do lote com 20 monitores defeituosos e 80 monitores em perfeito estado, no qual extraímos duas peças sem reposição, e queremos calcular a probabilidade do evento latexmath:[$B = $] {O segundo monitor é defeituoso}.

_Solução_:

Relembre a definição do evento latexmath:[$A$]: latexmath:[$A = $]{O primeiro monitor é defeituoso}.

Pelo teorema da probabilidade total, segue que

latexmath:[$P(B) = P(B|A)P(A) + P(B|A^c) P(A^c).$]

Já sabemos que latexmath:[$P(A) = \frac{1}{5}$]. Isto fornece também, pela propriedade do complementar latexmath:[$P(A^c) = 1-P(A) = \frac{4}{5}$].

Vamos calcular agora latexmath:[$P(B|A)$] e latexmath:[$P(B|A^c)$] separadamente. 

Dado que o evento latexmath:[$A$] ocorreu, e sabendo que estamos *sem reposição*, para o segundo monitor, teremos 99 monitores disponíveis e entre eles, apenas 19 são defeituosos. Assim, latexmath:[$P(B|A) = \frac{19}{99}.$]

Analogamente, temos que se latexmath:[$A^c$] ocorreu, então o primeiro monitor escolhido estava em perfeito estado. Assim, neste cenário, para a escolha do segundo monitor, teremos 20 monitores defeituosos disponíveis entre o total de 99 monitores. Assim latexmath:[$P(B|A^c) = \frac{20}{99}.$]

Juntando todas as informações, temos que

latexmath:[$P(B) = \frac{19}{99} \frac{1}{5} + \frac{20}{99}\frac{4}{5} = \frac{80 + 19}{99\cdot 5} = \frac{1}{5}.$]

Então, curiosamente, apesar das contas serem completamente diferentes, e de estarmos sem reposição, neste caso, as probabilidades também são iguais. Note que isso é uma coincidência e não ocorre em geral.

'''
==== Teorema de Bayes

Assim como no teorema da probabilidade total, seja latexmath:[$\Omega$] um espaço amostral associado a um experimento latexmath:[$E$], e seja latexmath:[$B_1,B_2,\ldots,B_k$] uma partição de latexmath:[$\Omega$]. 

Temos então, pela definição da probabilidade condicional que

latexmath:[$P(B_i|A) = \frac{P(A\cap B_i)}{P(A)}, i=1,2,\ldots, k$].

Usando o teorema da multiplicação, temos que latexmath:[$P(A\cap B_i) = P(A|B_i)P(B_i)$]. Além disso, pelo teorema da probabilidade total, temos que latexmath:[$P(A) = \sum_{j=1}^k P(A|B_j)P(B_j)$]. 

Portanto, juntando essas fórmulas com a definição da probabilidade condicional, obtemos:

latexmath:[$P(B_i|A) = \frac{P(A|B_i)P(B_i)}{\sum_{j=1} P(A|B_j)P(B_j)}, i =1,\ldots, k.$]

Esta fórmula é conhecida como *Teorema de Bayes*.

Exercício:: Numa turma de ciências da computação da UFPB, 1% dos homens e 4% das mulheres possuem menos de 1,60m de altura. Além disso, 60% dos estudantes são homens. Se um estudante é selecionado ao acaso e é verificado que tem menos de 1,60m de altura. Qual é a probabilidade desse estudante ser homem?

_Solução_:

Defina os eventos

latexmath:[$A = $] {Estudantes com menos de 1,60m}, latexmath:[$M = $] {Estudantes do sexo feminino} e latexmath:[$H = $] {Estudantes do sexo masculino}.

Pelo enunciado, sabemos que latexmath:[$P(A|H) = 0,01$], latexmath:[$P(A|M) = 0,04$], latexmath:[$P(H) = 0,6$] e latexmath:[$P(M) = 1- P(H) = 0,4$].

Além disso, pelo teorema de Bayes, segue que

latexmath:[$P(H|A) = \frac{P(A|H)P(H)}{P(A|H)P(H) + P(A|M)P(M)} = \frac{0,01\cdot 0,6}{0,01\cdot 0,6 + 0,04\cdot 0,4} = \frac{3}{11}.$]

'''

=== Eventos Independentes

Considere dois eventos latexmath:[$A$] e latexmath:[$B$] quaisquer de um mesmo espaço amostral latexmath:[$\Omega$]. Dois eventos latexmath:[$A$] e latexmath:[$B$] são independentes quando a probabilidade de ocorrer um dos eventos não é modificada pela ocorrência do outro. Ou seja, dizemos que latexmath:[$A$] e latexmath:[$B$] são independentes quando latexmath:[$P(A|B) = P(A)$] ou latexmath:[$P(B|A) = P(B)$].

Assim, se latexmath:[$A$] e latexmath:[$B$] são *eventos independentes*, então

latexmath:[$P(A\cap B) = P(A)P(B)$].

Observe que se vale a identidade acima, então os eventos são independentes.

Exercício::

Suponha que um dado equilibrado seja jogado duas vezes. Sejam os eventos:
latexmath:[$A = $] {o primeiro dado mostra um número par} e latexmath:[$B = $] {o segundo dado mostra o número 5 ou 6}.
Calcule latexmath:[$P(A), P(B), P(A\cap B), P(A|B)$] e latexmath:[$P(B|A)$].

_Solução_:

Escrevendo explicitamente, temos que

latexmath:[$\Omega = \{(1,1),(1,2),(1,3),\ldots, (6,6)\}$], onde latexmath:[$\Omega$] possui 36 elementos.

latexmath:[$A = \{ (2,1), (2,2), (2,3), (2,4), (2,5), (2,6), (4,1), (4,2), (4,3), (4,4), (4,5), (4,6), (6,1), (6,2), (6,3), (6,4), (6,5), (6,6)\}$], onde latexmath:[$A$] possui 18 elementos.

latexmath:[$B = \{ (1,5), (2,5), (3,5), (4,5), (5,5), (6,5), (1,6), (2,6), (3,6), (4,6), (5,6), (6,6)\}$], onde latexmath:[$B$] possui 12 elementos.

latexmath:[$A\cap B = \{ (2,5), (2,6), (4,5), (4,6), (6,5), (6,6)\}$], onde latexmath:[$A\cap B$] possui 6 elementos.

Portanto, temos que

latexmath:[$P(A) = \frac{18}{36} = \frac{1}{2}, P(B) = \frac{12}{36} = \frac{1}{3}$] e latexmath:[$P(A\cap B) = \frac{6}{36} = \frac{1}{6}.$]

Observemos que latexmath:[$P(A\cap B) = \frac{1}{6} = \frac{1}{2} \frac{1}{3} = P(A) P(B).$] Logo, pelo que vimos acima, os eventos são independentes e desta forma, latexmath:[$P(A|B) = P(A) = \frac{1}{2}$], e latexmath:[$P(B|A) = P(B) = \frac{1}{3}$].

Podemos verificar diretamente:

latexmath:[$P(A|B) = \frac{P(A\cap B)}{P(B)} = \frac{1/6}{1/3} = \frac{1}{2}$] e latexmath:[$P(B|A) = \frac{P(A\cap B)}{P(A)} = \frac{1/6}{1/2} = \frac{1}{3}.$]

'''

Podemos generalizar este resultado para latexmath:[$n$] eventos. Isto fornece a seguinte definição:

Definição:: Sejam latexmath:[$A_1,A_2,\ldots,A_n$] eventos em um mesmo espaço amostral latexmath:[$\Omega$]. Dizemos que latexmath:[$A_1,\ldots,A_n$] são *eventos independentes* se, e somente se, para latexmath:[$k = 2, 3,\ldots, n$], e todas as escolhas possíveis de índices latexmath:[$i_1,\ldots,i_k$], onde cada latexmath:[$i_j$] é um número entre 1 e latexmath:[$n$], e eles são diferentes, vale a igualdade

latexmath:[$P(A_{i_1}\cap A_{i_2}\cap\cdots\cap A_{i_k}) = P(A_{i_1})\cdots P(A_{i_k}).$]

Neste caso, temos latexmath:[$2^n -n -1$] relações a serem verificadas. 

Exercício::

Suponha que um par de moedas honestas sejam lançadas. Considere os eventos:
latexmath:[$A = $] {cara na primeira moeda}, latexmath:[$B = $] {cara na segunda moeda} e latexmath:[$C = $] {cara em exatamente uma moeda}.
Mostre que os eventos latexmath:[$A,B$] e latexmath:[$C$] são dois-a-dois independentes, mas não são independentes.

_Solução_:

Observe que latexmath:[$\Omega = $] {(cara,cara),(cara,coroa),(coroa,cara),(coroa,coroa)}. Note que latexmath:[$\Omega$] possui 4 elementos.

Temos que latexmath:[$A = $] {(cara,cara),(cara,coroa)}, latexmath:[$B = $] {(cara,cara), (coroa,cara)}, latexmath:[$C = $] {(cara,coroa),(coroa,cara)}.
Além disso, segue que latexmath:[$A\cap B$] = {(cara,cara)}, latexmath:[$A\cap C$] = {(cara,coroa)}, latexmath:[$B\cap C$] = {(coroa,cara)}.

Portanto, temos que latexmath:[$P(A) = \frac{2}{4} = \frac{1}{2}, P(B) = \frac{2}{4} = \frac{1}{2}, P(C) = \frac{2}{4} = \frac{1}{2}$. Por outro lado, temos que latexmath:[$P(A\cap B) = \frac{1}{4} = \frac{1}{2}\frac{1}{2} = P(A)P(B)$], latexmath:[$P(A\cap C) = \frac{1}{4} = \frac{1}{2}\frac{1}{2} = P(A)P(C)$] e latexmath:[$P(B\cap C) = \frac{1}{4} = \frac{1}{2}\frac{1}{2} = P(B)P(C)$].

Isso mostra que os eventos latexmath:[$A, B$] e latexmath:[$C$] são dois-a-dois independentes. Entretanto, temos que latexmath:[$A\cap B\cap C = \emptyset$], e desta forma,

latexmath:[$P(A\cap B\cap C) = 0 \neq \frac{1}{8} = P(A)P(B)P(C)$].

Logo, os eventos latexmath:[$A,B$] e latexmath:[$C$] não são independentes.

'''



////
Sempre termine os arquivos com uma linha em branco.
////


