=== Atividades

*1.* Seja x:[X] uma variável aleatória discreta com função de probabilidade dada por
[latexmath]
++++
\[
p(x) = cx,\quad x=1,\ldots,6.
\]
++++
Encontre:


--


a) o valor de x:[c];







b) a probabilidade de x:[X] ser um número ímpar.





--


*2.* Seja x:[X] uma variável aleatória discreta com função de probabilidade dada por
[latexmath]
++++
\[
p(x)=\frac{c}{4^x},\quad x=0,1,\ldots.
\]
++++
Obtenha:


--


a) o valor de x:[x].








b) a probabilidade de x:[X] ser um número par.






--

*3.* Seja x:[X] uma variável aleatória discreta com função de distribuição dada por
[latexmath]
++++
\[
F(x) = \begin{cases}
0,&\hbox{~se~} x<0,\\
1/2,&\hbox{~se~}0\leq x <1,\\
3/5, &\hbox{~se~} 1\leq x <2,\\
4/5,&\hbox{~se~} 2\leq x < 3,\\
9/10,&\hbox{~se~} 3\leq x <4,\\
1,&\hbox{~se~} x\geq 4.
\end{cases}
\]
++++
Calcule:


--


a) a função de probabilidade de x:[X].






b) x:[P(X=0|X\hbox{~é par})].






--


*4.* Uma urna contém cinco bolas numeradas de 1 a 5. Duas bolas são retiradas simultaneamente. Obtenha a função
de probabilidade das seguintes variáveis aleatórias:


--


a) o maior número sorteado;









b) a soma dos números retirados.





--


*5.* Verifique que as seguintes funções são densidades:



--



a) 
[latexmath]
++++
\[
f(x) = \begin{cases}
1/8,&\hbox{~se~}0\leq x\leq 2,\\
3/4,&\hbox{~se~}4\leq x\leq 5,\\
0,&\hbox{caso contrário}.
\end{cases}
\]
++++




b) x:[f(x) = 3(1-x)^2, 0\leq x\leq 1.]




c) x:[f(x) = 4xe^{-2x},\quad x\geq 0.]

--

*6.* Seja x:[X] uma variável aleatória contínua com densidade dada por
[latexmath]
++++
\[
f(x) = \frac{c}{x^3},\quad x\geq 1.
\]
++++
Calcule:
--



a) o valor de x:[c];










b) a probabilidade de x:[X] ser maior do que x:[2];









c) a função de distribuição de x:[X].









--



*7.* Encontre a densidade de x:[Y=e^{-2X}], onde x:[X] é uma variável aleatória contínua com densidade dada por
x:[f(x) = e^{-x},\quad x>0].



*8.* Encontre a densidade de x:[|X|], se x:[X] é uma variável aleatória contínua com densidade dada por
[latexmath]
++++
\[
f(x) = \frac{1}{\sqrt{2\pi}} e^{-x^2/2},\quad x\in\mathbb{R}.
\]
++++





*9.* Seja x:[X] uma variável aleatória com densidade dada por
[latexmath]
++++
\[
f(x) = \begin{cases}
1/2,&\hbox{~se~}-1<x<0,\\
e^{-x}/2,&\hbox{~se~}x\geq 0,\\
0,&\hbox{caso contrário}.
\end{cases}
\]
++++
Obtenha a densidade de x:[Y=X^2].









