[[Cap_Var_Ale]]
== Variáveis Aleatórias e Suas Distribuições

:cap: cap4

.Objetivos do capítulo
____
Ao final deste capítulo você deverá ser capaz de:

* Saber a definição de variável aleatória
* Saber identificar variáveis aleatórias discretas
* Entender o que é e como calcular a função de probabilidade de uma variável aleatória discreta
* Saber identificar variáveis aleatórias contínuas
* Entender o que é e como calcular a função de densidade de uma variável aleatória contínua
* Saber a definição e como calcular a função de distribuição acumulada
* Saber a relação entre a função de distribuição acumulada e função de probabilidade (no caso de variáveis aleatórias discretas)
* Saber a relação entre a função de distribuição acumulada e função de densidade (no caso de variáveis aleatórias contínuas)
* Saber a definição e exemplos de variáveis aleatórias mistas
* Entender o que são e como trabalhar com funções de variáveis aleatórias
____


Imaginemos que existe a definição de que a temperatura de João Pessoa é 
considerada quente se é maior do que 27 graus Celsius, é considerada 
confortável se está entre 20 e 27 graus Celsius, e é considerada fria se é 
menor do que 20 graus Celsius. Suponha que nosso espaço amostral para o 
experimento medir a temperatura de João Pessoa pela manhã. Suponha que nosso
espaço amostral, que contém todos os resultados possíveis para a temperatura, 
é latexmath:[$\Omega=R$]. Se queremos determinar se a temperatura é fria, 
confortável ou quente, a melhor ferramenta para isso é definir uma função 
latexmath:[$X:\Omega\to$] {fria,confortável,quente}. Ou seja, uma função que
associa a cada valor de temperatura, a quantidade _fria_, _confortável_ ou _quente_. 
Por exemplo, latexmath:[$X(10)=$] frio; latexmath:[$X(34)=$] quente, e latexmath:[$X(22)=$] 
confortável. Neste exemplo, foram medidas temperaturas, 10, 34 e 22, respectivamente.

(((Variável Aleatória)))

Essa função latexmath:[$X$] que utilizamos é o que chamamos 
de uma variável aleatória. Ou seja, é um rótulo que damos 
para os valores possíveis no espaço amostral.

Na prática, o mais comum é utilizar variáveis aleatórias, onde associamos cada valor 
do espaço amostral a um número real, ao invés de um conjunto arbitŕario. 
Isso se deve ao fato, de que existem muitas distribuições de probabilidade 
conhecidas tomando como valores números reais. Portanto, ao considerar uma variável
aleatória que toma valores reais, estamos pegando um problema de probabilidade genérico, 
e transformando num problema de probabilidade de números reais,
e assim podemos utilizar toda a teoria de distribuições discretas 
e contínuas para resolver o problema.

Desta forma, mais precisamente, temos a

Definição: Variável Aleatória::
+
--
Seja latexmath:[$\Omega$] um espaço amostral e seja latexmath:[$X:\Omega\to R$]
uma função latexmath:[$X$] que associa a cada elemento latexmath:[$\omega\in\Omega$]
um número real latexmath:[$X(\omega)\in\mathbb{R}$].
--

.Exemplo de variável aleatória
====
Suponha que sorteamos 3 pessoas em João Pessoa e observamos se é homem ou mulher.
Suponha que queremos saber o número de mulheres sorteadas.
Para isso, defina a variável aleatória latexmath:[$X:\Omega\to R$], 
onde latexmath:[$X$] pode assumir os valores, 0,1,2 e 3. Se denotamos homem por 
H e mulher por M, temos que 
latexmath:[$\Omega= \{MMM,MMH,MHM,HMM,MHH,HMH,HHM,HHH\}$], e portanto 
latexmath:[$X(MMM)=3,X(MMH)=X(MHM)=X(HMM)=2,X(MHH)=X(HMH)=X(HHM)=1,X(HHH)=0.$]    
====

(((Variável Aleatória, Imagem inversa)))

Definição: Imagem Inversa:: 
+
--
Seja latexmath:[$\Omega$] um espaço amostral e seja latexmath:[$X:\Omega\to R$] uma variável aleatória.
Dado qualquer subconjunto latexmath:[$B\subset R$], definimos a imagem inversa de latexmath:[$B$]
pela variável aleatória latexmath:[$X$] como o conjunto latexmath:[$X^{-1}(B) = \{\omega\in\Omega; X(\omega)\in B\}$].
Ou seja, latexmath:[$X^{-1}(B)$] consiste dos elementos de latexmath:[$\Omega$] que são levados no 
conjunto latexmath:[$B$] pela variável aleatória latexmath:[$X$].
--

A partir da imagem inversa de latexmath:[$X^{-1}(B)$] podemos construir uma nova medida de probabilidade
induzida pela variável aleatória latexmath:[$X$].

(((Probabilidade, Induzida por uma variável aleatória)))

Definição: Probabilidade induzida pela variável aleatória latexmath:[$X$]::
+
--
Definimos a probabilidade latexmath:[$P(X\in B)$] como sendo 
latexmath:[$P(X^{-1}(B))$], ou seja, como a probabilidade do evento latexmath:[$X^{-1}(B)$]. 
Da mesma forma, definimos latexmath:[$P(X=a)$] como sendo latexmath:[$P(X^{-1}(\{a\}))$], ou seja, 
a probabilidade da variável aleatória assumir o valor latexmath:[$a$]. 
--

Exercício::
+
--
Escreva o que significa latexmath:[$P(X\leq b)$] para algum número real latexmath:[$b$].
--

_Solução_::
+
--
Seguindo a mesma ideia da definição, temos que latexmath:[$P(X\leq b)$] deve ser 
definido como a probabilidade de latexmath:[$X$] ser menor ou igual a latexmath:[$b$], 
assim, é a probabilidade de latexmath:[$X$] pertencer ao intervalo da reta latexmath:[$(-\infty,b\]$]. 
Portanto, latexmath:[$P(X\leq b) = P(X^{-1}((-\infty,b\]))$].
--

Exercício::
+
--
Suponha que na cidade de João Pessoa, temos a mesma quantidade de homens e de mulheres, 
e que cada sorteio de pessoas é feito com reposição e independentemente do(s) sorteio(s) anterior(es). 
Seja latexmath:[$X$] a variável aleatória que indica o número de mulheres sorteadas.
Calcule: latexmath:[$P(X=0), P(X=1), P(X=2)$] e latexmath:[$P(X\leq 2)$]. 
--

_Solução_::
+
--
Temos que latexmath:[$P(X=0) = P(HHH) = \frac{1}{8}$]; 
latexmath:[$P(X=1) = P(\{HHM,HMH,MHH\}) = P(HHM)+P(HMH)+P(MHH) = \frac{3}{8}$]; 
latexmath:[$P(X=2) = P(HMM,MHM,MMH) = P(HMM)+P(MHM)+P(MMH) = \frac{3}{8}$]. 
Finalmente, 
[latexmath]
++++
\[P(X\leq 2) = P(X=0) + P(X=1) + P(X=2) = \frac{1}{8} + \frac{3}{8}+\frac{3}{8} = \frac{7}{8}.\]
++++

Poderíamos também ter resolvido utilizando a técnica de tomar complementares. Como latexmath:[$X$] só pode
assumir valores latexmath:[$0,1,2$] e 3, temos que, 
[latexmath]
++++
\[P(X\leq 2) = 1-P(X>2) = 1 - P(X=3) = 1 - P(MMM) = 1-\frac{1}{8} = \frac{7}{8}.\]
++++

--

=== Variáveis Aleatórias Discretas

(((Variável Aleatória, Discretas)))

Como falamos anteriormente, nosso objetivo em considerar variáveis aleatórias 
tomando como valores números reais, se deve ao fato de haver uma teoria bem 
completa em torno dessas variáveis aleatórias. Dentre as variáveis aleatórias
reais, existem dois grandes grupos: as variáveis aleatórias _discretas_ e as 
variáveis aleatórias _contínuas_. Nosso objetivo nesta seção consiste em definir,
e apresentar vários exemplos de variáveis aleatórias discretas.

Definição: Variável aleatória discreta:: 
+
--
Seja latexmath:[$\Omega$] um espaço amostral e seja latexmath:[$X:\Omega\to R$] uma variável 
aleatória. Se existe uma sequência números latexmath:[$a_1,a_2,a_3,\ldots$], tais que 
latexmath:[$X$] só pode assumir um dos valores dessa sequência. Então dizemos que 
latexmath:[$X$] é uma variável aleatória discreta.
--

[NOTE]
====
Note que apesar da sequência latexmath:[$a_1,a_2,a_3,\ldots$] ser uma sequência infinita,
o conjunto de valores possíveis para a variável aleatória latexmath:[$X$] pode ser _finito_ ou _infinito enumerável_. 
Por infinito enumerável, nós queremos dizer um conjunto infinito que pode ser indexado pelo conjunto
dos números naturais, ou seja, pelo qual podemos escrever uma sequência numérica cobrindo todos os números.
====

No caso de variáveis aleatórias discretas, sabemos que vale a seguinte 
identidade: 
[latexmath]
++++
\[P(X\in \{a_1,a_2,a_3,\ldots\}) = 1,\]
++++
pois latexmath:[$X$] necessariamente só assume valores nesse conjunto latexmath:[$\{a_1,a_2,a_3,\ldots\}$]. 
Portanto, utilizando a aditividade contável da medida de probabilidade, obtemos 
[latexmath]
++++
\[1 = P(X\in \{a_1,a_2,a_3,\ldots\}) = \sum_{i=1}^\infty P(X=a_i),\]
++++
e portanto temos que latexmath:[$\sum_{i=1}^\infty P(X=a_i) = 1$], e além disso, 
sabemos que para cada latexmath:[$i$], vale latexmath:[$P(X=a_i)\geq 0$]. 

Estes fatos motivam a seguinte definição:

(((Probabilidade, Função de)))

Definição: Função de probabilidade::
+
--
Seja latexmath:[$\Omega$] um espaço amostral e seja latexmath:[$X:\Omega\to R$] uma variável 
aleatória discreta, e seja latexmath:[$a_1,a_2,a_3,\ldots,$] o conjunto de valores possíveis 
de latexmath:[$X$]. Definimos a _função de probabilidade_ da variável aleatória latexmath:[$X$] 
como uma função latexmath:[$p(a_i)$], que associa a cada latexmath:[$a_i$] a probabilidade da 
variável aleatória latexmath:[$X$] assumir o valor latexmath:[$a_i$], isto é, definimos 
latexmath:[$p(a_i) = P(X=a_i)$]. 
--

[NOTE]
====
Pelo que já vimos, uma função de probabilidade satisfaz as seguintes propriedades: 
. para todo latexmath:[$i$], latexmath:[$p(x_i)\geq 0$];
. latexmath:[$\sum_{i=1}^\infty p(x_i) = 1.$]
====

Exercício::
+
--
Suponha que uma urna contém 6 bolas azuis e 4 bolas vermelhas. Quatro bolas são tiradas
aleatoriamente da urna, com reposição, e é observada a cor da bola, antes da bola ser 
devolvida à urna. Seja latexmath:[$X$] a variável aleatória que indica o número de bolas 
vermelhas que foram retiradas da urna. Obtenha a função de probabilidade de latexmath:[$X$].
--

_Solução_::
+
--
Denote por _V_ a bola vermelha e por _A_, a bola azul. Pelas informações do problema, 
temos que a probabilidade de se retirar uma bola vermelha é latexmath:[$\frac{4}{10}$] e a 
de se retirar uma bola azul é latexmath:[$\frac{6}{10}$]. 

Assim, latexmath:[$P(V) = \frac{4}{10}=0,4$] e latexmath:[$P(A) = \frac{6}{10}=0,6$]. 

O espaço amostral do problema é dado por
[latexmath]
++++
\[
\begin{array}{lll}
\Omega &=& \{VVVV,VVVA,VVAV,VAVV,AVVV,VVAA,VAVA,\\
&&VAAV,AVAV,AAVV,AVVA,VAAA,AVAA,AAVA,AAAV,AAAA\}.
\end{array}
\]
++++

É fácil ver que o conjunto de valores possíveis para a variável aleatória latexmath:[$X$] é latexmath:[$\{0,1,2,3,4\}$]. 

Assim:

[latexmath]
++++
\[p(0) = P(X=0) = P(AAAA) = (0,6)^4;\]
++++

[latexmath]
++++
\[
\begin{array}{lll}
p(1) &=&P (X=1)= P(AAAV,AAVA,AVAA,VAAA)\\
&=& P(AAAV)+P(AAVA)+P(AVAA)+P(VAAA)\\
&=&(0,6)^30,4+(0,6)^30,4+(0,6)^30,4+(0,6)^30,4 = 4(0,6)^30,4;
\end{array}
\]
++++

[latexmath]
++++
\[
\begin{array}{lll}
p(2) &=& P(X=2) = P(VVAA,VAVA,VAAV,AVAV,AAVV,AVVA)\\
&=& P(VVAA)+P(VAVA)+P(VAAV)+P(AVAV)+P(AAVV)+P(AVVA)\\
&=& (0,6)^2(0,4)^2+(0,6)^2(0,4)^2+(0,6)^2(0,4)^2\\
&+&(0,6)^2(0,4)^2+(0,6)^2(0,4)^2+(0,6)^2(0,4)^2\\
&=& 6(0,6)^2(0,4)^2;
\end{array}
\]
++++

[latexmath]
++++
\[
\begin{array}{lll}
p(3)&=&P(X=3) =P(VVVA,VVAV,VAVV,AVVV)\\
&=& P(VVVA)+P(VVAV)+P(VAVV)+P(AVVV)\\
&=& (0,4)^30,6+(0,4)^30,6+(0,4)^30,6+(0,4)^30,6\\
&=& 4(0,4)^30,6;
\end{array}
\]
++++

finalmente, latexmath:[$p(4)=P(X=4)=P(VVVV) = (0,4)^4$].

--

=== Variáveis Aleatórias Contínuas

(((Variável Aleatória, Contínua)))

As variáveis contínuas são aquelas na qual a variável aleatória pode assumir uma 
quantidade não-enumerável de valores. Isto faz com que a probabilidade de assumir
um valor específico seja 0. Ou seja, se latexmath:[$X$] é uma variável aleatória contínua, 
para todo número real latexmath:[$a$], temos que latexmath:[$P(X=a)=0$]. A intuição 
para este fato inusitado, é que temos tantos valores possíveis para latexmath:[$X$],
que faz com que a probabilidade de assumir um valor em particular seja 0. Neste caso, 
a probabilidade de latexmath:[$X$] assumir um valor é trocada pela probabilidade de 
latexmath:[$X$] pertencer a um intervalo da reta. Além disso, no cálculo da probabilidade,
a soma é ``trocada'' por uma integral, conforme veremos na próxima definição.

(((Função, densidade)))

Definição: Variável Aleatória Contínua::
+
--
Dizemos que latexmath:[$X$] é uma variável aleatória contínua se existe uma função real 
latexmath:[$f:\mathbb{R}\to \mathbb{R}$], a qual chamamos de _função de densidade_ de latexmath:[$X$],
que satisfaz as seguintes condições:

* Para todo latexmath:[$x$] real, latexmath:[$f(x)\geq 0$];
* latexmath:[$\displaystyle\int_{-\infty}^\infty f(x)dx = 1$];
* Se latexmath:[$f(x)$] satisfaz as duas primeiras condições, então temos que para 
quaisquer latexmath:[$a$] e latexmath:[$b$], latexmath:[$-\infty < a<b<\infty$], 
vale latexmath:[$P(a\leq X\leq b) = \displaystyle\int_a^b f(x)dx$].
--

[NOTE]
====
Note portanto, que pela definição, para checar se uma função latexmath:[$f(x)$] 
é uma função de densidade é suficiente verificar duas coisas:

. se para todo latexmath:[$x$] real, temos latexmath:[$f(x)\geq 0$];
. se latexmath:[$\displaystyle\int_{-\infty}^\infty f(x)dx = 1.$] 
====

[IMPORTANT]
====
Como mencionamos anteriormente, a definição de variável aleatória contínua implica
que para todo latexmath:[$a$] real, latexmath:[$P(X=a)=0$]. De fato, como
latexmath:[$X$] possui uma função de densidade latexmath:[$f$], temos que 
[latexmath]
++++
\[P(X=a)=\int_a^a f(x)dx = 0.\]
++++

====

Uma consequência deste fato é que latexmath:[$P(a\leq X\leq b) = P(a < x<b) = P(a<x\leq b) = P(a\leq X <b)$]. 

Exercício::
+
--
Suponha que latexmath:[$X$] seja uma variável aleatória contínua com a função de densidade 
[latexmath]
++++
\[f(x) = \begin{cases} 
2x,& 0<x<1;\\
0,&\textrm{caso contrário}.
\end{cases}.\]
++++

.. Mostre que latexmath:[$f(x)$] é uma função de densidade;

.. Calcule latexmath:[$P(X\leq 1/2)$];

.. Calcule latexmath:[$P(X\leq 1/2 | 1/3\leq X\leq 2/3)$] (probabilidade condicional). 

--

_Solução_::
+
--
*a.* Temos da definição de latexmath:[$f(x)$] que para todo latexmath:[$x$] real, latexmath:[$f(x)\geq 0$]. 
Basta verificar agora que latexmath:[$\int_{-\infty}^\infty f(x)dx=1$]. Note que latexmath:[$f(x)=0$] fora do intervalo latexmath:[$[0,1\]$],
e portanto 
[latexmath]
++++
\[\int_{-\infty}^\infty f(x)dx = \int_0^1 2xdx = \left. x^2\right|_0^1 = 1.\]
++++

Assim, latexmath:[$f(x)$] é função de densidade

*b.* 
[latexmath]
++++
\[P(X\leq 1/2) = \int_0^{1/2} 2xdx = x^2\Big|_0^{1/2} = \frac{1}{4}.\]
++++

*c.* 
[latexmath]
++++
\[
\begin{array}{lll}
P(X\leq 1/2|1/3\leq X\leq 2/3) &=& \frac{P(1/3\leq X\leq 1/2)}{P(1/3\leq X\leq 1/2)}\\
&=& \frac{\int_{1/3}^{1/2} 2xdx}{\int_{1/3}^{2/3} 2xdx}\\
&=& \frac{ x^2\Big|_{1/3}^{1/2}}{x^2\Big|_{1/3}^{2/3}} = \frac{5/36}{3/9}\\
&=& \frac{5}{12}.
\end{array}
\]
++++

--

=== Função de Distribuição Acumulada

(((Função, Distribuição acumulada)))
(((Função, Distribuição)))

Na teoria matemática da probabilidade é possível mostrar que, 
dada uma variável aleatória latexmath:[$X$], 
a probabilidade de qualquer evento pode ser obtida a partir das 
probabilidades latexmath:[$P(X\leq a)$], onde latexmath:[$a$] é número real.
Ou seja, conhecendo latexmath:[$P(X\leq a)$] para todo latexmath:[$a$] 
real, significa dizer que conhecemos latexmath:[$P(X\in A)$] 
para qualquer evento latexmath:[$A$]. Este resultado é um importante resultado 
de Teoria da Medida, e mostra o quão rica é a função latexmath:[$F(a) = P(X\leq a)$]. 
Por conta disso, ela recebe um nome:

Definição: Função de Distribuição Acumulada::
+
--
Seja latexmath:[$\Omega$] um espaço amostral, e seja latexmath:[$X:\Omega\to R$] uma variável aleatória
discreta ou contínua. Defina a função latexmath:[$F_X:R\to R$] dada por 
latexmath:[$F_X(a) = P(X\leq a)$], onde latexmath:[$a$] é número real. latexmath:[$F_X$] é
denominada a função de distribuição acumulada da variável aleatória latexmath:[$X$], ou simplesmente
função de distribuição.
--

* Se latexmath:[$X$] for uma variável aleatória discreta, então 
[latexmath]
++++
\[F_X(a) = \sum_{j;a_j\leq a} p(a_j),\]
++++
onde a soma é feita sobre os indíces latexmath:[$j$], tais que latexmath:[$a_j\leq a$].

* Se latexmath:[$X$] for uma variável aleatória contínua, então 
[latexmath]
++++
\[F_X(a) = \int_{-\infty}^a f(x)dx.\]
++++

Exercício::
+
--
Seja latexmath:[$X$] uma variável aleatória discreta tomando valores 0,1 e 2. 
Suponha que sua função de probabilidade é dada por
latexmath:[$p(0) = 1/2, p(1) = 1/3$] e latexmath:[$p(2) = 1/6$]. 
Obtenha latexmath:[$F_X$].
--

_Solução_::
+
--
Se latexmath:[$a<0$], então latexmath:[$F_X(a) = P(X<a) \leq P(X < 0) = 0$]. 
Como latexmath:[$F_X(a) = P(X\leq a) \geq 0$], segue que para todo latexmath:[$a<0$], latexmath:[$F_X(a) = 0$].

Suponha agora, latexmath:[$0\leq a<1$], então latexmath:[$F_X(a) = P(X\leq a) = P(X=0) = p(0) = 1/2$].

Seja agora, latexmath:[$1\leq a <2$]. Então, latexmath:[$F_X(a) = P(X\leq a) = P(X=0) + P(X=1) = p(0)+p(1) = 1/2+1/3 = 5/6.$]

Finalmente, se latexmath:[$a\geq 2$], então latexmath:[$F_X(a) = P(X\leq a) = P(X\leq 2) = 1.$]

Assim, 

[latexmath]
++++
\[
F_X(a) = \begin{cases}
0,& a<0\\
1/2,& 0\leq a<1,\\
5/6,& 1\leq a <2,\\
1,& a\geq 2.
\end{cases}.
\]
++++

--

Exercício::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade 
[latexmath]
++++
\[f(x) = \begin{cases}
2x,& 0<x<1;\\
0,&\textrm{caso contrário}.
\end{cases}.\]
++++

Já sabemos que latexmath:[$f$] é função de densidade por um exercício anterior. 
Obtenha sua função de distribuição latexmath:[$F_X$].
--

_Solução_::
+
--
Temos que se latexmath:[$a< 0$], então latexmath:[$P(X\leq a) \leq P(X < 0) = 0$]. 
Assim, para latexmath:[$a<0$], temos latexmath:[$F_X(a)=0$]. 

Para latexmath:[$0\leq a \leq 1$], temos 
[latexmath]
++++
\[P(X\leq a) = \int_0^a 2xdx = \left. x^2\right|_0^a = a^2.\]
++++

Assim, para latexmath:[$0\leq a\leq 1$], vale latexmath:[$F_X(a) = a^2$]. 

Finalmente, se latexmath:[$a>1$], então latexmath:[$P(X\leq a) = P(X\leq 1) = 1.$] 

Portanto, para latexmath:[$a>1$], segue latexmath:[$F_X(a) = 1$].

Desta forma,

[latexmath]
++++
\[F_X(a) = \begin{cases}
0,& 0\leq a<0,\\
a^2,& 0\leq a \leq 1,\\
1,& a\geq 1.
\end{cases}.\]
++++

--

[NOTE]
====
Observe que se latexmath:[$a\leq b$], então sempre que latexmath:[$X(\omega) \leq a$], 
teremos latexmath:[$X(\omega)\leq a\leq b$], o que implica, latexmath:[$X(\omega)\leq b$]. 
Assim, vale a inclusão de conjuntos 
latexmath:[$\{\omega\in\Omega; X(\omega) \leq a\} \subset \{\omega\in\Omega; X(\omega)\leq b\}$]. 
Logo, latexmath:[$P(X\leq a) \leq P(X\leq b)$]. 

Portanto, temos que se latexmath:[$a\leq b$], então latexmath:[$F_X(a)\leq F_X(b)$], ou seja, 
latexmath:[$F_X$] é uma função não-decrescente.
====

[NOTE] 
====
É possível mostrar que para qualquer variável aleatória latexmath:[$X$], 
vale latexmath:[$\lim_{a\to -\infty} F_X(a) = 0$] e latexmath:[$\lim_{a\to\infty} F_X(a) = 1$]. 
====

[IMPORTANT]
====
Note ainda que se latexmath:[$X$] é uma variável aleatória discreta com conjunto de 
valores possíveis dado por latexmath:[$\{a_1,a_2,a_3,\ldots\}$], ordenados de tal forma 
que latexmath:[$a_1<a_2<a_3<a_4<\ldots$], então temos que

[latexmath]
++++
\[p(a_i) = P(X=a_i) = P(X\leq a_i) - P(X\leq a_{i-1}) = F_X(a_i) - F_X(a_{i-1}).\]
++++

Ou seja, podemos obter a função de probabilidade de latexmath:[$X$] a partir da 
função de distribuição de latexmath:[$X$] desta forma.
====

[NOTE] 
====
Note que esta última observação nos diz que se temos uma função de distribuição de
uma variável aleatória discreta, então o conjunto de valores que a variável aleatória
latexmath:[$X$] pode assumir é exatamente o conjunto dos pontos de descontinuidade
da função de distribuição latexmath:[$F_X$]. Assim, se latexmath:[$a_1$] é o menor 
ponto de descontinuidade de latexmath:[$X$], então latexmath:[$P(X=a_1) = F_X(a_1)$], 
e depois disso, se latexmath:[$F_X$] é descontínua no ponto latexmath:[$a_i$], então 
teremos que latexmath:[$P(X=a_i) = F_X(a_i)-F_X(a_{i-1})$].
====

Exercício::
+
--
Suponha que latexmath:[$X$] é uma variável aleatória discreta 
com função de distribuição latexmath:[$F_X$] dada por

[latexmath]
++++
\[F_X(a) = \begin{cases}
0,& a<0,\\
1/4,& 0\leq a < 1,\\
1/2,& 1\leq a < 2,\\
1,& a\geq 2.
\end{cases}
\]
++++


Obtenha a função de probabilidade latexmath:[$p(a_i)$]. 
--

_Solução_:: 
+
--
Os pontos de descontinuidade da função de distribuição latexmath:[$F_X$] são 0, 1 e 2.
Portanto, pelo que vimos, temos que latexmath:[$p(0) = F_X(0)=1/4$], 
latexmath:[$p(1) = F_X(1) - F_X(0) = 1/2-1/4 = 1/4$], e finalmente,
latexmath:[$p(2) = F_X(2) - F_X(1) = 1 - 1/2 = 1/2$].
--

Temos um resultado análogo para variáveis aleatórias contínuas.

[IMPORTANT]
====
Seja agora latexmath:[$X$] uma variável aleatória contínua. Então, vale que

[latexmath]
++++
\[F_X(x) = \int_{-\infty}^x f(t)dt.\]
++++

Ou seja, estamos dizendo que latexmath:[$F_X$] é uma primitiva para a 
função de densidade latexmath:[$f$]. Desta forma, podemos ``recuperar'' 
a função de densidade, a partir da função de distribuição, por simples derivação 
em todos os pontos em que latexmath:[$F_X$] for derivável:

[latexmath]
++++
\[f(a) = \frac{d F_X(a)}{da} = F_X'(a).\]
++++
====


Exercício::
+
--
Suponha que latexmath:[$X$] é uma variável aleatória contínua com função de distribuição latexmath:[$F_X$] dada por

[latexmath]
++++
\[F_X(a) = \begin{cases}
0,& a<0,\\
1-e^{-a},& a\geq 0.
\end{cases}.\]
++++

Obtenha a função de densidade latexmath:[$f(x)$].
--

_Solução_::
+
--
Sabemos que a função de densidade latexmath:[$f(x)$] é dada pela derivada da função de 
distribuição em todos os pontos em que esta for derivável.

Assim, se latexmath:[$x<0$], temos que latexmath:[$f(x) = F_X'(x) = 0$]. 
Se latexmath:[$x>0$], então latexmath:[$f(x) = F_X'(x) = e^{-x}$]. Em latexmath:[$x=0$], 
latexmath:[$F_X$] não é derivável, então podemos supor latexmath:[$f(x)=0$], já que o valor de uma 
função em um único ponto não altera o valor da integral.

Portanto, a função de densidade latexmath:[$f$] da variável aleatória latexmath:[$X$] é dada por

[latexmath]
++++
\[f(x) = \begin{cases}
0,& 0\leq x\leq 0,\\
e^{-x},& x > 0.
\end{cases}.\]
++++
--

=== Variáveis Aleatórias Mistas

(((Variável Aleatória, Mista)))

Podemos ter também um terceiro tipo de variável aleatória: a variável aleatória mista. 
Ela consiste em uma variável aleatória cuja probabilidade é uma mistura entre as variáveis
aleatórias contínuas e discretas. Assim, se latexmath:[$X$] é uma variável aleatória mista, 
então existem números reais latexmath:[$a_1,a_2,a_3,\ldots,$] tais que para algum _i_, 
latexmath:[$P(X=a_i)>0$], e tais que 
[latexmath]
++++
\[\sum_{i=1}^\infty P(X=a_i) = p <1,\]
++++
ou seja, isso garante que ela tem esse comportamento da variável aleatória discreta, 
mas não é uma variável aleatória discreta, pois a soma não é igual a 1.

(((Função, Distribuição, Parte discreta)))
(((Função, Probabilidade, Parte discreta)))

Assim, seja latexmath:[$F_X$] a função de distribuição da variável aleatória latexmath:[$X$]. 
Definimos a _parte discreta_ da função de distribuição de latexmath:[$X$] como
latexmath:[$F_X^d(x) = \sum_{i; a_i\leq x} P(X=a_i)$]. 
Defina latexmath:[$p(a_i) = P(X=a_i)$], então dizemos que a função latexmath:[$p$] 
é a função de probabilidade da parte discreta da variável aleatória latexmath:[$X$].

NOTE: Note que se latexmath:[$X$] fosse uma variável aleatória discreta, teríamos latexmath:[$F_X = F_X^d$].

(((Função, Distribuição, Parte contínua)))

Agora, defina latexmath:[$F_X^c(x) = F_X(x) - F_X^d(x)$], a parte contínua da função de distribuição da
variável aleatória latexmath:[$X$]. Assim, se latexmath:[$X$] é uma variável aleatória mista,
existe uma função latexmath:[$f(t)\geq 0$], tal que latexmath:[$F_X^c(x) = \displaystyle\int_{-\infty}^x f(t)dt$],
e latexmath:[$\displaystyle\int_{-\infty}^\infty f(t)dt = 1-p$]. Dizemos que a função 
latexmath:[$f$] é a função de densidade da parte contínua de latexmath:[$X$].

(((Função, Densidade, Parte contínua)))

[NOTE] 
====
Observe então que se latexmath:[$X$] é uma variável aleatória discreta, então 
latexmath:[$F_X^c(x) = 0,$] para todo latexmath:[$x$]; e se latexmath:[$X$] é uma variável 
aleatória contínua, então latexmath:[$F_X^d(x) = 0,$] donde temos latexmath:[$F_X(x) = F_X^c(x)$]. 
====

 
Portanto, podemos concluir que latexmath:[$F_X(x) = F_X^c(x) + F_X^d(x),$] ou seja, vale: 

[latexmath]
++++
\[F_X(x) = P(X\leq x) = \int_{-\infty}^x f(t)dt + \sum_{i; a_i\leq x} P(X=a_i).\]
++++

Assim, suponha que é dada uma função de distribuição latexmath:[$F_X$] de uma variável aleatória 
mista latexmath:[$X$], e que queremos encontrar a função de probabilidade da parte discreta de 
latexmath:[$X$], e a função de densidade da parte contínua de latexmath:[$X$]. 

Para tanto, começamos procurando por pontos de descontinuidade de latexmath:[$F_X$]. 
Suponha que temos os pontos latexmath:[$a_1,a_2,\ldots$], então, para encontrar a função de 
probabilidade da parte discreta de latexmath:[$X$], basta calcular para cada _i_, o número 
latexmath:[$p(a_i) = P(X=a_i) = P(X\leq a_i)-P(X<a_i)$]. 

Uma vez, encontrada a função de probabilidade da parte discreta de 
latexmath:[$X$], definimos latexmath:[$F_X^c(x) = F_X(x) - F_X^d(x)$], e obtemos a 
função de densidade da parte contínua de latexmath:[$X$] por derivação: latexmath:[$f(x) = {F_X^c}'(x)$], 
ou seja, derivamos a parte contínua da função de distribuição latexmath:[$F_X$].

Exercício::
+
--
Seja latexmath:[$X$] uma variável aleatória mista com função de distribuição

[latexmath]
++++
\[F_X(x) = \begin{cases}
0,& x\leq 0,\\
x,& 0<x<1/2,\\
1, x\geq 1/2.
\end{cases}\]
++++

Obtenha a função de probabilidade da parte discreta de latexmath:[$X$] e a função de densidade da parte contínua de latexmath:[$X$].
--

_Solução_::
+
--
Observe que latexmath:[$F_X$] só possui apenas um ponto de descontinuidade no 
ponto latexmath:[$x=1/2$]. Assim, temos que a função de probabilidade da parte 
discreta é dada por latexmath:[$p(1/2) = P(X\leq 1/2) - P(X<1/2) = F_X(1/2) - P(X<1/2) = 1 - 1/2=1/2$]. 
Pois, como para latexmath:[$x<1/2$], vale, latexmath:[$P(X<x) = x$], temos, latexmath:[$P(X<1/2) = 1/2$]. 

Portanto, temos que se latexmath:[$x<1/2$], então latexmath:[$F_X^d(x) = 0$], e se latexmath:[$x\geq 1/2$], 
então latexmath:[$F_X^d(x) = 1/2$]. Daí, se latexmath:[$x<1/2$], latexmath:[$F_X^c(x) = F_X(x) - F_X^d(x) = x$], e 
se latexmath:[$x\geq 1/2$], temos latexmath:[$F_X^c(x) = F_X(x) - F_X^d(x) = 1 - 1/2 = 1/2$]. Desta forma, temos que

[latexmath]
++++
\[F_X^c(x) =  \begin{cases}
0,& x\leq 0,\\
x,& 0<x<1/2,\\
1/2, x\geq 1/2.
\end{cases}.\]
++++

Assim, derivando, obtemos que a função de densidade da parte contínua de latexmath:[$X$] é dada por

[latexmath]
++++
\[f(x) =  \begin{cases}
0,& x\leq 0\textrm{ ou } x\geq 1/2,\\
1,& 0<x<1/2.
\end{cases}.\]
++++

--

=== Funções de Variáveis Aleatórias

(((Variável Aleatória, Função)))

Definição: Função de uma Variável Aleatória::
+
--
Seja latexmath:[$X$] uma variável aleatória tomando valores reais. 
Seja latexmath:[$Im(X) = X(\Omega) = \{X(\omega); \omega\in\Omega\}$] 
a imagem de latexmath:[$X$], ou seja, o conjunto dos valores que a variável 
aleatória latexmath:[$X$] pode assumir. Seja latexmath:[$g:Im(X)\to R$] uma 
função real. Então, a função latexmath:[$Y = g(X)$] é uma nova variável aleatória, 
e dizemos que latexmath:[$Y$] é uma função da variável aleatória latexmath:[$X$].
--

Relembre a definição de imagem inversa: para um subconjunto dos reais latexmath:[$A\subset R$] 
a imagem inversa de latexmath:[$A$] pela função latexmath:[$g$] é 
o conjunto latexmath:[$g^{-1}(A) = \{x\in Im(X); g(x) \in A\}$].

Assim, temos que para todo evento latexmath:[$A\subset R$], vale 
latexmath:[$P(Y \in A) = P(g(X) \in A) = P(X\in g^{-1}(A))$]. 
Portanto, podemos calcular probabilidades com relação à variável aleatória 
latexmath:[$Y$] a partir diretamente de probabilidades envolvendo apenas a variável aleatória latexmath:[$X$].

.Exemplo de função de variável aleatória discreta
====
Seja latexmath:[$X$] uma variável aleatória discreta tomando valores no conjunto 
latexmath:[$1,2,3,\ldots$]. Suponha que latexmath:[$P(X=n) = (1/2)^n$]. 
Defina a função latexmath:[$g:\{1,2,3,\ldots\}\to R$] dada por 
latexmath:[$f(2k) = 1$], latexmath:[$k=1,2,3,\ldots$], e latexmath:[$f(2k-1)=-1$], 
para latexmath:[$k=1,2,3,\ldots$]. Ou seja, latexmath:[$g(x)$] é igual a 1 se 
latexmath:[$x$] é par, e é igual a -1 se latexmath:[$x$] é ímpar. 
Desta forma, definindo latexmath:[$Y=g(X)$], temos que 

[latexmath]
++++
\[Y = \begin{cases}
1,&\textrm{se }X\textrm{ for par},\\
-1,&\textrm{se }X\textrm{ for ímpar}.
\end{cases}\]
++++

Assim, temos que latexmath:[$P(Y=1) = P(g(X) = 1) = P(X\in g^{-1}(\{1\}))$]. 
Note que latexmath:[$g(x)=1$] se, e somente se, latexmath:[$x$] é par, ou seja, 
latexmath:[$g^{-1}(\{1\}) = \{2,4,6,\ldots\}$]. Assim, 

[latexmath]
++++
\[
\begin{array}{lll}
P(Y=1) &=& P(X\in \{2,4,6,\ldots\}) = (1/2)^2+(1/2)^4+(1/2)^6 +\cdots = 1/4 + (1/4)^2 + (1/4)^3 + \cdots\\
&=& \frac{1/4}{1-1/4} = 1/3.
\end{array}
\]
++++

Por outro lado, latexmath:[$P(Y=-1) = 1 - P(Y=1) = 1 -1/3 = 2/3.$]

Observe que outra forma equivalente de calcular latexmath:[$P(Y=1)$], 
seria observar que latexmath:[$Y=1$] se, e somente se, latexmath:[$X$] 
é par, e portanto latexmath:[$\{Y=1\} = \{X\in\{2,4,6,\ldots\}\}$]. 
E portanto, latexmath:[$P(Y=1) = P(X\in\{2,4,6,\ldots\})$].

====

.Exemplo de função de variável aleatória contínua
====
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade dada por latexmath:[$f(x) = 2x$], se 
latexmath:[$x\in (0,1)$], e 0 caso contrário. Seja latexmath:[$Y = 3X+1$]. Vamos encontrar a função de densidade 
de latexmath:[$Y$], que denotaremos por latexmath:[$f_Y(y)$].

Primeiramente, note que como latexmath:[$Im(X) = (0,1)$], e assim latexmath:[$Im(Y) = (1,4)$]. 
Observe, agora, que latexmath:[$P(Y\leq y) = P(3X+1\leq y)$]. Sabemos que latexmath:[$3X+1 \leq y$] se, 
e somente se, latexmath:[$X\leq (y-1)/3$]. Portanto, vale latexmath:[$F_Y(y) = P(3X+1\leq y) = P(X\leq (y-1)/3) = F_X((y-1)/3)$]. 

Finalmente, se latexmath:[$y\leq 0$], então latexmath:[$F_Y(y) = P(Y\leq y) = 0$], e se 
latexmath:[$y\geq 4$], temos latexmath:[$F_Y(y) = P(Y\leq y) = 1$].  Portanto, se latexmath:[$y< 0$],
então latexmath:[$f_Y(y)= F_Y'(y) = 0$], e se latexmath:[$y> 4$], então latexmath:[$f_Y(y) = F_Y'(y) = 0$].

Agora, se latexmath:[$y\in (1,4)$], temos que latexmath:[$F_Y(y) = F_X((y-1)/3)$], e portanto, pela regra da cadeia

[latexmath]
++++
\[f_Y(y) = F_Y'(y) = F_X'( (y-1)/3 ) \cdot 1/3 = f((y-1)/3)\cdot 1/3 = \frac{2 ((y-1)/3)}{3} = \frac{2(y-1)}{9}.\]
++++

====

Exercício::
+
--
Considere latexmath:[$X$] variável aleatória contínua com a densidade do exemplo anterior. 
Seja latexmath:[$g(x) = e^{-x}$]. Obtenha a função de densidade de latexmath:[$Y=g(X) = e^{-X}$], 
latexmath:[$f_Y(y)$].
--

_Solução_::
+
--
Como latexmath:[$Im(X) = (0,1)$], temos que latexmath:[$Im(Y) = (1/e,1)$]. Assim,
se latexmath:[$y<1/e$], então latexmath:[$F_Y(y) = P(Y\leq y) = 0$], e se
latexmath:[$y>1$], então latexmath:[$F_Y(y) = P(Y\leq y) = 1$]. Isto implica que 
se latexmath:[$y<1/e$], latexmath:[$f_Y(y) =F_Y'(y)= 0$], e se latexmath:[$y>1$],
temos latexmath:[$f_Y(y)=F_Y'(y)=0$]. 

Falta considerarmos latexmath:[$y \in (1/e,1)$]. Assim, temos que latexmath:[$Y\leq y$] se, 
e somente se, latexmath:[$e^{-X}\leq y$], que por sua vez, vale se, e somente 
se, latexmath:[$X\geq -\ln(y)$]. Portanto, 
latexmath:[$F_Y(y) = P(Y\leq y) = P(X\geq -\ln(y)) = 1-F_X(-\ln(y))$]. 
Onde temos que 
[latexmath]
++++
\[P(X\geq -\ln(y)) = 1 - P(X<-\ln(y)) = 1- P(X\leq -\ln(y)) = 1-F_X(-\ln(y)),\]
++++
pois latexmath:[$P(X=-\ln(y))=0$], já que latexmath:[$X$] é uma variável aleatória contínua.

Desta forma, obtemos, usando a regra da cadeia, que para latexmath:[$y\in (1/e,1)$], 

[latexmath]
++++
\[f_Y(y) = F_Y'(y) = (1-F_X(-\ln(y))' = -f_X(-\ln(y))\cdot\frac{-1}{y} = \frac{-2\ln(y)}{y}.\]
++++

--

Exercício::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de 
densidade latexmath:[$f$]. Seja latexmath:[$Y = X^2$]. Encontre a 
função de densidade da variável aleatória latexmath:[$Y$], latexmath:[$f_Y$]. 
--

_Solução_::
+
--
Observe que latexmath:[$X^2\geq 0$]. Daí, se latexmath:[$y<0$], segue que 
latexmath:[$F_Y(y) = P(Y\leq y) = 0$], e portanto, para latexmath:[$y<0$], vale latexmath:[$f_Y(y)=0$].

Suponha agora que latexmath:[$y\geq 0$], e note que latexmath:[$Y\leq y$] se,
e somente se, latexmath:[$X^2\leq y$]. Esta última desigualdade vale se, e somente se,
latexmath:[$X^2-y\leq 0$]. Resolvendo essa inequação, obtemos que latexmath:[$X^2-y\leq 0$] se,
e somente se, latexmath:[$X\geq -\sqrt{y}$] e latexmath:[$X\leq \sqrt{y}$]. Assim, vale a 
igualdade entre os conjuntos latexmath:[$\{Y\leq y\} = \{-\sqrt{y}\leq X\leq \sqrt{y}\}$]. 

Portanto, como latexmath:[$X$] é variável aleatória contínua, segue que,

[latexmath]
++++
\[F_Y(y) = P(Y\leq y) = P(-\sqrt{y}\leq X\leq \sqrt{y}) = P(X\leq \sqrt{y}) - P(X<-\sqrt{y}) = F_X(\sqrt{y}) - F_X(-\sqrt{y}).\]
++++

Daí, pela regra da cadeia, vale que 
[latexmath]
++++
\[F_Y'(y) = f(\sqrt{y})\cdot \frac{1}{2\sqrt{y}} - f(-\sqrt{y})\cdot\frac{-1}{2\sqrt{y}} = \frac{1}{2\sqrt{y}}\left(f(\sqrt{y})+f(-\sqrt{y})\right).\]
++++

Portanto, latexmath:[$f_Y(y) = \frac{1}{2\sqrt{y}}\left(f(\sqrt{y})+f(-\sqrt{y})\right).$]
--

////
Sempre termine os arquivos com uma linha em branco.
////


