== Esperança de uma Variável Aleatória

Vamos começar introduzindo uma notação que será útil ao estudar o conceito de
esperança matemática: variáveis aleatórias independentes.

=== Variáveis aleatórias independentes
(((Variáveis Aleatórias, Independentes)))
Relembre a definição de eventos independentes: sejam latexmath:[$\Omega$]
um espaço amostral, latexmath:[$A$] e latexmath:[$B$] 
eventos de latexmath:[$\Omega$]. Então, dizemos que os eventos 
latexmath:[$A$] e latexmath:[$B$] são independentes se 
latexmath:[$P(A\cap B) = P(A)P(B)$]. 


Esta definição motiva a definição de independência entre 
variáveis aleatórias:

Definição: Variáveis Aleatórias Independentes::
+
--

Sejam latexmath:[$X:\Omega\to R$] e latexmath:[$Y:\Omega\to R$] 
duas variáveis aleatórias. 
Dizemos que latexmath:[$X$] e latexmath:[$Y$] são independentes 
se para todos os eventos 
latexmath:[$A,B\in R$], vale a fórmula:

[latexmath]
++++
\[P(X\in A\textrm{ e } Y\in B) = P(X\in A)P(Y\in B).\] 
++++

--

[NOTE]
====
Sejam latexmath:[$X$] e latexmath:[$Y$] são duas variáveis 
aleatórias discretas. 
Suponha que latexmath:[$X$] toma valores no conjunto 
latexmath:[$\{a_1,a_2,a_3,\ldots\}$] e que latexmath:[$Y$] 
toma valores no conjunto latexmath:[$\{b_1,b_2,b_3,\ldots\}$]. 
Então, é possível mostrar que
latexmath:[$X$] e latexmath:[$Y$] são independentes se, e somente se, 
para cada latexmath:[$a_i$] e latexmath:[$b_j$], temos 
[latexmath]
++++
\[P(X = a_i, Y=b_j) = P(X=a_i)P(Y=b_j).\]
++++
====

=== Esperança matemática

(((Esperança, Variável Aleatória)))

Vamos começar motivando a definição de esperança. A esperança pode 
ser pensada como uma generalização da média. 
De fato, suponha que temos 10 pesos. O primeiro possui 1 quilo, o 
segundo 2 quilos, ..., o décimo 10 quilos. 
Suponha que uma pessoa escolhe um peso aleatoriamente, onde todos os 
pesos possuem a mesma probabilidade de serem escolhidos. 
Qual o peso médio? 


Temos 1 quilo com probabilidade 1/10, 2 quilos com probabilidade 1/10, ..., 
10 quilos com probabilidade 1/10. 
Assim, o peso médio é latexmath:[$m = 1/10 + 2/10 + \cdots + 10/10 = 5,5$].

Mais geralmente temos a

(((Esperança, Variável Aleatória Discreta)))

Definição: Esperança de Variáveis Aleatórias Discretas
+
--

Seja latexmath:[$X$] uma variável aleatória discreta tomando valores no 
conjunto latexmath:[$\{a_1,a_2,a_3,\ldots\}$]. 
Seja latexmath:[$p(a_i) = P(X=a_i)$] sua função de probabilidade. Então,
definimos a esperança, ou valor esperado, de latexmath:[$X$] como:
[latexmath]
++++
\[E(X) = \sum_{i=1}^\infty a_i p(a_i),\]
++++
se a série latexmath:[$\sum_{i=1}^\infty |a_i| p(a_i)$] convergir, ou seja, 
se a série latexmath:[$\sum_{i=1}^\infty a_i p(a_i)$] 
convergir absolutamente. Caso a série em questão não convirja absolutamente, 
dizemos que a esperança de latexmath:[$X$] não existe.
--

É claro que se latexmath:[$X$] toma apenas uma quantidade finita de valores, 
digamos latexmath:[$a_1,\ldots,a_n$], então a esperança de 
latexmath:[$X$] é dada por
[latexmath]
++++
\[E(X) = \sum_{i=1}^n a_ip(a_i).\]
++++

[NOTE]
====
Observe que como a soma latexmath:[$p(a_1)+\cdots+p(a_n)=1$], podemos pensar 
nesta esperança como uma média ponderada, entre os valores
latexmath:[$a_1,\ldots,a_n$], com os pesos latexmath:[$p(a_1),\ldots,p(a_n)$]. 
Note ainda que se todos os valores forem igualmente possíveis,
ou seja, se para cada latexmath:[$i$], latexmath:[$p(a_i)=1/n$], então a esperança
será dada simplesmente pela média aritmética
entre os valores possíveis:
[latexmath]
++++
\[E(X) = \frac{1}{n} \sum_{i=1}^n a_i.\]
++++
====

.Exemplo de esperança de variável aleatória discreta
====
Seja latexmath:[$X$] uma variável aleatória que toma valor latexmath:[$1$] com 
probabilidade latexmath:[$p$], e valor latexmath:[$0$]
com probabilidade latexmath:[$1-p$]. Temos então que 
[latexmath]
++++
\[ E(X) = 0p(0) + 1p(1) = p(1)=P(X=1) = p.\]
++++
====


Vamos agora definir esperança para variáveis aleatórias contínuas.

(((Esperança, Variável Aleatória Contínua)))

Definição: Esperança de Variáveis Aleatórias Contínuas::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade
latexmath:[$f$]. 
Definimos a esperança de latexmath:[$X$] como
[latexmath]
++++
\[E(X) = \int_{-\infty}^\infty f(x)dx,\]
++++
se
[latexmath]
++++
\[\int_{-\infty}^\infty |x| f(x) dx < \infty.\]
++++
No caso da integral imprópria acima divergir, dizemos que a
esperança de latexmath:[$X$] não existe.
--

.Exemplo de esperança de variável aleatória contínua
====
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade dada por 
[latexmath]
++++
\[f(x) = \begin{cases}
\frac{1}{b-a},& a< x< b,\\
0,& \hbox{caso contrário.}
\end{cases}
\]
++++
Portanto,
[latexmath]
++++
\[
\begin{array}{lll}
E(X) &=& \int_a^b \frac{x}{b-a} dx = \frac{1}{b-a} \cdot \frac{x^2}{2}\Big|_a^b\\
&=& \frac{b^2-a^2}{2(b-a)} = \frac{(b+a)(b-a)}{2(b-a)}\\
&=& \frac{a+b}{2}.
\]
++++
====

=== Esperança de uma Função de Variável Aleatória

(((Esperança, Variável Aleatória, Função de)))

Definição: Esperança de função de variável aleatória::
+
--
Seja latexmath:[$X$] uma variável aleatória e seja latexmath:[$Y = H(X)$], para uma função real latexmath:[$H$]. Temos então dois casos:

. Se latexmath:[$X$] for uma variável aleatória discreta tomando valores em latexmath:[$\{a_1,a_2,\ldots\}$], 
e se latexmath:[$p$] é a função de probabilidade de latexmath:[$X$], temos que

[latexmath]
++++
\[ E(Y) = E(H(X)) = \sum_{i=1}^\infty H(a_i)P(X=a_i) = \sum_{i=1}^\infty H(a_i)p(a_i).\]
++++

. Se latexmath:[$X$] for uma variável aleatória contínua com função de densidade latexmath:[$f$], então temos que

[latexmath]
++++
\[E(Y) = E(H(X)) = \int_{-\infty}^\infty H(x)f(x)dx.\]
++++
--









