== Esperança de uma Variável Aleatória

Vamos começar introduzindo uma notação que será útil ao estudar o conceito de
esperança matemática: variáveis aleatórias independentes.

=== Variáveis aleatórias independentes
(((Variáveis Aleatórias, Independentes)))

Relembre a definição de eventos independentes: sejam latexmath:[$\Omega$]
um espaço amostral, latexmath:[$A$] e latexmath:[$B$] 
eventos de latexmath:[$\Omega$]. Então, dizemos que os eventos 
latexmath:[$A$] e latexmath:[$B$] são independentes se 
latexmath:[$P(A\cap B) = P(A)P(B)$]. 


Esta definição motiva a definição de independência entre 
variáveis aleatórias:

Definição: Variáveis Aleatórias Independentes::
+
--
Sejam latexmath:[$X:\Omega\to R$] e latexmath:[$Y:\Omega\to R$] 
duas variáveis aleatórias. 
Dizemos que latexmath:[$X$] e latexmath:[$Y$] são independentes 
se para todos os eventos 
latexmath:[$A,B\in R$], vale a fórmula:

[latexmath]
++++
\[P(X\in A\textrm{ e } Y\in B) = P(X\in A)P(Y\in B).\] 
++++

--

[NOTE]
====
Sejam latexmath:[$X$] e latexmath:[$Y$] são duas variáveis 
aleatórias discretas. 
Suponha que latexmath:[$X$] toma valores no conjunto 
latexmath:[$\{a_1,a_2,a_3,\ldots\}$] e que latexmath:[$Y$] 
toma valores no conjunto latexmath:[$\{b_1,b_2,b_3,\ldots\}$]. 
Então, é possível mostrar que
latexmath:[$X$] e latexmath:[$Y$] são independentes se, e somente se, 
para cada latexmath:[$a_i$] e latexmath:[$b_j$], temos 
[latexmath]
++++
\[P(X = a_i, Y=b_j) = P(X=a_i)P(Y=b_j).\]
++++
====

=== Esperança matemática

(((Esperança, Variável Aleatória)))

Vamos começar motivando a definição de esperança. A esperança pode 
ser pensada como uma generalização da média. 
De fato, suponha que temos 10 pesos. O primeiro possui 1 quilo, o 
segundo 2 quilos, ..., o décimo 10 quilos. 
Suponha que uma pessoa escolhe um peso aleatoriamente, onde todos os 
pesos possuem a mesma probabilidade de serem escolhidos. 
Qual o peso médio? 


Temos 1 quilo com probabilidade 1/10, 2 quilos com probabilidade 1/10, ..., 
10 quilos com probabilidade 1/10. 
Assim, o peso médio é latexmath:[$m = 1/10 + 2/10 + \cdots + 10/10 = 5,5$].

Mais geralmente temos a

(((Esperança, Variável Aleatória Discreta)))

Definição: Esperança de Variáveis Aleatórias Discretas::
+
--

Seja latexmath:[$X$] uma variável aleatória discreta tomando valores no 
conjunto latexmath:[$\{a_1,a_2,a_3,\ldots\}$]. 
Seja latexmath:[$p(a_i) = P(X=a_i)$] sua função de probabilidade. Então,
definimos a esperança, ou valor esperado, de latexmath:[$X$] como:
[latexmath]
++++
\[E(X) = \sum_{i=1}^\infty a_i p(a_i),\]
++++
se a série latexmath:[$\sum_{i=1}^\infty |a_i| p(a_i)$] convergir, ou seja, 
se a série latexmath:[$\sum_{i=1}^\infty a_i p(a_i)$] 
convergir absolutamente. Caso a série em questão não convirja absolutamente, 
dizemos que a esperança de latexmath:[$X$] não existe.
--

É claro que se latexmath:[$X$] toma apenas uma quantidade finita de valores, 
digamos latexmath:[$a_1,\ldots,a_n$], então a esperança de 
latexmath:[$X$] é dada por
[latexmath]
++++
\[E(X) = \sum_{i=1}^n a_ip(a_i).\]
++++

[NOTE]
====
Observe que como a soma latexmath:[$p(a_1)+\cdots+p(a_n)=1$], podemos pensar 
nesta esperança como uma média ponderada, entre os valores
latexmath:[$a_1,\ldots,a_n$], com os pesos latexmath:[$p(a_1),\ldots,p(a_n)$]. 
Note ainda que se todos os valores forem igualmente possíveis,
ou seja, se para cada latexmath:[$i$], latexmath:[$p(a_i)=1/n$], então a esperança
será dada simplesmente pela média aritmética
entre os valores possíveis:
[latexmath]
++++
\[E(X) = \frac{1}{n} \sum_{i=1}^n a_i.\]
++++
====

.Exemplo de esperança de variável aleatória discreta
====
Seja latexmath:[$X$] uma variável aleatória que toma valor latexmath:[$1$] com 
probabilidade latexmath:[$p$], e valor latexmath:[$0$]
com probabilidade latexmath:[$1-p$]. Temos então que 
[latexmath]
++++
\[ E(X) = 0p(0) + 1p(1) = p(1)=P(X=1) = p.\]
++++
====


Vamos agora definir esperança para variáveis aleatórias contínuas.

(((Esperança, Variável Aleatória Contínua)))

Definição: Esperança de Variáveis Aleatórias Contínuas::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade
latexmath:[$f$]. 
Definimos a esperança de latexmath:[$X$] como
[latexmath]
++++
\[E(X) = \int_{-\infty}^\infty f(x)dx,\]
++++
se
[latexmath]
++++
\[\int_{-\infty}^\infty |x| f(x) dx < \infty.\]
++++
No caso da integral imprópria acima divergir, dizemos que a
esperança de latexmath:[$X$] não existe.
--

.Exemplo de esperança de variável aleatória contínua
====
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade dada por 
[latexmath]
++++
\[f(x) = \begin{cases}
\frac{1}{b-a},& a< x< b,\\
0,& \hbox{caso contrário.}
\end{cases}
\]
++++
Portanto,
[latexmath]
++++
\[
\begin{array}{lll}
E(X) &=& \displaystyle\int_a^b \frac{x}{b-a} dx = \frac{1}{b-a} \cdot \frac{x^2}{2}\Big|_a^b\\
&=& \frac{b^2-a^2}{2(b-a)} = \frac{(b+a)(b-a)}{2(b-a)}\\
&=& \frac{a+b}{2}.
\end{array}
\]
++++
====

=== Esperança de uma Função de Variável Aleatória

(((Esperança, Variável Aleatória, Função de)))

Definição: Esperança de função de variável aleatória::
+
--
Seja latexmath:[$X$] uma variável aleatória e seja latexmath:[$Y = H(X)$], para uma função real latexmath:[$H$]. Temos então dois casos:

* Se latexmath:[$X$] for uma variável aleatória discreta tomando valores em latexmath:[$\{a_1,a_2,\ldots\}$], 
e se latexmath:[$p$] é a função de probabilidade de latexmath:[$X$], temos que

[latexmath]
++++
\[ E(Y) = E(H(X)) = \sum_{i=1}^\infty H(a_i)P(X=a_i) = \sum_{i=1}^\infty H(a_i)p(a_i).\]
++++

* Se latexmath:[$X$] for uma variável aleatória contínua com função de densidade latexmath:[$f$], então temos que

[latexmath]
++++
\[E(Y) = E(H(X)) = \int_{-\infty}^\infty H(x)f(x)dx.\]
++++
--

.Exemplo de esperança de função de uma variável aleatória discreta
====
Vamos relembrar um exemplo estudando quando introduzimos funções de variáveis aleatórias: 
seja latexmath:[$X$] uma variável aleatória discreta tomando valores no conjunto 
latexmath:[$1,2,3,\ldots$]. Suponha que latexmath:[$P(X=n) = (1/2)^n$]. 
Defina a função latexmath:[$g:\{1,2,3,\ldots\}\to R$] dada por 
latexmath:[$f(2k) = 1$], latexmath:[$k=1,2,3,\ldots$], e latexmath:[$f(2k-1)=-1$], 
para latexmath:[$k=1,2,3,\ldots$]. Ou seja, latexmath:[$g(x)$] é igual a 1 se 
latexmath:[$x$] é par, e é igual a -1 se latexmath:[$x$] é ímpar. 
Desta forma, definindo latexmath:[$Y=g(X)$], temos que 

[latexmath]
++++
\[
\begin{array}{lll}
E(Y) &=& E(g(X)) = \displaystyle\sum_{i=1}^\infty g(i) P(X=i)\\
&=& \displaystyle\sum_{i=1}^\infty g(2i)P(X=2i) + \sum_{i=1}^\infty g(2i-1)P(X=2i-1)\\
&=& \displaystyle\sum_{i=1}^\infty P(X=2i) + \sum_{i=1}^\infty (-1) P(X=2i-1)\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - \sum_{i=1}^\infty (1/2)^{2i-1}\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - \sum_{i=1}^\infty 2\cdot (1/2)^{2i}\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - 2 \sum_{i=1}^\infty (1/2)^{2i}\\
&=& -\displaystyle\sum_{i=1}^\infty (1/2)^{2i}\\
&=& -\displaystyle\sum_{i=1}^\infty (1/4)^{i}\\
&=& - \frac{1/4}{1-1/4}\\
&=& -1/3.
\end{array}
\]
++++

Portanto, latexmath:[$E(Y) = -1/3$]. 

Note que, quando apresentamos o exemplo no Capítulo 4, vimos que latexmath:[$Y$] só 
assume os valores latexmath:[$-1$] e latexmath:[$1$]. Além disso, calculamos sua função de probabilidade:
[latexmath]
++++
\[
P(Y=-1) = 2/3 \hbox{~~e~~} P(Y=1) = 1/3.
\]
++++

Desta forma, usando diretamente a definição de esperança de variáveis aleatórias discretas, temos:

[latexmath]
++++
\[E(Y) = (-1)\cdot 2/3 + 1\cdot 1/3 = -2/3 + 1/3 = -1/3.\]
++++

Logo, vemos que não há contradição entre as definições, e as esperanças sempre vão coincidir.
====

[IMPORTANT]
====
Como vimos no exemplo anterior, na hora de calcular a esperança de funções de variáveis aleatórias discretas,
temos duas opções:

* Calcular diretamente, usando a função de probabilidade de latexmath:[$X$], através da fórmula
[latexmath]
++++
\[E(Y) = E(H(X)) = \sum_{i=1}^\infty H(a_i) P(X=a_i);\]
++++
* Obter a função de probabilidade de latexmath:[$Y$] e depois calcular a esperança de latexmath:[$Y$] diretamente:
[latexmath]
++++
\[E(Y) = \sum_{j=1}^\infty b_j P(Y=b_j),\]
++++
onde latexmath:[$Y$] toma valores em latexmath:[$\{b_1,b_2,\ldots\}$].
====

.Exemplo de esperança de função de uma variável aleatória contínua
====
Suponha que latexmath:[$X$] é uma variável aleatória contínua com função de densidade
[latexmath]
++++
\[ f(x) = \begin{cases}
\frac{e^x}{2},& x\leq 0,\\
\frac{e^{-x}}{2},& x>0.
\end{cases}
\]
++++
Tome latexmath:[$Y = |X|$], então latexmath:[$E(Y)$] é dada por
[latexmath]
++++
\[
\begin{array}{lll}
E(Y) &=& E(|X|) = \displaystyle\int_{-\infty}^\infty |x|f(x)dx\\
&=&  \displaystyle\int_{-\infty}^0-x\frac{e^x}{2} dx + \displaystyle\int_0^\infty x \frac{e^{-x}}{2} dx.
\end{array}
\]
++++

Observe que integrando por partes, obtemos que latexmath:[$F(x) = -xe^x + e^x$] é uma primitiva para latexmath:[$-xe^x$] e que 
latexmath:[$G(x) = -xe^{-x} -e^{-x}$] é uma primitiva para latexmath:[$xe^{-x}$]. Daí,

[latexmath]
++++
\[\int_{-\infty}^0-x\frac{e^x}{2} dx =\frac{1}{2}(-xe^x + e^x)\Big|_{-\infty}^0 = \frac{1}{2}\hbox{~~e~~} 
\int_0^\infty x \frac{e^{-x}}{2} dx = \frac{1}{2}(-xe^{-x} -e^{-x})\Big|_0^\infty = \frac{1}{2}.\]
++++

Finalmente, juntando todas as informações, obtemos
[latexmath]
++++
\[
E(Y) = \displaystyle\int_{-\infty}^0-x\frac{e^x}{2} dx + \displaystyle\int_0^\infty x \frac{e^{-x}}{2} dx = \frac{1}{2}+\frac{1}{2} = 1.
\]
++++

Assim como no caso de variáveis discretas, podemos calcular a esperança de latexmath:[$Y$] diretamente. Para isto, vamos obter
a função de densidade de latexmath:[$Y$]. Observe que como latexmath:[$X$] é variável aleatória contínua, latexmath:[$P(X=y)=0$] para
todo latexmath:[$y$] real. Assim, como latexmath:[$Y\geq 0$], segue que para todo latexmath:[$y\geq 0$]:
[latexmath]
++++
\[F_Y(y) = P(Y\leq y) = P(|X|\leq y) = P(-y\leq X\leq y) = P(-y < X\leq y) = F_X(y) - F_X(-y).\]
++++

Desta forma, por derivação, obtemos que a função de densidade de latexmath:[$Y$], latexmath:[$f_Y(y)$] é dada por 
[latexmath]
++++
\[f_Y(y) = f(y) + f(-y) = \frac{e^{-y}}{2} + \frac{e^{-y}}{2} = e^{-y},\]
++++
e latexmath:[$f(y) = 0$], se latexmath:[$y<0$].

Portanto, 
[latexmath]
++++
\[E(Y) = \int_{-\infty}^\infty yf_Y(y)dy = \int_0^\infty ye^{-y}dy = (ye^{-y} -e^y)\Big|_0^\infty = 1,\]
++++
donde usamos que latexmath:[$H(y) = ye^{-y} - e^y$] é primitiva de latexmath:[$ye^{-y}$].

Assim como no caso de funções de variáveis aleatórias discretas, as duas formas de calcular a esperança fornecem o mesmo resultado.
====

[IMPORTANT]
====
Como vimos no exemplo anterior, e no caso de funções de variáveis aleatórias discretas,
na hora de calcular a esperança de funções de variáveis aleatórias contínuas, temos duas opções:

* Calcular diretamente, usando a função de densidade de latexmath:[$X$], através da fórmula
[latexmath]
++++
\[E(Y) = E(H(X)) = \int_{-\infty}^\infty H(x) f(x)dx;\]
++++
* Obter a função de densidade de latexmath:[$Y$], latexmath:[$f_Y(y)$], 
e depois calcular a esperança de latexmath:[$Y$] diretamente:
[latexmath]
++++
\[E(Y) = \int_{-\infty}^\infty yf_Y(y)dy.\]
++++
====







