== Esperança de uma Variável Aleatória

Vamos começar introduzindo uma notação que será útil ao estudar o conceito de
esperança matemática: variáveis aleatórias independentes.

=== Variáveis aleatórias independentes
(((Variáveis Aleatórias, Independentes)))

Relembre a definição de eventos independentes: sejam latexmath:[$\Omega$]
um espaço amostral, latexmath:[$A$] e latexmath:[$B$] 
eventos de latexmath:[$\Omega$]. Então, dizemos que os eventos 
latexmath:[$A$] e latexmath:[$B$] são independentes se 
latexmath:[$P(A\cap B) = P(A)P(B)$]. 


Esta definição motiva a definição de independência entre 
variáveis aleatórias:

Definição: Variáveis Aleatórias Independentes::
+
--
Sejam latexmath:[$X:\Omega\to R$] e latexmath:[$Y:\Omega\to R$] 
duas variáveis aleatórias. 
Dizemos que latexmath:[$X$] e latexmath:[$Y$] são independentes 
se para todos os eventos 
latexmath:[$A,B\in R$], vale a fórmula:

[latexmath]
++++
\[P(X\in A\textrm{ e } Y\in B) = P(X\in A)P(Y\in B).\] 
++++

--

[NOTE]
====
Sejam latexmath:[$X$] e latexmath:[$Y$] são duas variáveis 
aleatórias discretas. 
Suponha que latexmath:[$X$] toma valores no conjunto 
latexmath:[$\{a_1,a_2,a_3,\ldots\}$] e que latexmath:[$Y$] 
toma valores no conjunto latexmath:[$\{b_1,b_2,b_3,\ldots\}$]. 
Então, é possível mostrar que
latexmath:[$X$] e latexmath:[$Y$] são independentes se, e somente se, 
para cada latexmath:[$a_i$] e latexmath:[$b_j$], temos 
[latexmath]
++++
\[P(X = a_i, Y=b_j) = P(X=a_i)P(Y=b_j).\]
++++
====

=== Esperança matemática

(((Esperança, Variável Aleatória)))

Vamos começar motivando a definição de esperança. A esperança pode 
ser pensada como uma generalização da média. 
De fato, suponha que temos 10 pesos. O primeiro possui 1 quilo, o 
segundo 2 quilos, ..., o décimo 10 quilos. 
Suponha que uma pessoa escolhe um peso aleatoriamente, onde todos os 
pesos possuem a mesma probabilidade de serem escolhidos. 
Qual o peso médio? 


Temos 1 quilo com probabilidade 1/10, 2 quilos com probabilidade 1/10, ..., 
10 quilos com probabilidade 1/10. 
Assim, o peso médio é latexmath:[$m = 1/10 + 2/10 + \cdots + 10/10 = 5,5$].

Mais geralmente temos a

(((Esperança, Variável Aleatória Discreta)))

Definição: Esperança de Variáveis Aleatórias Discretas::
+
--

Seja latexmath:[$X$] uma variável aleatória discreta tomando valores no 
conjunto latexmath:[$\{a_1,a_2,a_3,\ldots\}$]. 
Seja latexmath:[$p(a_i) = P(X=a_i)$] sua função de probabilidade. Então,
definimos a esperança, ou valor esperado, de latexmath:[$X$] como:
[latexmath]
++++
\[E(X) = \sum_{i=1}^\infty a_i p(a_i),\]
++++
se a série latexmath:[$\sum_{i=1}^\infty |a_i| p(a_i)$] convergir, ou seja, 
se a série latexmath:[$\sum_{i=1}^\infty a_i p(a_i)$] 
convergir absolutamente. Caso a série em questão não convirja absolutamente, 
dizemos que a esperança de latexmath:[$X$] não existe.
--

É claro que se latexmath:[$X$] toma apenas uma quantidade finita de valores, 
digamos latexmath:[$a_1,\ldots,a_n$], então a esperança de 
latexmath:[$X$] é dada por
[latexmath]
++++
\[E(X) = \sum_{i=1}^n a_ip(a_i).\]
++++

[NOTE]
====
Observe que como a soma latexmath:[$p(a_1)+\cdots+p(a_n)=1$], podemos pensar 
nesta esperança como uma média ponderada, entre os valores
latexmath:[$a_1,\ldots,a_n$], com os pesos latexmath:[$p(a_1),\ldots,p(a_n)$]. 
Note ainda que se todos os valores forem igualmente possíveis,
ou seja, se para cada latexmath:[$i$], latexmath:[$p(a_i)=1/n$], então a esperança
será dada simplesmente pela média aritmética
entre os valores possíveis:
[latexmath]
++++
\[E(X) = \frac{1}{n} \sum_{i=1}^n a_i.\]
++++
====

.Exemplo de esperança de variável aleatória discreta
====
Seja latexmath:[$X$] uma variável aleatória que toma valor latexmath:[$1$] com 
probabilidade latexmath:[$p$], e valor latexmath:[$0$]
com probabilidade latexmath:[$1-p$]. Temos então que 
[latexmath]
++++
\[ E(X) = 0p(0) + 1p(1) = p(1)=P(X=1) = p.\]
++++
====


Vamos agora definir esperança para variáveis aleatórias contínuas.

(((Esperança, Variável Aleatória Contínua)))

Definição: Esperança de Variáveis Aleatórias Contínuas::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade
latexmath:[$f$]. 
Definimos a esperança de latexmath:[$X$] como
[latexmath]
++++
\[E(X) = \int_{-\infty}^\infty f(x)dx,\]
++++
se
[latexmath]
++++
\[\int_{-\infty}^\infty |x| f(x) dx < \infty.\]
++++
No caso da integral imprópria acima divergir, dizemos que a
esperança de latexmath:[$X$] não existe.
--

.Exemplo de esperança de variável aleatória contínua
====
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade dada por 
[latexmath]
++++
\[f(x) = \begin{cases}
\frac{1}{b-a},& a< x< b,\\
0,& \hbox{caso contrário.}
\end{cases}
\]
++++
Portanto,
[latexmath]
++++
\[
\begin{array}{lll}
E(X) &=& \displaystyle\int_a^b \frac{x}{b-a} dx = \frac{1}{b-a} \cdot \frac{x^2}{2}\Big|_a^b\\
&=& \frac{b^2-a^2}{2(b-a)} = \frac{(b+a)(b-a)}{2(b-a)}\\
&=& \frac{a+b}{2}.
\end{array}
\]
++++
====

=== Esperança de uma Função de Variável Aleatória

(((Esperança, Variável Aleatória, Função de)))

Definição: Esperança de função de variável aleatória::
+
--
Seja latexmath:[$X$] uma variável aleatória e seja latexmath:[$Y = H(X)$], para uma função real latexmath:[$H$]. Temos então dois casos:

* Se latexmath:[$X$] for uma variável aleatória discreta tomando valores em latexmath:[$\{a_1,a_2,\ldots\}$], 
e se latexmath:[$p$] é a função de probabilidade de latexmath:[$X$], temos que

[latexmath]
++++
\[ E(Y) = E(H(X)) = \sum_{i=1}^\infty H(a_i)P(X=a_i) = \sum_{i=1}^\infty H(a_i)p(a_i).\]
++++

* Se latexmath:[$X$] for uma variável aleatória contínua com função de densidade latexmath:[$f$], então temos que

[latexmath]
++++
\[E(Y) = E(H(X)) = \int_{-\infty}^\infty H(x)f(x)dx.\]
++++
--

.Exemplo de esperança de função de uma variável aleatória discreta
====
Vamos relembrar um exemplo estudando quando introduzimos funções de variáveis aleatórias: 
seja latexmath:[$X$] uma variável aleatória discreta tomando valores no conjunto 
latexmath:[$1,2,3,\ldots$]. Suponha que latexmath:[$P(X=n) = (1/2)^n$]. 
Defina a função latexmath:[$g:\{1,2,3,\ldots\}\to R$] dada por 
latexmath:[$f(2k) = 1$], latexmath:[$k=1,2,3,\ldots$], e latexmath:[$f(2k-1)=-1$], 
para latexmath:[$k=1,2,3,\ldots$]. Ou seja, latexmath:[$g(x)$] é igual a 1 se 
latexmath:[$x$] é par, e é igual a -1 se latexmath:[$x$] é ímpar. 
Desta forma, definindo latexmath:[$Y=g(X)$], temos que 

[latexmath]
++++
\[
\begin{array}{lll}
E(Y) &=& E(g(X)) = \displaystyle\sum_{i=1}^\infty g(i) P(X=i)\\
&=& \displaystyle\sum_{i=1}^\infty g(2i)P(X=2i) + \sum_{i=1}^\infty g(2i-1)P(X=2i-1)\\
&=& \displaystyle\sum_{i=1}^\infty P(X=2i) + \sum_{i=1}^\infty (-1) P(X=2i-1)\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - \sum_{i=1}^\infty (1/2)^{2i-1}\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - \sum_{i=1}^\infty 2\cdot (1/2)^{2i}\\
&=& \displaystyle\sum_{i=1}^\infty (1/2)^{2i} - 2 \sum_{i=1}^\infty (1/2)^{2i}\\
&=& -\displaystyle\sum_{i=1}^\infty (1/2)^{2i}\\
&=& -\displaystyle\sum_{i=1}^\infty (1/4)^{i}\\
&=& - \frac{1/4}{1-1/4}\\
&=& -1/3.
\end{array}
\]
++++

Portanto, latexmath:[$E(Y) = -1/3$]. 

Note que, quando apresentamos o exemplo no Capítulo 4, vimos que latexmath:[$Y$] só 
assume os valores latexmath:[$-1$] e latexmath:[$1$]. Além disso, calculamos sua função de probabilidade:
[latexmath]
++++
\[
P(Y=-1) = 2/3 \hbox{~~e~~} P(Y=1) = 1/3.
\]
++++

Desta forma, usando diretamente a definição de esperança de variáveis aleatórias discretas, temos:

[latexmath]
++++
\[E(Y) = (-1)\cdot 2/3 + 1\cdot 1/3 = -2/3 + 1/3 = -1/3.\]
++++

Logo, vemos que não há contradição entre as definições, e as esperanças sempre vão coincidir.
====

[IMPORTANT]
====
Como vimos no exemplo anterior, na hora de calcular a esperança de funções de variáveis aleatórias discretas,
temos duas opções:

* Calcular diretamente, usando a função de probabilidade de latexmath:[$X$], através da fórmula
[latexmath]
++++
\[E(Y) = E(H(X)) = \sum_{i=1}^\infty H(a_i) P(X=a_i);\]
++++
* Obter a função de probabilidade de latexmath:[$Y$] e depois calcular a esperança de latexmath:[$Y$] diretamente:
[latexmath]
++++
\[E(Y) = \sum_{j=1}^\infty b_j P(Y=b_j),\]
++++
onde latexmath:[$Y$] toma valores em latexmath:[$\{b_1,b_2,\ldots\}$].
====

.Exemplo de esperança de função de uma variável aleatória contínua
====
Suponha que latexmath:[$X$] é uma variável aleatória contínua com função de densidade
[latexmath]
++++
\[ f(x) = \begin{cases}
\frac{e^x}{2},& x\leq 0,\\
\frac{e^{-x}}{2},& x>0.
\end{cases}
\]
++++
Tome latexmath:[$Y = |X|$], então latexmath:[$E(Y)$] é dada por
[latexmath]
++++
\[
\begin{array}{lll}
E(Y) &=& E(|X|) = \displaystyle\int_{-\infty}^\infty |x|f(x)dx\\
&=&  \displaystyle\int_{-\infty}^0-x\frac{e^x}{2} dx + \displaystyle\int_0^\infty x \frac{e^{-x}}{2} dx.
\end{array}
\]
++++

Observe que integrando por partes, obtemos que latexmath:[$F(x) = -xe^x + e^x$] é uma primitiva para latexmath:[$-xe^x$] e que 
latexmath:[$G(x) = -xe^{-x} -e^{-x}$] é uma primitiva para latexmath:[$xe^{-x}$]. Daí,

[latexmath]
++++
\[\int_{-\infty}^0-x\frac{e^x}{2} dx =\frac{1}{2}(-xe^x + e^x)\Big|_{-\infty}^0 = \frac{1}{2}\hbox{~~e~~} 
\int_0^\infty x \frac{e^{-x}}{2} dx = \frac{1}{2}(-xe^{-x} -e^{-x})\Big|_0^\infty = \frac{1}{2}.\]
++++

Finalmente, juntando todas as informações, obtemos
[latexmath]
++++
\[
E(Y) = \displaystyle\int_{-\infty}^0-x\frac{e^x}{2} dx + \displaystyle\int_0^\infty x \frac{e^{-x}}{2} dx = \frac{1}{2}+\frac{1}{2} = 1.
\]
++++

Assim como no caso de variáveis discretas, podemos calcular a esperança de latexmath:[$Y$] diretamente. Para isto, vamos obter
a função de densidade de latexmath:[$Y$]. Observe que como latexmath:[$X$] é variável aleatória contínua, latexmath:[$P(X=y)=0$] para
todo latexmath:[$y$] real. Assim, como latexmath:[$Y\geq 0$], segue que para todo latexmath:[$y\geq 0$]:
[latexmath]
++++
\[F_Y(y) = P(Y\leq y) = P(|X|\leq y) = P(-y\leq X\leq y) = P(-y < X\leq y) = F_X(y) - F_X(-y).\]
++++

Desta forma, por derivação, obtemos que a função de densidade de latexmath:[$Y$], latexmath:[$f_Y(y)$] é dada por 
[latexmath]
++++
\[f_Y(y) = f(y) + f(-y) = \frac{e^{-y}}{2} + \frac{e^{-y}}{2} = e^{-y},\]
++++
e latexmath:[$f(y) = 0$], se latexmath:[$y<0$].

Portanto, 
[latexmath]
++++
\[E(Y) = \int_{-\infty}^\infty yf_Y(y)dy = \int_0^\infty ye^{-y}dy = (ye^{-y} -e^y)\Big|_0^\infty = 1,\]
++++
donde usamos que latexmath:[$H(y) = ye^{-y} - e^y$] é primitiva de latexmath:[$ye^{-y}$].

Assim como no caso de funções de variáveis aleatórias discretas, as duas formas de calcular a esperança fornecem o mesmo resultado.
====

[IMPORTANT]
====
Como vimos no exemplo anterior, e no caso de funções de variáveis aleatórias discretas,
na hora de calcular a esperança de funções de variáveis aleatórias contínuas, temos duas opções:

* Calcular diretamente, usando a função de densidade de latexmath:[$X$], através da fórmula
[latexmath]
++++
\[E(Y) = E(H(X)) = \int_{-\infty}^\infty H(x) f(x)dx;\]
++++
* Obter a função de densidade de latexmath:[$Y$], latexmath:[$f_Y(y)$], 
e depois calcular a esperança de latexmath:[$Y$] diretamente:
[latexmath]
++++
\[E(Y) = \int_{-\infty}^\infty yf_Y(y)dy.\]
++++
====

=== Propriedades da Esperança

Nessa seção vamos apresentar várias propriedades da esperança matemática e demonstrar algumas delas.

Propriedades da esperança::
+
--
* (Esperança da constante): Seja latexmath:[$c\in\mathbb{R}$] um número real, e seja latexmath:[$X$]
a variável aleatória constante igual a latexmath:[$c$], ou seja, latexmath:[$P(X=c)=1$]. Então
latexmath:[$E(X) = c.$]. 

* (Sinal da esperança): Se latexmath:[$X\geq 0$], então latexmath:[$E(X)\geq 0$], e 
se latexmath:[$X\leq 0$], então latexmath:[$E(X)\leq 0$].

* (Multiplicação por constante): Seja latexmath:[$c\in\mathbb{R}$] um número real, e seja 
latexmath:[$X$] uma variável aleatória. Então latexmath:[$E(cX)=cE(X)$].

* (Soma de variáveis aleatórias): Sejam latexmath:[$X$] e latexmath:[$Y$] variáveis aleatórias
quaisquer, então latexmath:[$E(X+Y) = E(X) + E(Y)$]. 

* (Combinação linear de variáveis aleatórias): Sejam latexmath:[$X_1,X_2,\ldots,X_n$] variáveis
aleatórias, e latexmath:[$c_1,c_2,\ldots,c_n$] números reais. Então
[latexmath]
++++
\[E\Big( \sum_{i=1}^n c_i X_i\Big) = \sum_{i=1}^n c_i E(X_i).\]
++++

* (Produto de variáveis aleatórias independentes): Sejam latexmath:[$X$] e latexmath:[$Y$] 
variáveis aleatórias independentes, então
[latexmath]
++++
\[ E(XY) = E(X)E(Y).\]
++++
--

_Demonstração_::
+
--
* (Esperança da constante): Note que latexmath:[$X$] é uma variável aleatória discreta que toma
apenas o valor latexmath:[$c$], e portanto
[latexmath]
++++
\[E(X) = c P(X=c) = c.\]
++++


* (Sinal da esperança): Vamos demonstrar o caso latexmath:[$X\geq 0$] para variáveis aleatórias
discretas e para variáveis aleatórias contínuas. Os casos de variáveis aleatórias
mistas e latexmath:[$X\leq 0$] ficam como exercícios para o leitor.

Seja latexmath:[$X$] variável aleatória discreta, latexmath:[$X\geq 0$], tomando valores
no conjunto latexmath:[$\{a_1,a_2,\ldots\}$]. Como latexmath:[$X\geq 0$], segue que 
para todo latexmath:[$i$], temos latexmath:[$a_i\geq 0$]. Além disso,
latexmath:[$P(X=a_i)\geq 0$]. Logo,
[latexmath]
++++
\[ E(X) = \sum_{i=1}^n a_i P(X=a_i) \geq 0.\]
++++

Seja, agora, latexmath:[$X$] variável aleatória contínua, latexmath:[$X\geq 0$], com função de densidade
latexmath:[$f(x)$]. Então, como latexmath:[$X\geq 0$], vale latexmath:[$f(x)=0$] se latexmath:[$x<0$]. Daí

[latexmath]
++++
\[ E(X) = \int_{-\infty}^\infty xf(x)dx = \int_0^\infty xf(x)dx \geq 0.\]
++++

* (Multiplicação por contante): Vamos demonstrar para variáveis aleatórias
discretas e para variáveis aleatórias contínuas. O caso de variáveis aleatórias
mistas fica como exercício para o leitor.

Seja, então, latexmath:[$X$] variável aleatória discreta, e suponha que latexmath:[$X$]
toma valores no conjunto latexmath:[$\{a_1,a_2,\ldots\}$]. Então, latexmath:[$cX$] 
é função da variável aleatória discreta, daí
[latexmath]
++++
\[E(cX) = \sum_{i=1}^\infty ca_i P(X=a_i) = c\sum_{i=1}^\infty a_i P(X=a_i) = cE(X).\]
++++

Suponha agora que latexmath:[$X$] é variável aleatória contínua com função de densidade
latexmath:[$f(x)$]. Então, latexmath:[$cX$] é função de uma variável aleatória contínua, 
e segue que
[latexmath]
++++
\[E(X) = \int_{-\infty}^\infty cxf(x)dx = c\int_{-\infty}^\infty f(x)dx = cE(X).\]
++++

* (Soma de variáveis aleatórias): A demonstração foge do escopo do livro.

* (Combinação linear de variáveis aleatórias): Usando a propriedade da soma de variáveis aleatórias
latexmath:[$n$] vezes, temos que
[latexmath]
++++
\[E\Big(\sum_{i=1}^n c_i X_i\Big) = \sum_{i=1}^n E(c_iX_i).\]
++++
Usando a propriedade da multiplicação por constante, obtemos o resultado desejado:
[latexmath]
++++
\[E\Big(\sum_{i=1}^n c_i X_i\Big) = \sum_{i=1}^n E(c_iX_i) = \sum_{i=1}^n c_iE(X_i) .\]
++++

* (Produto de variáveis aleatórias independentes): Foge do escopo do livro.
--

=== Variância de uma variável aleatória
(((Variância, Variável Aleatória)))
(((Variável Aleatória, Variância)))
Vamos agora utilizar a esperança para definir uma noção de variabilidade 
da variável aleatória: a variância. 

A variância de uma variável aleatória mede o quanto a variável aleatória
flutua em torno da esperança. Ou seja, mede quanto os valores
da variável aleatória latexmath:[$X$] podem se afastar da esperança.

Vale observar também que se a variância de latexmath:[$X$] for igual a zero,
então latexmath:[$X$] não varia nada, com relação à esperança, e portanto
a variável aleatória latexmath:[$X$] é constante igual à esperança de 
latexmath:[$X$].

Definição: Variância de uma variável aleatória::
+
--
Seja latexmath:[$X$] uma variável aleatória. Definimos a variância de latexmath:[$X$] como
[latexmath]
++++
\[ Var(X) = E\big[(X-E(X))^2\big].\]
++++
--

[NOTE]
====
Observe que como latexmath:[$(X-E(X))^2\geq 0$], temos pela propriedade do sinal
da esperança que latexmath:[$E\big[ (X-E(X))^2\big\] \geq 0$], e portanto
latexmath:[$Var(X)\geq 0$]. 
====
(((Variável Aleatória, Desvio padrão)))

Uma noção muito útil em estatística é dada pela raiz quadrada da variância (pois a variância é maior ou igual a zero). 
Mais precisamente, seja latexmath:[$X$] uma variável aleatória, então o número latexmath:[$\sqrt{Var(X)}$] é chamado
de _desvio padrão_ de latexmath:[$X$], e é denotado por latexmath:[$\sigma_X$]. 

O seguinte resultado fornece uma simplificação do cálculo da variância:

Proposição::
+
--
Seja latexmath:[$X$] uma variável aleatória, então latexmath:[$Var(X) = E(X^2) - (E(X))^2$]. 
--

_Demonstração_::
+
--
Temos que como latexmath:[$E(X)$] é um número real constante, podemos utilizar
as propriedades: esperança da multiplicação por constante; esperança da constante; e esperança da soma, para obter:
[latexmath]
++++
\[
\begin{array}{lll}
Var(X) &=& E\big[(X-E(X))^2\Big]\\
&=& E\big[ X^2 - 2X E(X) + E(X)^2\Big]\\
&=& E(X^2) - 2E(XE(X)) + E(X)^2\\
&=& E(X^2) - 2E(X)^2 + E(X)^2\\
&=& E(X^2) - (E(X))^2.
\end{array}
\]
++++
--

[IMPORTANT]
====
É possível mostrar que se latexmath:[$Var(X)=0$], então latexmath:[$P(X = E(X))=1$]. Ou seja, 
latexmath:[$X$] é uma variável aleatória constante. Quanto maior o valor da variância,
mais a variável aleatória pode se afastar da esperança, ou seja, maior a oscilação da variável
aleatória em torno da esperança.
====

.Exemplo de variância de uma variável aleatória discreta
====
Seja latexmath:[$X$] a variável aleatória discreta que toma valor latexmath:[$1$] com 
probabilidade latexmath:[$p$] e toma valor latexmath:[$0$] com probabilidade
latexmath:[$1-p$]. 

Então, temos que latexmath:[$E(X) = 0\cdot (1-p) + 1\cdot p = p$]. Daí,
[latexmath]
++++
\[Var(X) = E(X^2) - E(X)^2 = E(X^2) - p^2 = 0^2\cdot (1-p) + 1\cdot p - p^2 = p(1-p).\]
++++
====

.Exemplo de variância de uma variável aleatória contínua
====
Seja latexmath:[$X$] variável aleatória contínua com função de densidade
[latexmath]
++++
\[
f(x) = \begin{cases}
1+x,& -1\leq x\leq 0,\\
1-x,& 0\leq x\leq 1,\\
0,& \hbox{caso contrário.}
\end{cases}
\]
++++

Comece notando que
[latexmath]
++++
\[
\begin{array}{lll}
E(X) &=& \displaystyle\int_{-1}^0 x(1+x)dx + \displaystyle\int_0^1 x(1-x) dx\\
&=& \displaystyle\int_{-1}^0 x+x^2 dx + \displaystyle\int_0^1x-x^2dx\\
&=& \Big(\frac{x^2}{2}+\frac{x^3}{3}\Big)\Big|_{-1}^0 + \Big(\frac{x^2}{2}-\frac{x^3}{3}\Big)\Big|_0^1\\
&=& -1/2 +1/3 +1/2 - 1/3\\
&=& 0.
\end{array}
\]
++++

Além disso,
[latexmath]
++++
\[
\begin{array}{lll}
E(X^2) &=& \displaystyle\int_{-1}^0 x^2(1+x)dx + \displaystyle\int_0^1 x^2(1-x) dx\\
&=& \displaystyle\int_{-1}^0 x^2+x^3 dx + \displaystyle\int_0^1x^2-x^3dx\\
&=& \Big(\frac{x^3}{3}+\frac{x^4}{4}\Big)\Big|_{-1}^0 + \Big(\frac{x^3}{3}-\frac{x^4}{4}\Big)\Big|_0^1\\
&=& 1/3-1/4 +1/3 -1/4\\
&=& 1/6.
\end{array}
\]
++++

Logo, latexmath:[$Var(X) = E(X^2) = 1/6$]. 

====

=== Propriedades da variância
Nesta seção vamos apresentar algumas propriedades da variância e provar algumas delas.

Propriedades da variância::
+
--
* (Variância da constante): Seja latexmath:[$c\in\mathbb{R}$] um número real, e seja latexmath:[$X$]
a variável aleatória constante igual a latexmath:[$c$], ou seja, latexmath:[$P(X=c)=1$]. Então,
latexmath:[$Var(X) = 0$].

* (Soma por constante): Seja latexmath:[$X$] uma variável aleatória e seja latexmath:[$c\in\mathbb{R}$] 
uma constante. Então, latexmath:[$Var(X+c) = Var(X)$].

* (Variância da soma de variáveis independentes): Sejam latexmath:[$X$] e latexmath:[$Y$] variáveis
aleatórias independentes. Então, latexmath:[$Var(X+Y) = Var(X)+Var(Y)$]. 

* (Variância da multiplicação por constante): Seja latexmath:[$X$] variável aleatória, e seja
latexmath:[$c\in\mathbb{R}$] uma constante. Então, latexmath:[$Var(cX) = c^2 Var(x)$]. 

* (Variância de uma função afim de latexmath:[$X$]): Sejam latexmath:[$a,b\in\mathbb{R}$], e seja
latexmath:[$X$] variável aleatória. Então, latexmath:[$Var(aX+b) = a^2Var(X)$].

--


_Demonstração_::
+
--
* (Variância da constante): Observe que se latexmath:[$X$] é constante igual a latexmath:[$c$],
temos pela propriedade da esperança que latexmath:[$E(X) = c$]. Daí
[latexmath]
++++
\[Var(X) = E\Big[ (X-E(X))^2\Big] = E[ (c-c)^2] = 0.\]
++++


* (Soma por constante): Usando as propriedades da esperança,
temos diretamente que
[latexmath]
++++
\[
Var(X+c) = E\Big[ (X+c - E(X+c))^2\Big] = E\Big[ (X+c -E(X)-c)^2\Big] = E\Big[(X-E(X))^2\Big] = Var(X).
\]
++++


* (Variância da soma de variáveis independentes): Foge do escopo do livro.

* (Variância da multiplicação por constante): Usando as propriedades da esperança, temos que
[latexmath]
++++
\[
\begin{array}{lll}
Var(cX) &=& E\Big[ (cX - E(cX))^2\Big] = E\Big[ (cX - cE(X))^2\Big]\\
&=& E\Big[c^2 (X-E(X))^2\Big] = c^2 E\Big[(X-E(X))^2\Big]\\
&=& c^2Var(X).
\end{array}
\]
++++


* (Variância de uma função afim de latexmath:[$X$]): Usando a variância da soma por constante, temos que
latexmath:[$Var(aX+b) = Var(aX)$], e usando a variância da multiplicação por constante obtemos
latexmath:[$Var(aX) = a^2Var(X)$]. Combinando as duas igualdades obtemos 
latexmath:[$Var(aX+b) = a^2Var(X)$].
--

Exercício::
+
--
Seja latexmath:[$X$] uma variável aleatória contínua com função de densidade
[latexmath]
++++
\[f(x) = \begin{cases}
\frac{1}{b-a},& a< x< b,\\
0,& \hbox{caso contrário.}
\end{cases}
\]
++++
Encontre latexmath:[$Var(X)$].
--

_Solução_::
+
--
Já vimos no exemplo de esperança de variável aleatória contínua que latexmath:[$E(X) = \frac{a+b}{2}$]. Temos agora que
[latexmath]
++++
\[
\begin{array}{lll}
E(X^2) &=& \displaystyle\int_a^b x^2\frac{1}{b-a} dx = \frac{1}{b-a}\Big|_a^b\\
&=& \displaystyle\frac{1}{b-a} \Big(\frac{b^3}{3} - \frac{a^3}{3}\Big)\\
&=& \displaystyle\frac{b^3-a^3}{3(b-a)}.
\end{array}
\]
++++

Mas observe agora que temos o produto notável:
[latexmath]
++++
\[(b-a)(a^2+ab+b^2) = a^2b + ab^2+b^3-a^3-a^2b-ab^2 = b^3-a^3.\]
++++

Portanto, segue que
[latexmath]
++++
\[
E(X^2) = \frac{b^3-a^3}{3(b-a)} = \frac{(b-a)(a^2+ab+b^2)}{3(b-a)} = \frac{a^2+ab+b^2}{3}.
\]
++++

Finalmente, temos
[latexmath]
++++
\[
Var(X) = E(X^2) - (E(X))^2 = \frac{a^2+ab+b^2}{3} - \frac{(a+b)^2}{4} = \frac{a^2-2ab+b^2}{12} = \frac{(b-a)^2}{12}.
\]
++++

Resumindo, latexmath:[$Var(X) = (b-a)^2/12.$]
--







