== Principais Distribuições Contínuas

Aqui apresentaremos algumas das principais distribuições contínuas. Para tanto, apresentaremos suas funções de densidade.

Além disso, apresentaremos algumas propriedades destas distribuições, tais como esperança e variância.

=== Distribuição Uniforme

(((Distribuição, Uniforme)))

Definição: Variável Aleatória Seguindo Distribuição Uniforme::
+
--
Suponha que x:[X] seja uma variável aleatória contínua que assuma valores no intervalo x:[[a,b\]], no qual
x:[a] e x:[b] sejam ambos finitos. Se a função de densidade de x:[X] for dada por
[latexmath]
++++
\[
f(x) = \begin{cases}
\frac{1}{b-a},& a\leq x\leq b,\\
0,& \textrm{caso contrário},
\end{cases}
\]
++++
dizemos que x:[X] é uniformemente distribuída sobre o intervalo x:[[a,b\]], e denotamos x:[X\sim U[a,b\]].
--

Uma variável aleatória uniformemente distribuída representa o análogo contínuo dos resultados equiprováveis 
no seguinte sentido: Para qualquer subintervalo x:[[c,d\]], onde x:[a\leq c<d\leq b], x:[P(c\leq X\leq d)]
é a mesma para todos os subintervalos que tenham o mesmo comprimento. Ou seja,
[latexmath]
++++
\[
P(c\leq X\leq d)= \int_c^d f(x)dx = \frac{d-c}{b-a},
\]
++++
e, por isso, depende unicamente do comprimento do intervalo.

Esperança:: 
+
--
Temos que 
[latexmath]
++++
\[
E(X) = \int_a^b x\frac{b-a}dx = \frac{x^2}{2(b-a)}\Big|_a^b = \frac{b^2-a^2}{2(b-a)} = \frac{a+b}{2}.
\]
++++
--

Variância::
+
--
Temos que
[latexmath]
++++
\[
E(X^2) = \int_a^b \frac{x^2}{b-a}dx = \frac{x^3}{3(b-a)}\Big|_a^b = \frac{b^3-a^3}{3(b-a)} = \frac{a^2+ab+b^2}{3}.
\]
++++
Portanto, obtemos que
[latexmath]
++++
\[
Var(X) = E(X^2)-(E(X))^2 = \frac{a^2+ab+b^2}{3} - \frac{(a+b)^2}{4} = \frac{(b-a)^2}{12}.
\]
++++
--

.Exemplo de aplicação da distribuição uniforme
====
Um ponto é escolhido ao acaso no segmento de reta x:[[0,2\]]. Qual será a probabilidade de que o ponto escolhido esteja entre 
1 e 3/2?

Seja x:[X] a variável aleatória que representa a coordenada do ponto escolhido. Temos que x:[X\sim U[0,2\]], daí
[latexmath]
++++
\[
f(x) = \begin{cases}
1/2,&0\leq x\leq 2,\\
0,&\textrm{caso contrário},
\end{cases}
\]
++++
e
[latexmath]
++++
\[
P(1\leq X\leq 3/2) = \int_1^{3/2} \frac{1}{2} dx = \frac{1}{2}\Big(\frac{3}{2}-1\Big) = \frac{1}{4}.
\]
++++
====

=== A Distribuição Normal

(((Distribuição, Normal)))

Definição: Variável Aleatória Seguindo Distribuição Normal::
+
--
A variável aleatória x:[X], que assume valores na reta, x:[-\infty<x<\infty], tem distribuição normal
se sua função de densidade é da forma
[latexmath]
++++
\[
f(x) = \frac{1}{\sqrt{2\pi}\sigma}e^{-\frac{(x-\mu)^2}{2\sigma^2}},\quad -\infty<x<\infty, 
\]
++++
onde x:[-\infty<\mu<\infty] e x:[\sigma>0], e denotamos x:[X\sim N(\mu,\sigma^2)].
--

Na figura abaixo apresentamos gráficos das funções de densidade da distribuição normal para alguns valores
de x:[\mu] e x:[\sigma^2]:

.Exemplo de funções de densidade da distribuição normal para valores de x:[\mu] e x:[\sigma^2] descritos no par ordenado x:[(\mu;\sigma^2)]
image::images/densidades/densidadenormal.eps[scaledwidth="60%"] 

Esperança e Variância::
+
--
Temos que se x:[X\sim N(\mu,\sigma^2)], então
[latexmath]
++++
\[
E(X) = \mu\quad\hbox{~e~} Var(X) = \sigma^2.
\]
++++
--

==== Padronização e Tabulação da Distribuição Normal

(((Distribuição, Normal, Tabulação)))
(((Distribuição, Normal, Padronização)))

Temos que se x:[X\sim N(\mu,\sigma^2)], então a variável _padronizada_
[latexmath]
++++
\[
Z = \frac{X-\mu}{\sigma}
\]
++++
terá distribuição normal padrão, ou seja, x:[Z\sim N(0,1)], e sua função de densidade é dada por
[latexmath]
++++
\[
f(z) = \frac{1}{\sqrt{2\pi}} e^{-\frac{z^2}{2}},\quad -\infty<z<\infty.
\]
++++

Logo, temos que
[latexmath]
++++
\[
P(a\leq Z\leq b) = \int_a^b \frac{1}{\sqrt{2\pi}} e^{-\frac{z^2}{2}}dz.
\]
++++

Desta forma, dada uma variável aleatória x:[X\sim N(\mu,\sigma^2)], podemos padronizá-la
na variável x:[Z], e obter as probabilidades a partir da tabela de valores da 
função de distribuição da normal padrão
[latexmath]
++++
\[
\Phi(z) = P(Z\leq z) = \int_{-\infty}^z \frac{1}{\sqrt{2\pi}} e^{-\frac{z^2}{2}}dz.
\]
++++

NOTE: Observe que na padronização dividimos por x:[\sigma], que é o desvio padrão da variável aleatória normal. *Não* dividimos pela variância.

A distribuição normal padrão satisfaz a seguinte propriedade se *simetria*:
[latexmath]
++++
\[
\Phi(-x) = 1-\Phi(x).
\]
++++

[IMPORTANT]
====
A identidade de simetria acima nos diz que podermos calcular as probabilidades x:[P(Z\leq -x)] a partir 
das probabilidades x:[P(Z\leq x)]. Assim, como a tabela da normal apresentada no apêndice não contém 
valores negativos de x:[x], para calcularmos estas probabilidades, utilizamos a fórmula acima.
====

.Exemplo de cálculo de probabilidades utilizando a tabela da normal
====
Seja x:[Z\sim N(0,1)]. Vamos calcular as probabilidades x:[P(0\leq Z\leq 1), P(Z\geq 1,93), P(-2,55\leq Z\leq 1,2)] e 
x:[P(Z\leq 1,93)]. 

Observe inicialmente que
[latexmath]
++++
\[
P(0\leq Z \leq 1) = \Phi(1) - \Phi(0).
\]
++++

Olhando para a tabela da normal (que pode ser encontrada no Apêndice deste livro), obtemos que
x:[\Phi(1) = 0,8413] e x:[\Phi(0) = 0,5]. Portanto
[latexmath]
++++
\[
P(0\leq Z \leq 1) = \Phi(1) - \Phi(0)=0,8413-0,5 = 0,3413.
\]
++++

Para a próxima probabilidade, temos que x:[P(Z\geq 1,93) = 1 - P(Z\leq 1,93) = 1-\Phi(1,93)]. Olhando para a tabela no apêndice, obtemos
x:[P(Z\geq 1,93) = 1-\Phi(1,93) =1- 0,9732 = 0,0268]. 


A próxima probabilidade deve ser observada com cuidado, pois temos um valor negativo, e se olharmos na tabela, não há valores
negativos, e portanto, teremos que usar a simetria da distribuição normal. Assim,
[latexmath]
++++
\[
\begin{array}{lll}
P(-2,55\leq Z\leq 1,2) &=& \Phi(1,2) - \Phi(-2,55) = \Phi(1,2) - (1-\Phi(2,55))\\
&=& \Phi(1,2)+\Phi(2,55) - 1 = 0,8849+0,9946-1\\
&=&0,8795.
\end{array}
\]
++++

Finalmente, x:[P(Z\leq 1,93) = \Phi(1,93) = 0,0268.]
====

Veremos agora mais alguns exemplos de aplicações da distribuição normal.

.Exemplo de aplicação da distribuição normal
====
Suponha que as alturas dos alunos de ciências da computação da UFPB seguem distribuição normal
com média 1,60m e desvio padrão 0,30m. Seja x:[X] a variável aleatória que indica a altura de
um aluno de ciências da computação da UFPB escolhido ao acaso.
Encontre a probabilidade de um aluno medir:

a) Entre 1,50m e 1,80m;

Queremos calcular x:[P(1,50\leq X\leq 1,80)].  Observe que 
[latexmath]
++++
\[
Z = \frac{X-1,60}{0,30} \sim N(0,1).
\]
++++

Temos então que:
[latexmath]
++++
\[
\begin{array}{lll}
P(1,50\leq X\leq 1,80) &=& P(1,50-1,60 \leq X-1,60\leq 1,80-1,60) = P(-0,1\leq X-1,60\leq 0,2)\\
&=& P(-0,1/0,3 \leq (X-1,60)/0,30 \leq 0,2/0,3) = P(-1/3\leq Z\leq 2/3)\\
&=& \Phi(0,67) - \Phi(-0,33)\\
&=& \Phi(0,67) - (1-\Phi(0,33))\\
&=& \Phi(0,67)+\Phi(0,33) -1\\
&=& 0,7486+0,6293-1\\
&=& 0,3779.
\end{array}
\]
++++

b) Mais de 1,75m;

Queremos calcular x:[P(X\geq 1,75)].

Temos então que:
[latexmath]
++++
\[
\begin{array}{lll}
P(X\geq 1,75) &=& P(X-1,60\geq 1,75-1,60) = P(X-1,60\geq 0,15)\\
&=& P((X-1,60)/0,30 \geq 0,15/0,3) = P( Z\geq 1/2)\\
&=& 1 - P(Z\leq 1/2)\\
&=& 1-\Phi(0,5)\\
&=& 1-0,6915\\
&=& 0,3085.
\end{array}
\]
++++

c) Menos de 1,48m;

Queremos calcular x:[P(X\leq 1,48)].

Temos então que:
[latexmath]
++++
\[
\begin{array}{lll}
P(X\leq 1,48) &=& P(X-1,60\leq 1,48-1,60) = P(X-1,60\leq -0,12)\\
&=& P((X-1,60)/0,30 \leq -0,12/0,3) = P( Z\leq -4/10)\\
&=&\Phi(-0,4)\\
&=& 1-\Phi(0,4)\\
&=& 0,3446.
\end{array}
\]
++++

d) Qual deve ser a altura mínima para escolhermos 10% dos alunos mais altos?

Queremos encontrar um valor x:[c], tal que x:[P(X>c)=0,10].

Assim, temos que
[latexmath]
++++
\[
\begin{array}{lll}
P(X> c) &=& P(X-1,60> c-1,60)\\
&=& P((X-1,60)/0,30 > (c-1,60)/0,3) = P( Z> (c-1,60)/0,3)\\
&=&1-\Phi((c-1,60)/0,3).
\end{array}
\]
++++
Assim, queremos encontrar x:[c], tal que x:[0,1 = 1-\Phi((c-1,60)/0,3)], ou seja,
x:[\Phi((c-1,60)/0,3) = 0,9]. Seja x:[z = (c-1,60)/0,3], temos que x:[\Phi(z) = 0,9].
Olhando para a tabela, vemos que z = 1,28. 

Logo, x:[(c-1,60)/0,3 = 1,28], o que implica que x:[c = 1,6 + 0,384 = 1,984]. Desta forma,
a altura em questão é 1,98m.
====


==== Aproximação da Distribuição Binomial pela Normal

Vimos no capítulo de variáveis aleatórias discretas que podemos aproximar a distribuição binomial pela
distribuição Poisson. 

A aproximação da distribuição binomial pela Poisson é boa quando o parâmetro x:[p] da distribuição binomial
é pequeno. Se este valor for grande, a aproximação pela distribuição Poisson é pobre. Neste caso,
devemos aproximar pela distribuição normal.

Proposição: Aproximação da distribuição binomial pela normal::
+
--
Suponha que x:[X_n] é uma sequência de variáveis aleatórias tais que x:[X_n\sim Bin(n,p)].
Então, vale o seguinte resultado:
[latexmath]
++++
\[
\lim_{n\to\infty} P\Big(\frac{X_n-np}{\sqrt{np(1-p)}} \leq z\Big) = \Phi(z),
\]
++++
onde x:[\Phi(z)] é a função de distribuição da normal padrão.

Desta forma, vale a aproximação para x:[n] grande:
[latexmath]
++++
\[
P(X_n\leq x) \approx \Phi\Big( \frac{x-np}{\sqrt{np(1-p)}}\Big).
\]
++++
--

.Exemplo de aplicação da aproximação da binomial pela normal
====
Suponha que lançamos uma moeda honesta 200 vezes. Obtenha a probabilidade do número de caras
estar entre 45% e 55% dos lançamentos (incluindo os extremos). Ou seja, se
x:[X_n] denota o número de caras obtidas após os 200 lançamentos, temos que
x:[X_n\sim Bin(200,1/2)], e queremos calcular 
[latexmath]
++++
\[
P(90\leq X_n\leq 110) = P(X_n\leq 110) - P(X_n\leq 89).
\]
++++

Como o parâmetro x:[p] da binomial não é pequeno, ou seja, não está próximo de zero,
a aproximação ideal é dada pela normal. 

Assim, como x:[\sqrt{np(1-p)}=7,07] e x:[np = 100], pela proposição anterior, temos que
[latexmath]
++++
\[
\begin{array}{lll}
P(90\leq X_n\leq 110) &\approx& \Phi\Big(\frac{110-100}{7,07}\Big) - \Phi\Big(\frac{90-100}{7,07}\Big)\\
&=& \Phi(1,41) - \Phi(-1,27)\\
&=& \Phi(1,41) - (1-\Phi(1,27))\\
&=& \Phi(1,41)+\Phi(1,27) - 1\\
&=&  0,9207+0,8980-1\\
&=& 0,8187.
\end{array}
\]
++++

Logo, a probabilidade é de aproximadamente 0,8187.
====

[NOTE]
====
No exemplo anterior:

* A probabilidade exata é dada por 0,8626. 

* A probabilidade obtida pela aproximação de Poisson é dada por 0,7065. Vemos que a aproximação é, de fato, muito pobre neste caso.

O motivo da aproximação ser ruim é que a aproximação da binomial pela Poisson supõe que a probabilidade x:[p] da binomial tende a zero
quando x:[n] tende a infinito, o que não acontece no exemplo anterior.
====

=== A Distribuição Exponencial

(((Distribuição, Exponencial)))

A distribuição exponencial é uma distribuição muito utilizada na prática para modelar tempo de falha de objetos.
Por exemplo, pode ser usada para modelar o tempo que demora até uma lâmpada falhar. Ela possui um parâmetro,
x:[\lambda], que pode ser interpretado da seguinte forma: x:[1/\lambda] é o tempo de vida médio do objeto.

Mais precisamente, temos a

Definição: Variável Aleatória Seguindo Distribuição Exponencial::
+
--
Uma variável aleatória contínua x:[X] assumindo valores não-negativos é dita seguir
distribuição exponencial com parâmetro x:[\lambda>0], se sua função de densidade é dada por
[latexmath]
++++
\[
f(x) = \begin{cases}
\lambda e^{-\lambda x},& x\geq 0,\\
0,& x< 0.
\end{cases}
\]
++++
Denotamos x:[X\sim Exp(\lambda)].
--

Observe que x:[f(x)] é, de fato, uma função de densidade, pois x:[f(x)\geq 0] para todo x:[x], e, além disso,
[latexmath]
++++
\[
\begin{array}{lll}
\displaystyle\int_{-\infty}^\infty f(x)dx &=& \displaystyle\int_0^\infty \lambda e^{-\lambda x} dx\\
&=& \displaystyle\lambda \frac{e^{-\lambda x}}{-\lambda}\Big|_0^\infty = \lambda\frac{1}{\lambda}\\
&=&1.
\end{array}
\]
++++


Na figura abaixo apresentamos gráficos das funções de densidade da distribuição exponencial para alguns valores
de x:[\lambda]:

.Exemplo de funções de densidade da distribuição exponencial para valores de x:[\lambda] descritos no parêntese x:[(\lambda)]
image::images/densidades/densidadeexp.eps[scaledwidth="60%"] 

Podemos também calcular a função de distribuição de uma variável aleatória seguindo distribuição exponencial
explicitamente:

[latexmath]
++++
\[
\begin{array}{lll}
F(x) &=& P(X\leq x) = \int_0^x \lambda e^{-\lambda x}dx = \lambda\frac{e^{-\lambda x}}{-\lambda}\Big|_0^x\\
&=& \lambda\Big[\frac{-e^{-\lambda x}}{\lambda} - \frac{1}{\lambda}\Big]\\
&=& 1 - e^{-\lambda x},
\end{array}
\]
++++
para x:[x\geq 0], e x:[F(x) = 0], se x:[x<0]. 

Em particular, obtemos x:[P(X>x) = e^{-\lambda x}.]

Esperança::
+
--
Temos que
[latexmath]
++++
\[
E(X) = \int_0^\infty x \lambda e^{-\lambda x} dx.
\]
++++

Integrando por partes com x:[dv = \lambda e^{-\lambda x}dx] e x:[u = x], temos que x:[v = -e^{-\lambda x}] e x:[du = dx], e portanto,

[latexmath]
++++
\[
\begin{array}{lll}
E(X) &=& \displaystyle -x e^{-\lambda x}\Big|_0^\infty - \int_0^\infty - e^{-\lambda x} dx\\
&=& 0 + \frac{e^{-\lambda x}}{-\lambda} \Big|_0^\infty\\
&=& \frac{1}{\lambda}.
\end{array}
\]
++++
--

Variância::
+
--
Integrando por partes duas vezes, obtemos que
[latexmath]
++++
\[
E(X^2) = \frac{2}{\lambda^2}.
\]
++++
Portanto,
[latexmath]
++++
\[
Var(X) = E(X^2) - (E(X))^2 = \frac{2}{\lambda^2} - \frac{1}{\lambda^2} = \frac{1}{\lambda^2}.
\]
++++
--

.Exemplo de cálculo envolvendo a distribuição exponencial
====
Suponha que x:[X\sim Exp(\lambda)]. Vamos encontrar a probabilidade de que x:[X] seja maior que seu valor esperado.
De fato, como x:[E(X) = 1/\lambda], queremos calcular:
[latexmath]
++++
\[
P(X>1/\lambda) = 1 - F(1/\lambda) = 1- (1 - e^{-\lambda \cdot 1/\lambda}) = e^{-1} \approx 0,37.
\]
++++
====

Exercício::
+
--
O tempo médio de falha das lâmpadas produzidas em uma certa fábrica é de 17500 horas. Sabendo que o tempo de falha destas lâmpadas segue
distribuição exponencial, qual é a probabilidade de uma lâmpada falhar no primeiro ano de uso?
--

_Solução_::
+
--
Primeiro, observe que como o tempo médio de falha é de 17500 horas, o parâmetro da exponencial é dado por
[latexmath]
++++
\[
\frac{\lambda} = \frac{1}{17500}.
\]
++++

Como um ano tem 365 dias (em geral não considera-se anos bissextos), temos x:[24\cdot 365 = 8760] horas em um ano. Assim, queremos
calcular
[latexmath]
++++
\[
P(X\leq 8760) = 1-e^{-\frac{1}{17500}\cdot 8760} \approx 1-e^{-0,5} \approx 0,39.
\]
++++
Assim, temos uma probabilidade de aproximadamente 39% de que a lâmpada venha a falhar no primeiro ano de uso.
--

==== Perda de Memória

(((Distribuição, Exponencial, Perda de Memória)))

Assim como a distribuição Geométrica é a única distribuição discreta que possui perda de memória,
a distribuição exponencial é a única distribuição contínua que possui perda de memória.

Mais precisamente, considere o seguinte exemplo: 

.Ilustração da perda de memória da distribuição exponencial
====
Suponha que Pedro é funcionário da fábrica de lâmpadas e sua função é esperar
até que uma lâmpada falhe. Suponha que Pedro já esperou 6 meses e a lâmpada ainda não falhou,
isto significa que a probabilidade da lâmpada falhar nos próximos 30 dias será maior do que a probabilidade de falhar nos primeiros
30 dias de uso da lâmpada?

A resposta é não. Não importa o quanto tempo Pedro tenha esperado, a probabilidade de falha nos próximos 30 dias sempre será a mesma. 
Assim como para a distribuição geométrica, esta propriedade da distribuição exponencial é chamada de _perda de memória_.
====

Mais precisamente, seja latexmath:[$X$] uma variável aleatória seguindo distribuição exponencial com parâmetro latexmath:[$\lambda$].
Então, temos que para todo par de números reais positivos, latexmath:[$t,s$], vale
[latexmath]
++++
\[
P(X>t+s|X>t) = P(X>s).
\]
++++

De fato, temos que
[latexmath]
++++
\[
P(X>t+s|X>t) = \frac{P(X>t+s,X>t)}{P(X>t)} = \frac{P(X>t+s)}{P(X>t)},
\]
++++
no entanto, já vimos que, para todo x:[x>0], x:[P(X>x) = e^{-\lambda x}]. Daí,

[latexmath]
++++
\[
P(X>t+s|X>t) = \frac{P(X>t+s)}{P(X>t)} = \frac{e^{-\lambda (t+s)}}{e^{-\lambda t}} = e^{-\lambda s} = P(X>s).
\]
++++

Isto prova a perda de memória. Observe que aqui, assim como na geométrica, na realidade, 
mostra mais do que falamos. Não só diz que a próxima probabilidade não muda,
mas essencialmente diz o seguinte: se Pedro já esperou um certo 
tempo latexmath:[$t$] para a lâmpada falhar, e ela ainda não falhou,
as probabilidades de falhas dali para frente são as mesmas 
de como se ele tivesse começado a esperar naquele momento. Ou seja,
a distribuiçã exponencial ``esquece'' todo o passado que já foi esperado.

=== A Distribuição Gama

(((Distribuição, Gama)))

==== A Função Gama
 
(((Função, Gama)))

Definição: Função Gama::
+
--
A função gama, denotada por x:[\Gamma(\cdot)], é dada por
[latexmath]
++++
\[
\Gamma(p) = \int_0^\infty x^{p-1} e^{-x} dx,\quad p>0.
\]
++++
--

Realizando a integral por partes na função gama, fazendo x:[u = x^{p-1}] e 
x:[dv = e^{-x}dx], temos que

[latexmath]
++++
\[
\begin{array}{lll}
\displaystyle \Gamma(p) &=& \displaystyle -e^{-x}x^{p-1}\Big|_0^\infty - \int_0^\infty \big(-e^{-x}(p-1)x^{p-2}\big) dx\\
&=& \displaystyle 0 + (p-1)\int_0^\infty e^{-x} x^{p-2}dx\\
&=& (p-1)\Gamma(p-1).
\end{array}
\]
++++

Se x:[p = n] um número natural, então teremos que
[latexmath]
++++
\[
\Gamma(n) = (n-1)\Gamma(n-1) = \cdots = (n-1)(n-2)\cdots 1 \cdot \Gamma(1).
\]
++++

Porém, temos que
[latexmath]
++++
\[
\Gamma(1) = \int_0^\infty e^{-x}dx = 1.
\]
++++

Assim, temos que se x:[n] é um número natural, x:[\Gamma(n) = (n-1)!], e portanto a função gama generaliza o fatorial, e pode
ser pensada como o fatorial de números reais positivos.

==== Distribuição Gama

Definição: Variável Aleatória Seguindo Distribuição Gama::
+
--
Seja x:[X] uma variável aleatória contínua tomando valores não-negativos. Dizemos que x:[X]
segue distribuição gama com parâmetros x:[r>0] e x:[\alpha>0], se sua função de densidade for dada por
[latexmath]
++++
\[
f(x) = \frac{\alpha}{\Gamma(r)}(\alpha x)^{r-1} e^{-\alpha x},\quad x\geq 0.
\]
++++
Denotamos x:[X\sim Gama(r,\alpha)].
--

A distribuição gama é mais flexível que a distribuição exponencial, isto é, as densidades podem
assumir as mesmas formas das densidades da distribuição exponencial, mas também podem assumir
formas diferentes. Isso se deve à inclusão do segundo parâmetro.

Na figura abaixo apresentamos gráficos das funções de densidade da distribuição gama para alguns valores
de x:[r] e x:[\alpha]:

.Exemplo de funções de densidade da distribuição gama para valores de x:[r] e x:[\alpha] descritos no par ordenado x:[(r,\alpha)]
image::images/densidades/densidadegama.eps[scaledwidth="60%"] 

[NOTE]
====
Observe que se x:[X\sim Gama(1,\alpha)], então na realidade x:[X\sim Exp(\alpha)]. Assim, a distribuição 
exponencial é caso particular da distribuição gama. 

Além disso, por este fato, o parâmetro x:[\alpha] da distribuição gama é chamado de taxa, e 
o parâmetro x:[r] é chamado de parâmetro de forma.
====


Esperança e Variância::
+
--
É possível mostrar que se x:[X\sim Gama(r,\alpha)], então
[latexmath]
++++
\[
E(X) = \frac{r}{\alpha}\hbox{~e~}Var(X) = \frac{r}{\alpha^2}.
\]
++++
--


Exercício::
+
--
Suponha que o tempo de vida útil, em anos, de uma máquina de lavar é uma
variável aleatória x:[X] com função de densidade dada por
[latexmath]
++++
\[
f(x) = \frac{xe^{-x/2}}{4},\quad x\geq 0.
\]
++++
Determine a distribuição de x:[X]. 

Além disso, se o fabricante fornece seis meses de garantia para o produto,
qual a proporção de aparelhos que devemos esperar que usem
essa garantia?
--

_Solução_::
+
--
Olhando a função de densidade, observamos que não se trata
de uma distribuição exponencial, mas que se parece com uma
distribuição gama.

Comparando a densidade acima com a densidade geral da 
distribuição gama, vemos que x:[X] segue distribuição
gama com parâmetros x:[r=2] e x:[\alpha=1/2].

Como o tempo de vida está sendo dado em anos, queremos calcular
a probabilidade 
[latexmath]
++++
\[
P(X\leq 1/2) = \int_0^{1/2} \frac{xe^{-x/2}}{4} dx = \frac{1}{4}\int_0^{1/2} xe^{-x/2}dx.
\]
++++
Para calcular a probabilidade acima, vamos integrar por partes.
Fazendo x:[u=x] e x:[dv = e^{-x/2}dx], obtemos que
x:[du=dx] e x:[v = -2e^{-x/2}]. Desta forma,

[latexmath]
++++
\[
\begin{array}{lll}
P(X\leq 1/2) &=&  -\frac{1}{2}xe^{-x/2}\Big|_0^{1/2} - \frac{1}{4}\int_0^{1/2} (-2e^{-x/2})dx\\
&=& -\frac{e^{-1/4}}{2} + \frac{1}{2}\int_0^{1/2} e^{-x/2}dx\\
&=& -\frac{e^{-1/4}}{2} - e^{-x/2}\Big|_0^{1/2}\\
&=& -\frac{e^{-1/4}}{2} -(e^{-1/4}-1)\\
&\approx& 0,0265. 
\end{array}
\]
++++
Desta forma, é esperado que aproximadamente 2,65% das máquinas de lavar utilizarão o serviço de garantia.
--




