== Introdução à Inferência Estatística

=== Definições Básicas

Vamos começar relembrando dois conceitos básicos importantes de estatística, a saber, _população_ e _amostra_.

(((População)))
(((Amostra)))

De uma maneira mais precisa, temos a seguinte definição:

Definição: População::
+
--
O conjunto de todos os elementos, ou resultados, sob investigação é chamado de população.
--

Quando estamos lidando com uma população é interessante observar:

* Características mensuráveis (expressas por variáveis numéricas);

* Características qualitativas (expressas por variáveis nominais ou categóricas).

(((Parâmetros Populacionais)))

Definição: Parâmetros Populacionais::
+
--
Damos o nome de parâmetros da população ou parâmetros populacionais aos valores numéricos que caracterizam globalmente
uma população.
--

(((Amostra, Tamanho)))

Relacionadas à população temos as seguintes definições:

Definição: Amostra e Tamanho Amostral::
+
--
Um subconjunto da população é chamado de _amostra_. Chamamos o número de elementos da amostra de de
_tamanho amostral_.
--

[IMPORTANT]
====
O objetivo da inferência estatística é produzir afirmações sobre dada característica da população na qual estamos
interessados, a partir de informações colhidas de uma parte dessa população. Esta característica na 
população pode ser representada por uma _variável aleatória_.
====

A relação entre inferência e amostragem é ilustrada na figura abaixo:

.Amostragem e Inferência
image::images/inferencia/amos-infe.eps[scaledwidth="60%"] 

[NOTE]
====
* Se tivermos informações completas sobre a distribuição, não haverá necessidade de obter amostras.

* Podemos supor que as variáveis vêm de uma família de distribuições de probabilidade, mas não podemos
supor qual o valor do parâmetro. Por exemplo, podemos supor que os dados seguem distribuição normal,
mas não podemos informar os valores das médias e variâncias.

* Existem casos onde a amostragem é necessária. Por exemplo, se quisermos saber o número de glóbulos brancos.

* É importante que a amostra seja representativa da população, ou seja, que o comportamento da amostra seja próximo
do comportamento da população. Para garantir isso, é preciso saber escolher bem o tamanho amostral, e que a amostra
seja obtida aleatoriamente. 
====

=== Amostragem

(((Amostragem)))

==== Tipos de Amostragem

(((Amostragem, Probabilística)))
(((Amostragem, Não-Probabilística)))

Temos dois grandes grupos de amostragem:

* _Amostragem Probabilística_: O mecanismo de escolha dos elementos da amostra é tal 
que existe uma probabilidade conhecida de cada elemento da população
vir a participar da amostra.

* _Amostragem Não-Probabilística_: Não existe nenhum mecanismo probabilístico na seleção da amostra.

.Tipos de Amostragem Probabilística

(((Amostragem, Aleatória Simples)))

* *Amostragem Aleatória Simples* (AAS):
.. Supomos que a população é homogênea, ou seja, a característica que estamos procurando pode aparecer
em qualquer elemento da população com a mesma probabilidade;
.. Procedimento: Rotular os elementos da população e sortear os indivíduos que farão parte da amostra.

(((Amostragem, Sistemática)))

* *Amostragem Sistemática*:
.. Supomos que a população é homogênea;
.. Procedimento: Os elementos da população são ordenados, a retirada do primeiro elemento é aleatória, e 
a partir do segundo elemento a retirada é feita periodicamente (com período determinístico). Por exemplo,
o primeiro elemento é retirado aleatoriamente, e em seguida, retiramos o décimo elemento depois do primeiro
retirado, depois o décimo elemento após o segundo retirado, e assim por diante.

(((Amostragem, Estratificada)))

* *Amostragem Estratificada*:
.. Supomos que a população é heterogênea, ou seja, a característica que estamos procurando pode variar dependendo de 
onde os dados são retirados. Entretanto, supomos que podemos dividir a população em grupos (estratos) homogêneos;
.. Procedimento: A seleção dos elementos de cada estrato é realizada de forma aleatória, ou seja, realizamos uma
amostragem aleatória simples em cada estrato.

(((Amostragem, por Conglomerado)))

* *Amostragem por Conglomerado*:
.. Supomos que a população pode ser dividida em subgrupos (conglomerados) heterogêneos;
.. Procedimento: A amostragem é realizada sobre os conglomerados, e não mais sobre os indivíduos da população,
ou seja, realiza-se uma amostragem aleatória simples, onde os elementos escolhidos são os conglomerados a serem utilizados,
ao invés de já se sortear os elementos da amostra.

==== Distribuição Amostral

*Interesse*::
+
--
Uma medida que descreva certa característica da população. Normalmente temos interesse em um 
parâmetro desconhecido da população, seja média, variância, ou outro parâmetro.
--

(((Estatística)))

_Solução_::
+
--
A partir da amostra, podemos construir uma função, utilizando apenas os valores obtidos nesta amostra, para
descrever tal característica. Esta função é chamada de *estatística*.
--

[NOTE]
====
Como os valores da amostra são aleatórios, qualquer quantidade calculada em função dos elementos da amostra também 
será uma variável aleatória. Assim, as estatísticas, sendo variáveis aleatórias, terão alguma distribuição de probabilidade.
====

.Formalização do Problema

(((AAS)))

Seja x:[X_1,\ldots,X_n] uma amostra aleatória simples (AAS) de uma população de tamanho x:[n]. Para realizarmos uma afirmação
sobre algum parâmetro x:[\theta] da população (média, variância, etc.), utilizaremos uma estatística x:[T] que, como sabemos,
é uma função da amostra, isto é, x:[T=f(X_1,\ldots,X_n)], para alguma função x:[f].

(((Distribuição Amostral)))

[NOTE]
====
Quando conhecemos melhor o comportamento da estatística x:[T], ou seja, se conhecemos sua _distribuição amostral_, que
nada mais é que a distribuição de probabilidade da variável aleatória x:[T], poderemos realizar afirmações sobre o
parâmetro x:[\theta]. 


A distribuição amostral relata o comportamento da estatística x:[T], caso retirássemos todas as possíveis amostras de tamanho
x:[n].
====

===== Distribuição Amostral da Média

(((Média Amostral)))

Consideremos uma população identificada pela variável aleatória x:[X], cujos parâmetros _média populacional_ 
x:[\mu = E(X)] e variância populacional x:[\sigma^2 = Var(X)] são supostos conhecidos. Vamos tirar
todas as possíveis amostras de tamanho x:[n] dessa população e, para ccada uma, calcular a média
amostral x:[\overline{X}] dada por
[latexmath]
++++
\[
\overline{X} = \frac{1}{n} \sum_{i=1}^n X_i,
\]
++++
e em seguida vamos obter algumas propriedades de x:[\overline{X}].

.Exemplo de distribuição amostral de x:[\overline{X}]
====
Considere a população x:[\{1,3,5,7\}]. Sabemos que a média populacional é x:[\mu = 4,2] e a variância populacional é
x:[\sigma^2 = 4,16]. Se retiramos uma amostra de tamanho x:[n=2], segundo amostragem aleatória simples (então
todos os elementos possuem a mesma probabilidade de serem retirados), a distribuição amostral de 
[latexmath]
++++
\[
\overline{X} = \frac{X_1+X_2}{2}
\]
++++
será dada por

[format="csv",cols="3,2,2,2,2,2,2,2,2",frame="topbot",grid="none"]
|=======================
x:[\overline{x}],  1,2,3,4,5,6,7  ,Total
x:[P(\overline{X}=\overline{x})],    x:[1/25], x:[2/25],x:[5/25],x:[6/25],x:[6/25],x:[4/25],x:[1/25]     ,1
|=======================

Assim, 
[latexmath]
++++
\[
E(\overline{X}) = \sum_{i=1}^7 \overline{x}_iP(\overline{X}=\overline{x}_i) = 4,2,
\]
++++
e
[latexmath]
++++
\[
Var(\overline{X}) = 2,08.
\]
++++

====

Temos então a seguinte proposição:

Proposição::
+
--
Seja x:[X] uma variável aleatória com média x:[\mu] e variância x:[\sigma^2], e seja x:[(X_1,\ldots,X_n)]
uma AAS de x:[X]. Então,
[latexmath]
++++
\[
E(\overline{X}) = \mu\quad\hbox{~e~} Var(\overline{X}) = \frac{\sigma^2}{n}.
\]
++++
--

_Demonstração_::
+
--
Temos que
[latexmath]
++++
\[
\begin{array}{lll}
E(\overline{X}) &=& \displaystyle E\Big(\frac{1}{n}\sum_{i=1}^n X_i\Big)\\
&=& \displaystyle\sum_{i=1}^n \frac{E(X_i)}{n}\\
&=& \displaystyle\frac{1}{n} \sum_{i=1}^n \mu\\
&=& \displaystyle\frac{n\mu}{n}\\
&=&\mu.
\end{array}
\]
++++
e, usando que a variância de soma de variáveis independentes é dada pela
soma das variâncias, e as propriedades da variância, temos:
[latexmath]
++++
\[
\begin{array}{lll}
Var(\overline{X}) &=& \displaystyle Var\Big(\frac{1}{n}\sum_{i=1}^n X_i\Big)\\
&=& \displaystyle\sum_{i=1}^n Var\Big(\frac{X_i}{n}\Big)\\
&=& \displaystyle\frac{1}{n^2} \sum_{i=1}^n \sigma^2\\
&=& \displaystyle\frac{n\sigma^2}{n^2}\\
&=&\displaystyle\frac{\sigma^2}{n}.
\end{array}
\]
++++

--

===== Teorema Central do Limite

(((Teorema, Central do Limite)))

Vamos agora enunciar um dos principais resultados da probabilidade moderna: o teorema central do limite. 
A demonstração deste teorema pode ser encontrada em livros mais avançados de probabilidade.

Teorema Central do Limite::
+
--
Sejam x:[X_1,\ldots,X_n] uma AAS da variável aleatória x:[X], com distribuição comum satisfazendo
x:[E(X_i) = \mu] e x:[Var(X_i)=\sigma^2]. Como a amostragem foi AAS, temos que as variáveis são independentes.
Assim, se x:[n] é grande, temos que,
[latexmath]
++++
\[
P(\overline{X}\leq x) \approx \Phi_{\mu,\sigma^2/n}(x),
\]
++++
onde x:[\Phi_{\mu,\sigma^2}] é a função de distribuição de uma variável aleatória x:[N\sim N(\mu,\sigma^2/n)]. 

Assim, dizemos que x:[\overline{X}] segue aproximadamente distribuição normal com média x:[\mu] e variância
x:[\sigma^2/n]. 
--

Podemos fazer a mudança de variáveis:
[latexmath]
++++
\[
Z = \frac{\overline{X}-\mu}{\sigma/\sqrt{n}}.
\]
++++

Desta forma, o teorema central do limite nos diz que se x:[n] é suficientemente grande, temos que x:[Z] segue 
aproximadamente distribuição normal com média 0 e variância 1.

[NOTE]
====
No caso em que a distribuição de x:[X] é normal, a distribuição de x:[\overline{X}] será normal, mesmo para valores pequenos de x:[n].
====

===== Distribuição Amostral da Proporção

Seja x:[X] uma variável aleatória com distribuição Bernoulli com parâmetro x:[p], isto é, 
x:[P(X=1)=p] e x:[P(X=0)=1-p]. Temos que x:[E(X)=p] e x:[Var(X) = p(1-p)]. Considere
uma AAS de tamanho x:[n] dessa população. Seja 
[latexmath]
++++
\[
S_n = \sum_{i=1}^n X_i,
\]
++++
o número de indivíduos com a característica de interesse da amostra. Sabemos que 
x:[S_n\sim Bin(n,p)]. 

Pelo teorema central do limite temos que x:[\overline{X}] tem distribuição aproximadamente normal,
para x:[n] suficientemente grande. Seja x:[\widehat{p} = \overline{X}], a proporção amostral. Então, 
temos que
[latexmath]
++++
\[
\widehat{p} \stackrel{\hbox{aprox.}}{\sim} N\Big( p, \frac{p(1-p)}{n}\Big),
\]
++++
ou equivalentemente,
[latexmath]
++++
\[
Z = \frac{\widehat{p}-p}{\sqrt{p(1-p)/n}} \stackrel{aprox.}{\sim} N(0,1).
\]
++++












