== Introdução à Inferência Estatística

=== Definições Básicas

Vamos começar relembrando dois conceitos básicos importantes de estatística, a saber, _população_ e _amostra_.

(((População)))
(((Amostra)))

De uma maneira mais precisa, temos a seguinte definição:

Definição: População::
+
--
O conjunto de todos os elementos, ou resultados, sob investigação é chamado de população.
--

Quando estamos lidando com uma população é interessante observar:

* Características mensuráveis (expressas por variáveis numéricas);

* Características qualitativas (expressas por variáveis nominais ou categóricas).

(((Parâmetros Populacionais)))

Definição: Parâmetros Populacionais::
+
--
Damos o nome de parâmetros da população ou parâmetros populacionais aos valores numéricos que caracterizam globalmente
uma população.
--

(((Amostra, Tamanho)))

Relacionadas à população temos as seguintes definições:

Definição: Amostra e Tamanho Amostral::
+
--
Um subconjunto da população é chamado de _amostra_. Chamamos o número de elementos da amostra de de
_tamanho amostral_.
--

[IMPORTANT]
====
O objetivo da inferência estatística é produzir afirmações sobre dada característica da população na qual estamos
interessados, a partir de informações colhidas de uma parte dessa população. Esta característica na 
população pode ser representada por uma _variável aleatória_.
====

A relação entre inferência e amostragem é ilustrada na figura abaixo:

.Amostragem e Inferência
image::images/inferencia/amos-infe.eps[scaledwidth="60%"] 

[NOTE]
====
* Se tivermos informações completas sobre a distribuição, não haverá necessidade de obter amostras.

* Podemos supor que as variáveis vêm de uma família de distribuições de probabilidade, mas não podemos
supor qual o valor do parâmetro. Por exemplo, podemos supor que os dados seguem distribuição normal,
mas não podemos informar os valores das médias e variâncias.

* Existem casos onde a amostragem é necessária. Por exemplo, se quisermos saber o número de glóbulos brancos.

* É importante que a amostra seja representativa da população, ou seja, que o comportamento da amostra seja próximo
do comportamento da população. Para garantir isso, é preciso saber escolher bem o tamanho amostral, e que a amostra
seja obtida aleatoriamente. 
====

=== Amostragem

(((Amostragem)))

==== Tipos de Amostragem

(((Amostragem, Probabilística)))
(((Amostragem, Não-Probabilística)))

Temos dois grandes grupos de amostragem:

* *Amostragem Probabilística*: O mecanismo de escolha dos elementos da amostra é tal 
que existe uma probabilidade conhecida de cada elemento da população
vir a participar da amostra.

* *Amostragem Não-Probabilística*: Não existe nenhum mecanismo probabilístico na seleção da amostra.

.Tipos de Amostragem Probabilística

(((Amostragem, Aleatória Simples)))

. *Amostragem Aleatória Simples* (AAS):
.. Supomos que a população é homogênea, ou seja, a característica que estamos procurando pode aparecer
em qualquer elemento da população com a mesma probabilidade;
.. Procedimento: Rotular os elementos da população e sortear os indivíduos que farão parte da amostra.

(((Amostragem, Sistemática)))

. *Amostragem Sistemática*:
.. Supomos que a população é homogênea;
.. Procedimento: Os elementos da população são ordenados, a retirada do primeiro elemento é aleatória, e 
a partir do segundo elemento a retirada é feita periodicamente (com período determinístico). Por exemplo,
o primeiro elemento é retirado aleatoriamente, e em seguida, retiramos o décimo elemento depois do primeiro
retirado, depois o décimo elemento após o segundo retirado, e assim por diante.

(((Amostragem, Estratificada)))

. *Amostragem Estratificada*:
.. Supomos que a população é heterogênea, ou seja, a característica que estamos procurando pode variar dependendo de 
onde os dados são retirados. Entretanto, supomos que podemos dividir a população em grupos (estratos) homogêneos;
.. Procedimento: A seleção dos elementos de cada estrato é realizada de forma aleatória, ou seja, realizamos uma
amostragem aleatória simples em cada estrato.

(((Amostragem, por Conglomerado)))

. *Amostragem por Conglomerado*:
.. Supomos que a população pode ser dividida em subgrupos (conglomerados) heterogêneos;
.. Procedimento: A amostragem é realizada sobre os conglomerados, e não mais sobre os indivíduos da população,
ou seja, realiza-se uma amostragem aleatória simples, onde os elementos escolhidos são os conglomerados a serem utilizados,
ao invés de já se sortear os elementos da amostra.

==== Distribuição Amostral

*Interesse*::
+
--
Uma medida que descreva certa característica da população. Normalmente temos interesse em um 
parâmetro desconhecido da população, seja média, variância, ou outro parâmetro.
--

(((Estatística)))

_Solução_::
+
--
A partir da amostra, podemos construir uma função, utilizando apenas os valores obtidos nesta amostra, para
descrever tal característica. Esta função é chamada de *estatística*.
--

[NOTE]
====
Como os valores da amostra são aleatórios, qualquer quantidade calculada em função dos elementos da amostra também 
será uma variável aleatória. Assim, as estatísticas, sendo variáveis aleatórias, terão alguma distribuição de probabilidade.
====

.Formalização do Problema

Seja










