Este livro foi desenvolvido para a introdução do tema Probabilidade e
Estatística, não tendo a ambição de englobar toda esta vasta  área do
conhecimento humano. Probabilidade e Estatística são as áreas do
conhecimento humano que lidam com a incerteza.  Ambas lidam com
experimentos em que existe alguma variável (ou variáveis) que não
temos controle, e portanto, mesmo mantendo as mesmas condições, um
experimento pode fornecer vários resultados diferentes.

Probabilidade e Estatística podem ser vistas como ciências inversas.
Quando se estuda probabilidade, conhecemos o modelo em estudo
completamente, e estamos interessados em saber como os resultados do
experimento se comportam (por exemplo,  saber qual a probabilidade de
sair um resultado específico). Já na estatística, temos um conjunto de
dados, mas não sabemos qual o modelo probabilístico que gerou estes
dados, e portanto, tenta-se descobrir, a partir destes dados, qual o
modelo probabilístico que gerou estes dados.

Fenômenos aleatórios estão cada vez mais presentes em nossas vidas, e
cada vez mais estamos interessados em tentar entender estes fenômenos.
Gráficos estatísticos estão cada vez mais presentes em notícias, e é
importante saber interpretar esses gráficos corretamente. Quando vemos
os resultados de uma pesquisa eleitoral, é bom sabermos interpretar o
seu significado, etc.. Vale a pena citar também que ferramentas
estatísticas são utilizadas pelos bancos, para definir o rendimento em
fundos de investimento ou poupança, também são utilizadas pelas
seguradoras para definir qual o valor do seguro que você tem que pagar
(na prática eles calculam o seu risco), etc..

Para um aluno, probabilidade e estatística podem ser úteis da seguinte
forma: i) são úteis para realizar pesquisa científica; ii) são úteis
caso o aluno queira trabalhar em banco, seguradora, montadoras,
instituições financeiras em geral, controle de qualidade da produção
de algum item, etc..; iii) são úteis no dia-a-dia.

Finalizamos essa primeira parte do prefácio mostrando um exemplo de
como a probabilidade pode mostrar como a nossa intuição nos engana.
Suponha que temos uma sala com 50 pessoas. Qual a probabilidade de que
pelo menos duas delas façam aniversário no mesmo  dia do ano? Quando
falamos dia do ano, estamos falando dia e mês, não apenas dia.  Temos
365 dias (vamos desconsiderar o ano bissexto) e 50 pessoas. A intuição
nos diz que essa probabilidade não deve ser muito grande. Entretanto,
esta probabilidade é de 97%!


=== Público alvo

O público alvo desse livro são os alunos de Licenciatura em Computação, na
modalidade à distância footnote::[Embora ele tenha sido feito para atender aos alunos
da Universidade Federal da Paraíba, o seu uso não se restringe a esta 
universidade, podendo ser adotado por outras universidades do sistema UAB.].
Ele foi concebido para ser utilizado numa disciplina de 'Probabilidade e Estatística'.

[[como_estudar]]
=== Como você deve estudar cada capítulo

* Leia a visão geral do capítulo
* Estude os conteúdos das seções
* Realize as atividades no final do capítulo
* Verifique se você atingiu os objetivos do capítulo

.Na sala de aula do curso
* Tire dúvidas e discuta sobre as atividades do livro com outros integrantes do curso
* Leia materiais complementares eventualmente disponibilizados
* Realize as atividades propostas pelo professor da disciplina

////
Sempre termine os arquivos com uma linha em branco.
////
