[[cap_respostas]]

== Respostas das Atividades

=== Capítulo 1

*3.* 41,8

*4.* 13,8

*5.* 41

*6.* 9

*7.* 41

*8.* 14

*9.* 6,33

*10.* 5,52

*11.* Variância amostral = 67,75. Variância populacional = 65,81.

*12.* Variância amostral = 76,83. Variância populacional = 73,76.

*13.* 19,69%.

*14.* 63,52%.


=== Capítulo 2


*1.* Respostas:
--
a. V;

b. F;

c. V;

d. V;

e. V;

f. F;

g. V;

h. F;

i. V;

j. F;

l. V;

m. F;

n. V;

o. F.
--

*2.* Respostas:
--
a. x:[\{1,2,3,4,\{5\},\{6,7\}\}];

b. x:[\emptyset];

c. x:[\{1,2,3,4,\{5\},\{6,7\}\}];

d. x:[\{5,6,7\}];

e. x:[\{1,2,3,\{6,7\}\}];

f. x:[\{6,7\}];

g. x:[\{\{5\}\}].
--

*3.* Seja x:[M=\{1,2,3,4,\{1\},\{2\},\{3\},\{4\}\}]. Sejam x:[A = \{1,\{2\},3,\{4\}\}] e 
x:[B = \{\{1\},2,\{3\},4\}].
--
a. Justifique!;

b. x:[A^c = B], x:[B^c = A], x:[A\cup B^c = A], x:[A^c\cup B= B], x:[A^c\cup B^c = M], 
x:[A\cup B = M], x:[A\cup A^c = M], x:[B\cup B^c = M].

c. x:[A\cap B = \emptyset], x:[A^c\cap B^c = \emptyset], x:[A\cap A^c = \emptyset] e x:[B\cap B^c=\emptyset].
--


*4.*  x:[26\cdot 25\cdot 24 = 15600].

*5.*  6.

*6.*  x:[5^10 = 9765625].

*7.*  60.

*8.*  6840.

*9.*  8! = 40320.

*10.*  5! = 120.

*11.* 210.

*12.* 120.


*13.*  371.

=== Capítulo 3

*1.* Respostas:
--
a)  x:[A\cap B^c\cap C^c]

b)  x:[A\cap B\cap C^c]

c)  x:[A\cap B\cap C]

d)  x:[A\cup B\cup C]

e)  x:[(A\cup B\cup C)^c]

f)  x:[(A\cap B^c\cap C^c)\cup (A^c\cap B\cap C^c)\cup (A^c\cap B^c\cap C)]

--


*2.*  x:[\frac{{26 \choose 2}{26 \choose 2}}{{52\choose 4}}].

*3.* x:[\frac{12!}{12^{12}}].

*4.* Respostas:
--
a)  x:[\frac{7}{{10\choose 4}}]

b)  1/210 

c)  2/5

d)  2/3

e)  1/42
--

*5.* Respostas:
--
a)  1/2

b)  3/4

c)  11/20

d)  1/20

e)  3/10

f)  7/20

g)  9/20

h)  4/5

--



*6.* 14/15

*7.* Respostas:
--
a)  319/324

b)  203/23328

c)  7/792

--

*8.* Respostas:
--
a)  2/15

b)  1/2

--


*9.*  Sim


*10.* Respostas:
--
a)  0,92

b) 0,44

--




=== Capítulo 4


*1.* Respostas:
--
a) 1/21

b) 3/7

--


*2.* Respostas:
--
a) 3/4

b) 4/5
--

*3.* Respostas:
--
a) x:[P(X=0) = 1/2, P(X=1)=P(X=3)=P(X=4)=1/10, P(X=2)=1/5].

b) 5/8
--

*4.* Respostas:
--
a) x:[p(2) = 1/10, p(3)=1/5, p(4)=3/10, p(5)=2/5.]

b) x:[p(x) = 1/10] se x:[x\in \{3,4,8,9\}] e x:[p(x)=1/5] se x:[x\in \{5,6,7\}].
--



*6.* Respostas:
--
a) 2

b) 1/4

c) x:[F(x) = \begin{cases} 1 - x^2,&\hbox{~se~}x\geq 1,\\ 0,&\hbox{~se~} x<1.\end{cases}]

--

*7.* x:[f_Y(y) = \frac{1}{2\sqrt{y}},\quad 0<y<1].

*8.* x:[f_Y(y) = (2/\pi)^{1/2} \exp\{-y^2/2\},\quad y>0.]

*9.* 
[latexmath]
++++
\[
f_Y(y) = \begin{cases}
\frac{1}{4\sqrt{y}}\big(1+e^{-\sqrt{y}}\big),&\hbox{~se~}0\leq y <1,\\
\frac{1}{4\sqrt{y}}e^{-\sqrt{y}},&\hbox{~se~}y\geq 1,\\
0,&\hbox{caso contrário}.
\end{cases}
\]
++++

=== Capítulo 5

*1.* Respostas:
--
a)  x:[ p(-16) = 1/12, p(-7) = 1/6, p(2) = 13/36, p(11)=2/9, p(20) = 1/6].

b)  x:[E(X) = 4, Var(X) = 108,5].
--

*2.* 7/2.

*3.* média = 12,3; variância = 9,3.

*4.* Resposta:
--
b) x:[E(X) = \infty]
--

*5.* Respostas:
--
a) x:[E(X)=0];

b) x:[E(|X|) = 1.]

c) x:[Var(X) = 2.]

--



=== Capítulo 6

*1.* Respostas:
--
a)  Binomial com x:[n=15], x:[p=0,8].

b)  0,035

c)  0,83
--


*2.* Respostas:
--
a)  Hipergeométrica com parâmetros 6, 9 e 12. 

b)  1/2.

--

*3.* Respostas: 
--
a) Binomial com x:[n = 10] e x:[p = 1/5.]

b)  x:[4,2\cdot 10^{-6}].

c)  x:[0,62].

--

*4.* Respostas:
--
a) Geométrica com x:[p=0,3].

b)  7

--

*5.* Respostas:
--
a)  Binomial negativa x:[n = 2] e x:[p=2/5].

b)  0,7667

--

*6.* Respostas:
--
a)  1/3

b)  0,057
--

*7.*  x:[\log(2)].

*8.* 0,9631

*9.* Respostas:
--
a)  0,1339

b)  0,2851

c)  0,9380

--




=== Capítulo 7

*1.*  3/5

*2.* Respostas:
--
a)  58,2%

b)  321

--

*3.* Respostas:
--
a)  0,9772

b)  0,8413

c)  0,44

d)  -2

e)  14,32

f) x:[ [-2,84,12,84\]].

--

*4.* Respostas:
--
a)  2,41%

b)  593ml

--

*5.* Respostas:
--
a)  214,6

b)  2431g

--

*6.*  0,281.

*7.*  x:[\frac{b^{n+1}-a^{n+1}}{(n+1)(b-a)}]

*8.*  x:[n!/\lambda^n.]

*9.*  7


*10.* Respostas:
--
a)  35/128

b)  12393/16384.

--

*11.* x:[f_Y(y) = y^{-1}(2\pi)^{-1/2} \exp\{-(\log(y))^2/2\},\quad y>0].

*12.* x:[Y] segue distribuição Gama x:[(1/2,1/2)].



=== Capítulo 8

*1.* Intervalo de 90% x:[[1,73;1,77\]]. Intervalo de 99% x:[[1,71;1,79\]].

*2.* Intervalo de 90% x:[[4,80;5,59\]]. Intervalo de 95% x:[[4,73;5,67\]]. Intervalo de 99% x:[[4,58;5,82\]].

*3.* Intervalo de 90% x:[[109,18;110,82\]]. Intervalo de 95% x:[[109,02;110,98\]].

*4.*  Intervalo de 90% x:[[0,55;0,65\]]. Intervalo de 99% x:[[0,53;0,67\]].

*5.* Intervalo de 96% x:[[0,46;0,74\]]. Como o valor x:[p=0,5] pertence ao intervalo de confiança de 96%, podemos
afirmar, com 96% de confiança que, sim, a moeda é honesta.

*6.* Intervalo de 96% x:[[0,20;0,29\]]. Baseado no intervalo de confiança, temos que se x:[X_i] é uma
variável aleatória indicando que a x:[i]-ésima casa é alugada, então, x:[X_i] segue distribuição
Bernoulli com o parâmetro x:[p] pertencente a este intervalo. O número de casas alugadas então é dado por
[latexmath]
++++
\[
N = \sum_{i=1}^{20.000} X_i.
\]
++++
Portanto, x:[N\sim Bin(n,p)], onde x:[p] pertence a este intervalo. Como o número esperado de casas alugadas
é dado por
[latexmath]
++++
\[
E(N) = 20.000 p.
\]
++++
Temos que o número esperado de casas alugadas pertence ao intervalo
[latexmath]
++++
\[
[4000,5800].
\]
++++

*7.* Intervalo de 90% x:[[-0,61;1,41\]].

*8.* Intervalo de 95% x:[[-7,09;4,09\]].

*9.* Intervalo de 95% x:[[0,56; 0,64\]]. Como 0,5 = 50% não pertence ao intervalo, e o intervalo contém,
com 95% de confiança, a média verdadeira. Temos que com 95% de confiança a média verdadeira, isto é,
a proporção de donas de casa que preferem o detergente x:[A], é maior do que 50%. Desta forma,
a companhia tem evidência suficiente para NÃO confiar no funcionário.


*10.* Intervalo de 90% x:[[0,11;0,16\]]. Como 0,05 = 5% não pertence ao intervalo, e o intervalo contém,
com 90% de confiança, a média verdadeira. Temos que com 90% de confiança a média verdadeira, isto é,
o percentual de artigos defeituosos produzidos pelo novo empregado, é maior do que 5%. Desta forma,
podemos sim afirmar que o novo empregado produz peças com índice de defeitos maior do que o existente.

*11.* a) -0,9921.

b) x:[\widehat{Y} = 32,28 - 1,7 X].

c) Temos que para x:[X=0], x:[\widehat{Y} = 32,28].

*12.* a) x:[\widehat{Y} = 386,84 - 1,87 X].

b) Temos que para x:[X=60], x:[\widehat{Y} = 274,64]. Para x:[X=120], temos x:[\widehat{Y} = 162,44].

c) x:[R^2\approx 0,79].

*13.* a) x:[\widehat{Y} = 1,81 X].

b) x:[R^2\approx 0,30]

c) x:[\widehat{X} = 0,4 + 0,16X].

d) x:[R^2\approx 0,30].































